- upload-apk.sh
Its working, there is only token issue, its gets exposed as Travis logs when there is some error in script.
My API_KEY won't work as I don't have write permission on fossasia's pslab-android repo. So 
add @wavicles API_KEY once KEYS aren't exposed in Travis logs.
I opened an issue on open-event-android https://github.com/fossasia/open-event-android/issues/1399
I will do necessary changes when it gets solved on open-event-android.
Tested it with my own repo, its working.
> Autogenerate apk in apk branch

- README.md
- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/org/fossasia/pslab/activity/MainActivity.java
- app/src/main/java/org/fossasia/pslab/fragment/SettingsFragment.java
- app/src/main/res/layout/settings_fragment.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/xml/settings_preference_fragment.xml
Fixes #44 
Added auto-start option in settings activity with Material Theme.
Further settings needed by project would be added later.
> added auto-start option in settings fragment

- app/src/main/java/org/fossasia/pslab/communication/digitalChannel/DigitalChannel.java
Completed `loadData` method in `DigitalChannel.java`
**Note**
> In `ScienceLab.java` there is a method to fetch states. 
> The parameter passed as `initialState` is a python dictionary as observed from the  [`sciencelab.py`](https://github.com/fossasia/pslab-python/blob/development/PSL/sciencelab.py#L2493) . The equivalent implementation was a HashMap in `ScienceLab.java`
> Fixes #107 : DigitalChannel loadData method completed!

- app/src/main/java/org/fossasia/pslab/fragment/ApplicationsFragment.java
When the screen orientation is changed, the grid rows will change accordingly avoiding huge icons
| Portrait | Landscape |
| ---- | ---- |
| ![Portrait](https://cloud.githubusercontent.com/assets/14261304/26285056/604e81b2-3e37-11e7-8233-399ac0f489ba.png) | ![Landscape](https://cloud.githubusercontent.com/assets/14261304/26285057/605b1bac-3e37-11e7-845e-69e40e6c761e.png) |
> Fix #120 : Applications grid rows change in landscape orientation

- app/src/main/java/org/fossasia/pslab/communication/peripherals/SPI.java
I'm in the middle of porting SX1276 and came across a new method in `SPI`. In the `SPI` in python repo has a new method added. This implements it in the android repo!
> Fix #161 : Added xfer function to SPI methods

- app/src/main/java/org/fossasia/pslab/fragment/LAChannelModeFragment.java
- app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
- app/src/main/java/org/fossasia/pslab/items/ChannelAxisFormatter.java
- app/src/main/java/org/fossasia/pslab/others/ChannelAxisFormatter.java
- app/src/main/res/layout/logic_analyzer_logic_lines.xml
Fixes issue #169  #173 
Changes: 
- Modified Channel selection at different modes as per pslab-desktop-app
- Named logic lines according to which Channel was selected in Channel Mode select Fragment
For Three channel mode, input channels are locked to ID1, ID2, ID3
In two Channel Mode, **SEN** & **CNTR** are selected which are passed to next fragment.
Added time label also in latest commit.
> Logic Analyzer UI modified as per pslab-desktop-app and labels indicate channel

- app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
Fixes issue #175 
Changes: 
- Called `initializeVariables()` and `runInitSequence` method in the constructor.
- Instead of calling `y.clear`, reinitialised `y` in [this](https://github.com/fossasia/pslab-android/blob/master/app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java#L2584) line to remove the error.
@viveksb007 @asitava1998 can you please check this with your device.
none
> Removed error from runInitSequence method

- app/build.gradle
- app/src/main/java/org/fossasia/pslab/communication/CommunicationHandler.java
Partly Fixes #156 
Changes: modified write function to support device with API level < 18
Tested by jithin on device with API level 15, there was  a permission issue #179  which @akarshan96 is taking care of.
> modified write function to support device with API level < 18

- app/src/main/res/drawable/navigationbar_text_color.xml
- app/src/main/res/layout/activity_control.xml
- app/src/main/res/values-v21/styles.xml
Fixes issue #170 
Changes: 
* Enables highlighting of bottom navigation bar.
* The active bar is displayed in white and inactive in black.
* Only meant for API level > 21.
> Fixes #170 highlights bottomnavigation bar

- app/src/main/res/layout/fragment_control_main.xml
Fixes issue #167 
Changes: 
* Earlier, the keyboard used to pop-up whenever Control UI was opened due to presence of edit-texts.
* Removed the focus on opening. Keyboard pops up only when an edit-text is clicked.
Screenshots cannot show the difference of the actual working though.
> Fixes #167 removes focus from edittext on opening Control UI

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/fossasia/pslab/fragment/ApplicationsFragment.java
Fixes issue #194 
Changes: State of Activity is retained on screen rotation so that scienceLab object doesn't re-initialises itself.
> Fixes re-initialisation on screen rotation

- app/src/main/java/org/fossasia/pslab/fragment/ApplicationsFragment.java
Fixes issue #207 
Now App doesn't crash when coming back to Application Fragment from specific Application say Logic Analyser after changing screen orientation.
> Fixed App crash when coming back to application fragment after screen orientation

- app/src/main/java/org/fossasia/pslab/fragment/LAChannelModeFragment.java
Fixes issue #218 
Changes: Now spinner of Single / Two channel mode is enabled after selecting Three/Four channel mode and switching back.
> spinner selection fixed for Single / Two Channel Mode

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/fossasia/pslab/activity/MainActivity.java
- app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
- app/src/main/java/org/fossasia/pslab/fragment/HomeFragment.java
- app/src/main/java/org/fossasia/pslab/others/PreferenceManager.java
- app/src/main/java/org/fossasia/pslab/receivers/USBDetachReceiver.java
- app/src/main/res/values/strings.xml
Fixes issue #72 and #216 
Changes: 
- Abrupt disconnection is handled by receiving USB_DEVICE_DETACHED intent in BroadcastReceiver.
- prevents version read again and again by storing it as preference when device is connected and discarding it when its disconnected.   
[APK Link](https://drive.google.com/open?id=0B30IF3fyX4Q3M2xQM3hFVHBNVjg) for testing.
App crashes if device is removed during initialisation as initialisation is going on another thread ( bulkTransfer methods are called before broadcastReceiver can handle things ) and thread.stop() and thread.kill() methods are deprecated. Would look for something that prevents app crash and thread would be killed on its own after some time.
One commit from previous PR is reflected as I forgot to change branch.
> Fixed : abrupt disconnections of device and prevent version read during initialisation

- app/src/main/AndroidManifest.xml
Fixes #221 
Changes:
- replaced default Android icon with the specific pslab icon
> replaced default Android icon with the specific pslab icon

- app/src/main/java/org/fossasia/pslab/communication/PacketHandler.java
- app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
- app/src/main/java/org/fossasia/pslab/fragment/HomeFragment.java
- app/src/main/java/org/fossasia/pslab/receivers/USBDetachReceiver.java
Fixes issue #258 
Changes: Stored Version in ```PacketHandler Version``` variable and read from it during the time app is opened. Version is read only once when device is connected.
> fixed version read between screens to HomeFragment

- app/src/main/res/layout-land/logic_analyzer_select_channel_mode.xml
- app/src/main/res/layout-sw600dp/fragment_xyplot.xml
- app/src/main/res/layout/fragment_xyplot.xml
- app/src/main/res/layout/logic_analyzer_select_channel_mode.xml
- app/src/main/res/values/strings.xml
Fixes issue #296 
Changes:
- Added button selector background to all the buttons in Oscilloscope and Logic Analyzer
- Added hard-coded strings to strings.xml in the respective button views
| Logic Analyzer | Oscilloscope |
| -------- | ------- |
| ![after](https://user-images.githubusercontent.com/14261304/28072245-0c2f863c-6685-11e7-8226-4a170f0a52b8.png) | ![after2](https://user-images.githubusercontent.com/14261304/28072393-69519292-6685-11e7-98ed-412d7ad1c635.png) |
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1139163/app-debug.apk.zip)
> Fixes #296 : Same button layout in Osc and LA

- app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
Fixes issue #316
Changes: 
- Caught the exception occurring when dividing by zero voltages when no capacitor is connected
> Crash fixed
> Fixes #316 : App crash fix when capacitance is measured

- app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
Fixes issue #323 
Changes:
- Thread to monitor checkboxes would start only if device is connected.
> Fixes #323: prevent unncessary running thread

- app/src/main/java/org/fossasia/pslab/fragment/HomeFragment.java
Fixes issue #327 
Changes: 
- Added a progress dialog box to display device initialization in home fragment
[Screencast](https://drive.google.com/open?id=0B5su2_aUn8g7TmlnMWlXa1I2VDQ)
> Fixes #327 : Progress Dialog for device initialization

- app/src/androidTest/java/org/fossasia/pslab/MainActivityTest.java
Partially Fixes issue #333 
Changes: 
- Added test to check views inside all fragments of MainActivity
P.S : would have added test for activity too but inside activity sciencelab methods are used and sciencelab is ```null``` in tests (test were failing due to null sciencelab object), would look for mocking objects in tests and add tests for each Activities. 
> checked views inside fragments

- app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
- app/src/main/res/layout-sw600dp/fragment_channel_parameters.xml
- app/src/main/res/layout/fragment_channel_parameters.xml
Fixes issue #353 
Changes: 
- Removed default selection from xml files related to oscilloscope activity
> Fix #353 : Removed default selection CH1 in OSC

- app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
- app/src/main/java/org/fossasia/pslab/others/AudioJack.java
Fixes issue #356 
Changes:
- audio buffer read is processed and plotted successfully.
- Currently I mapped the signed 16 bit value to -3 to 3 V and x axis as 1,2,3,.. (Refer [post](https://docs.google.com/document/d/1lXNzQfmXNBjjDyTzHT_q7gO3b7JWyr2_0oCFqavEZqM/edit?usp=sharing) for technical details)
X axis values (time-axis) needs to be calculated using current sampling rate of audio data and Y-axis values need to be calibrated using multi-meter. I don't have instruments to calibrate right now.
Screencast : https://photos.app.goo.gl/tp2N9uAwX1xvamAI3
> Fixes #356 audio buffer processed and plotted successfully

- app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
Fixes #383 
Changes: 
- Fixed the bug in fetchChannel method. This bug was causing the fetchChannel method to return wrong signals while capturing 1024 samples in PR #298 
Apk:
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1184201/app-debug.apk.zip)
Capturing 1024 samples and W1 generates sinewave
> fixes bug in fetchChannel method

- app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
- app/src/main/java/org/fossasia/pslab/adapters/ControlMainAdapter.java
- app/src/main/java/org/fossasia/pslab/experimentsetup/OhmsLawSetupExperiment.java
- app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorCBSetup.java
- app/src/main/java/org/fossasia/pslab/others/AudioJack.java
- app/src/main/java/org/fossasia/pslab/others/MathUtils.java
- app/src/main/res/layout/ohms_law_setup.xml
Partially Fixes issue #378 
Partially Fixes issue #380 
Changes:
Added experiment functionality 
Shifted **map()** function to MathUtils and modified its usages.Would gradually shift functions like **linspace()**,etc in numpy whose implementation code is repeated quite a lot of times.  
Ohms experiment setup screencast : https://photos.app.goo.gl/YPXiO7i1wwyBd8uF2
> Added experiment setup functionality

- app/src/main/java/org/fossasia/pslab/experimentsetup/OhmsLawSetupExperiment.java
Fixes issue #407 
Changes:
- Current value is changed before reading voltage from channel.
> Fixes #407 current change enabled in Ohm's law experiment

- app/src/main/java/org/fossasia/pslab/experimentsetup/NFETOutputCharacteristicsExperiment.java
- app/src/main/java/org/fossasia/pslab/experimentsetup/OhmsLawSetupExperiment.java
- app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorCBSetup.java
- app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorCEOutputSetup.java
- app/src/main/java/org/fossasia/pslab/experimentsetup/ZenerSetupFragment.java
Fixes issue #421 
Changes: 
- Added validation to voltage levels as follows;
- PV1 [-5V ~ 5V]
- PV2 [-3.3V ~ 3.3V]
- PV3 [0 ~ 3.3V]
| Minimum value | Maximum value |
| ------ | ------ |
| ![imgcheckmin](https://user-images.githubusercontent.com/14261304/28980995-65518c0a-7982-11e7-9e9d-857c1553388d.png) | ![imgcheckmax](https://user-images.githubusercontent.com/14261304/28981005-716f5c24-7982-11e7-87bc-ab25ce605607.png) |
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1201236/app-debug.apk.zip)
> Fixes #421 : Limit voltage values within an appropriate range

- app/src/main/java/org/fossasia/pslab/activity/SensorActivity.java
- app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentMain.java
- app/src/main/res/layout/activity_sensor.xml
- app/src/main/res/layout/sensor_main.xml
Fixes issue #453 
Changes:
- fixed App crash on clicking Sensor Quick View tile when device isn't connected
- Added appropriate message for user when device isn't connected and trying to scan sensors
- Optimised layout a bit
> Fixes #453 Fixed App crash on clicking Sensor Quick View

- app/src/main/res/layout/diode_configure_dialog.xml
- app/src/main/res/layout/nfet_output_characteristic_dialog.xml
- app/src/main/res/layout/ohms_law_setup.xml
- app/src/main/res/layout/transistor_cb_configure_dialog.xml
- app/src/main/res/layout/transistor_ce_output_configure_dialog.xml
- app/src/main/res/values/strings.xml
Fixes issue #451 
Changes: 
- Exported hardcoded string resources to `strings.xml` file
> Fixes #451 : Exported string resources in saved experiments

- upload-apk.sh
Fixes issue #471 
Changes:
- Added API Token in travis settings and made an api call to update apk on Appetize.io
Reference : [Appetize docs](https://appetize.io/docs)
> Fixes #471 Used Appetize API to update apk preview

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/fossasia/pslab/activity/SensorDataLoggerActivity.java
- app/src/main/java/org/fossasia/pslab/activity/ShowLoggedData.java
- app/src/main/res/layout/activity_show_logged_data.xml
- app/src/main/res/menu/activity_sensor_data_logger.xml
- app/src/main/res/menu/activity_show_logged_data.xml
- app/src/main/res/values/strings.xml
Fixes issue #490 
Changes:
- Added menu to View Logged Data which directs to ShowLoggedData Activity.
- In ShowLoggedData Activity there is ListView to show logged data and a menu Item to export Logged Data.
Would open other issues for below tasks.
There should be two more layers between DataLoggerActivity and ShowLoggedData Activity:
1. To Select which sensors logged data user wants to see.
2. Which trial of that sensors logged data user wants to see. ( In case when user logged same sensor's data at different times ).
> Fixes #490 created UI to view locally logged data

- app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java
Fixes issue #497 
Changes: 
- Added missing method call for N-FET Transfer Characteristics Experiment
> Fixes #497 : NFET Transfer Characteristics Experiment reinstating

- app/src/main/java/org/fossasia/pslab/fragment/SettingsFragment.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings_preference_fragment.xml
Fixes issue #545 
Changes: 
- Added preference for exporting sensor data `.txt` or `.csv`.
- Based on this preference data would be exported in Data Sensor Logger Activity.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/12713808/29485387-a695ad46-84ee-11e7-8edb-59066e55992d.png"></td>
<td><img src="https://user-images.githubusercontent.com/12713808/29485388-a6968e14-84ee-11e7-8f51-3eb7efd6ca9b.png"></td>
</tr>
</table>
> Fixes #545 Added data format option in app settings

- upload-apk.sh
Fixes issue #535 
Changes: 
- renamed apk from master branch to apk-release.apk
This should create `apk-release.apk` when there is commit on master branch and `app-debug.apk` when there is commit on development branch.
> Fixes #535 generated different apk for master branch

- app/src/main/java/org/fossasia/pslab/activity/ShowLoggedData.java
Fixes issue #565 
Changes: 
- File name is saved as `sensor_timstamp.txt` or `sensor_timstamp.csv`, thus its unique always.
> Fixed #565 exported data over written fixed

- .travis.yml
- app/src/androidTest/java/org/fossasia/pslab/MainActivityTest.java
Fixes issue #591 
Changes:
- Added command to enable UI test during travis build
- Modified MainActivity test
P.S: emulator with API 25 had some no abi issue, so used api level 22 emulator for UI tests on app.
> added command for UI check in travis

- README.md
Fixes issue #599 
Changes:
- Replaced stack-overflow post link with fossasia blog post on [**Android App debugging over Wi-Fi for PSLab**](http://blog.fossasia.org/android-app-debugging-over-wifi-for-pslab/).
> updated link for wi-fi debugging post on fossasia blog

- app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
Fixes issue #611 
Changes:
- modified fetch routines to prevent adding **ack** bytes as a data point. 
Distortion is fixed now.
Apk for testing 
[app-debug.apk.tar.gz](https://github.com/fossasia/pslab-android/files/1272381/app-debug.apk.tar.gz)
> Fixed #611 modified fetch routines to prevent adding ack bytes as a data point

- app/src/main/java/org/fossasia/pslab/activity/SplashActivity.java
Fixes issue #639 
Changes: app closes now on backpress
> Fix #639 app closes properly on backpress

- app/src/main/res/layout/activity_perform_experiment.xml
Fixes issue #679 
Changes: Removed the redundant play button from the experiments screen by deleting it from the layout file.
> Fixes #679 Removed redundant play button from the experiments screen

- app/src/main/java/org/fossasia/pslab/activity/MainActivity.java
- app/src/main/res/layout-sw600dp/activity_main.xml
- app/src/main/res/values/dimens.xml
Fixes issue #684 
Changes: Redefined activity_main.xml such that the Navigation Drawer always remains open when viewed on devices with screen widths greater than 600
>  Fixes #684 Enhancement of layouts for Tablet view

- app/src/main/java/org/fossasia/pslab/others/EditTextWidget.java
Fixes issue #694 
Changes:Cursor is positioned at the end of editText
> Fix #694 cursor is positioned at the end of editText

- app/src/main/java/org/fossasia/pslab/activity/ControlActivity.java
- app/src/main/java/org/fossasia/pslab/activity/LogicalAnalyzerActivity.java
- app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
- app/src/main/java/org/fossasia/pslab/activity/SensorActivity.java
- app/src/main/java/org/fossasia/pslab/activity/SensorDataLoggerActivity.java
- app/src/main/java/org/fossasia/pslab/activity/WavegenActivity.java
- app/src/main/res/values/strings.xml
Fixes issue #692
Changes:  Included warning dialog when the back button is pressed for Applications
APK FILE
[app-debug.zip](https://github.com/fossasia/pslab-android/files/1615921/app-debug.zip)
> Fixes #692 Inclusion of warning dialogs

- app/src/main/java/org/fossasia/pslab/activity/ControlActivity.java
Fixes issue #696 
Changes:  removed unnecessary refresh in ControlActivity
> Fix #696 removed unnecessary refresh in ControlActivity

- app/src/main/java/org/fossasia/pslab/fragment/ControlFragmentAdvanced.java
Fixes issue #700 
Changes: dialogs get cancelled on backPress in controlFragmentAdvanced
> fix #700 dialogs get cancelled on backPress

- app/src/main/java/org/fossasia/pslab/activity/AboutUs.java
Fixes issue #702 
Changes: added PSLab links in about us
> fix #702 add PSLab links in about us

- app/src/main/assets/DOC_HTML/apps/F_WATER_RESISTANCE.md
The path to find the image was incorrect and so the image was not appearing. In this update, the path is fixed.
Fixes issue #740 
Changes: Path to find the image was corrected
> Updated Water Resistance file

- app/src/main/java/org/fossasia/pslab/fragment/ControlFragmentRead.java
Fixes issue #732 
Changes:
- Added string formatting to resistor values (Note that the read resistor values were scaled)
The following gif demonstrate the following measurements;
- Open circuit measurement (Infinity)
- Measuring 52k
- Measuring 210k
- Short circuit
> Fixes #732: Resistance values displayed in formats

- .github/PULL_REQUEST_TEMPLATE
Fixes issue #730 
Changes: 
- Added a section to upload APK file along with the PR
> Fixes #730: Add APK requirement to PR template

- .travis.yml
- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- upload-apk.sh
- Upgrade to API 27
- Upgrade to Build Tools 27.0.3
- Upgrade Gradle to 4.5.1
- Upgrade Android Gradle Plugin to 3.1.0
- Upgrade Support Lib to 27.1.1
- Upgrade Realm to 5.0.1
- Update all dependencies
- Change APK upload script accordingly
Fixes #783
> chore: Update build tools, android version and dependencies

- app/src/main/AndroidManifest.xml
Fixes issue #769 
Changes: Splash Screen's Orientation is set to portrait mode so that multiple opening of pages didn't occur while changing orientation of splash screen.
> Orientation of splash screen changed

- app/src/main/java/org/fossasia/pslab/activity/MainActivity.java
Fixes #826 
Changes: Removed Overriding animations which caused trouble of blinking screen
> fix: removed Overriding animation

- app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
Fixes #856 
Changes: Changed orientation of the screen after closing of oscilloscope activity so that the screen doesn't remain as it is and there are no memory leaks.
[app-debug.zip](https://github.com/fossasia/pslab-android/files/1994989/app-debug.zip)
> fix: Problem with oscilloscope activity solved

- docs/commitstyle.md
Fixes #842 
Changes: 
- Added commit style guide to PSLab-Android app repository. Content derived from open-event-android repository
> docs: added commitstyle documentation

- app/build.gradle
- build.gradle
Fixes #883 
Changes:
- Added versions to config file and called from there
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/2017629/app-debug.apk.zip)
> fix: gradle versions in config files

- app/src/main/java/org/fossasia/pslab/activity/LogicalAnalyzerActivity.java
Fixes #907 
Changes: Changed onBackPressed method to come to Instrument Activity rather than going to Main Activity
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2042453/app-debug.zip)
> fix: Fixed onBackPressed method to come to instrument activity

- app/build.gradle
Fixes #956 
Changes: 
Updated version to `1.1.3` and versioncode to `5`
> chore: app version updated

- app/src/main/java/org/fossasia/pslab/fragment/HomeFragment.java
Fixes #947 
Changes: Changed the onKeyListner for WebView so that it go backs a page if any or closes the WebView when back button is pressed
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2060377/app-debug.zip)
NOTE: All the changes in the declarations and the import statements are due to code reformatting
> fix: Handled back button press in Webview of Home Fragment

- app/build.gradle
Fixes #988 
Changes: 
- Upgraded the app version to `1.1.5`
> chore: updated app version

- app/src/main/java/org/fossasia/pslab/activity/MultimeterActivity.java
Fixes #1017 
**Changes**:
The readings of voltage is now rounded to two decimal places.
**Checklist**:
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/2093860/app-debug.apk.zip)
> refactor:reduced the decimal places of voltage reading to two

- app/src/main/java/org/fossasia/pslab/activity/LuxMeterActivity.java
- app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentConfig.java
- app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentData.java
Fixes #1029 
**Changes**: 
Passing data from fragment config to fragment data in the lux meter instrument using a method when fragment gets destroyed.
[lux_meter_data.zip](https://github.com/fossasia/pslab-android/files/2100056/lux_meter_data.zip)
> refactor: fixed configure tab data pass

- app/src/main/java/org/fossasia/pslab/fragment/InstrumentsFragment.java
- app/src/main/res/drawable/tile_icon_lux_meter.xml
Fixes #1046
**Changes**: 
New vector drawable for the tile lux meter added. 
[luxmeter_card_icon.zip](https://github.com/fossasia/pslab-android/files/2107922/luxmeter_card_icon.zip)
> fix: New design for lux meter tile

- app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentConfig.java
Fixes #1059 
**Changes**: 
Focus changed listener has a try catch block to remove null pointer exception on destroy view
> None
[lux_meter_fix.zip](https://github.com/fossasia/pslab-android/files/2107934/lux_meter_fix.zip)
> fix: Fix configure fragment crash when using edit text box

- app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
Fixes #1001 
**Changes**: 
Channel CH1 and CH2 are also working now which were completely nonfunctional initially.
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/2108239/app-debug.apk.zip)
> refactor:solved communication issues in CH2 and CH1

- app/src/main/java/org/fossasia/pslab/communication/CommandsProto.java
Fixes #1002 
**Changes**: 
The data is fetched from PSLab device block by block. The previous block size was large and hence reduced it to 60.
[Oscilloscope_channel_read.zip](https://github.com/fossasia/pslab-android/files/2109491/Oscilloscope_channel_read.zip)
> fix: Channel read errors

- app/build.gradle
- app/src/main/java/org/fossasia/pslab/PSLabApplication.java
- app/src/main/java/org/fossasia/pslab/fragment/ChannelParametersFragment.java
- app/src/main/java/org/fossasia/pslab/fragment/ControlFragmentAdvanced.java
- app/src/main/java/org/fossasia/pslab/fragment/ControlFragmentMain.java
- app/src/main/java/org/fossasia/pslab/fragment/ControlFragmentRead.java
- app/src/main/java/org/fossasia/pslab/fragment/DataAnalysisFragment.java
- app/src/main/java/org/fossasia/pslab/fragment/ExperimentDocFragment.java
- app/src/main/java/org/fossasia/pslab/fragment/ExperimentDocMdFragment.java
- app/src/main/java/org/fossasia/pslab/fragment/ExperimentSetupFragment.java
- app/src/main/java/org/fossasia/pslab/fragment/Experiments.java
- app/src/main/java/org/fossasia/pslab/fragment/HomeFragment.java
- app/src/main/java/org/fossasia/pslab/fragment/InstrumentsFragment.java
- app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
- build.gradle
Fixes #1004 
**Changes**: 
- Removed LeakCanary integration
**APK for testing**: [LeakCanary.zip](https://github.com/fossasia/pslab-android/files/2107362/LeakCanary.zip)
> fix: removed leakcanary integration

- app/src/main/java/org/fossasia/pslab/activity/WaveGeneratorActivity.java
Fixes #1097 
**Changes**:
- Added the check for science lab
- added toast if device is not connected
- the wavetype are selected for both waves separately.
**APK for testing**:[app-debug.zip](https://github.com/fossasia/pslab-android/files/2118773/app-debug.zip)
> feat:added check for science lab device and dynamic selection of wavetype

- app/src/main/java/org/fossasia/pslab/activity/WaveGeneratorActivity.java
- app/src/main/java/org/fossasia/pslab/others/WaveGeneratorCommon.java
- app/src/main/res/layout-v21/activity_wave_generator.xml
- app/src/main/res/layout/activity_wave_generator.xml
- app/src/main/res/values/strings.xml
Fixes #1085 
fixes #1073 
**Changes**: 
- Renamed the PWM to Digital Panel
- Removed the Square image button from waveform panel.
- Introduced **Mode** button in the Digital Panel for switching between PWM and Square mode.
-> In PWM mode: all the pins will be active, they will have the same frequency but their phase and 
duty will be different, the wave pins will not work in this mode.
-> In Square mode: only the Sq1 pins will be active, and it can have different frequency and 
duty.
updated - 
[app-debug[2].zip](https://github.com/fossasia/pslab-android/files/2128193/app-debug.2.zip)
> feat: introduced the functionality of square wave

- app/src/main/java/org/fossasia/pslab/activity/LuxMeterActivity.java
- app/src/main/res/layout/activity_lux_main.xml
- app/src/main/res/values/strings.xml
First Step to issue #1088 
**Changes**: 
Added the code for the bottom sheet guide replacing the dialog box guide
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2126687/app-debug.zip)
> Adding bottom sheet guide to lux meter

- app/src/main/java/org/fossasia/pslab/others/ZoomLayout.java
- app/src/main/res/layout/bottom_sheet_custom.xml
Fixes #1079   
**Changes**: Added ZoomLayout class to handle the onPinch zoom for the bottom sheet guides
[zoomBottomSheet.zip](https://github.com/fossasia/pslab-android/files/2125817/zoomBottomSheet.zip)
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2131588/app-debug.zip)
> feat: Added zoom functionality for bottom sheet guides

- app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
Fixes #1139 
**Changes**: Handled the case of a single data point being fetched using if..else statement
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2138586/app-debug.zip)
> fix: Handled crash while only a single point is being fetched in Logic Analyzer

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/fossasia/pslab/activity/MainActivity.java
Fixes #1123 
**Changes**: Made main activity launch mode "singleTask" and override the OnNewIntent method to reuse the current main activity.
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2141105/app-debug.zip)
> fix: resolved multiple creation of main activity

- app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
- app/src/main/res/layout/activity_oscilloscope.xml
- app/src/main/res/layout/bottom_sheet_oscilloscope.xml
- app/src/main/res/values/dimens.xml
Fixes #1087 
**Changes**: 
Removed the existing dialog box guide for the oscilloscope and instead added the bottom sheet guide. 
[oscilloscope_bottom_sheet.zip](https://github.com/fossasia/pslab-android/files/2125324/oscilloscope_bottom_sheet.zip)
containing a demonstration]
> feat: oscilloscope bottom sheet guide

- app/src/main/java/org/fossasia/pslab/fragment/InstrumentsFragment.java
- app/src/main/res/drawable/tile_icon_compass.xml
- app/src/main/res/values/strings.xml
Second part for the issue #1136 
**Changes**: 
New tile icon design for the new compass intrument
[tile_icon_compass.zip](https://github.com/fossasia/pslab-android/files/2143898/tile_icon_compass.zip)
[tile_icon_compass_updated.zip](https://github.com/fossasia/pslab-android/files/2152022/tile_icon_compass_updated.zip)
> feat: new icon for Compass intrument

- app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
Fixes #1160 
**Changes**: Solved the bug in setting mode for Single Channel in Logic Analyzer
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2150486/app-debug.zip)
> fix: Solved the bug in setting mode for Single Channel in Logic Analyzer

- app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
- app/src/main/java/org/fossasia/pslab/communication/analogChannel/AnalogInputSource.java
Fixes #1203 
**Changes**: Doubled the output shown by the oscilloscope to match the exact input voltage
V+
V-
VR+
VR-
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2192528/app-debug.zip)
> Solved bug in voltage measurement in Oscilloscope instrument

- app/src/main/res/layout/bottom_sheet_oscilloscope.xml
Fixes #1175 
**Changes**:Made the oscilloscope guide zoomable
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2155571/app-debug.zip)
> fix: made oscilloscope guide zoomable

- app/src/main/AndroidManifest.xml
- app/src/main/java/org/fossasia/pslab/activity/LuxMeterActivity.java
- app/src/main/java/org/fossasia/pslab/activity/MainActivity.java
- app/src/main/java/org/fossasia/pslab/activity/SettingsActivity.java
- app/src/main/res/drawable/ic_arrow_back_white_24dp.xml
- app/src/main/res/layout/activity_settings.xml
- app/src/main/res/menu/data_log_menu.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/xml/settings_preference_fragment.xml
Fixes #1196 
First steps in #1195 
**Changes**: 
- Created new setting activity
- Implemented setting fragment inside setting activity
- Created setting option in menu for lux meter
- Clicking setting in navigation now opens setting activity
Now setting activity can be opened through any activity by simply using intents.
**To do in further PR**
- Create checkbox option in settings fragment to include the location in the csv file for sensors
setting option in overflow menu
[avi_setting.zip](https://github.com/fossasia/pslab-android/files/2173511/avi_setting.zip)
> fix : implemented setting fragment inside setting activity

- app/src/main/java/org/fossasia/pslab/activity/LuxMeterActivity.java
- app/src/main/java/org/fossasia/pslab/activity/SettingsActivity.java
- app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentData.java
- app/src/main/java/org/fossasia/pslab/fragment/SettingsFragment.java
- app/src/main/java/org/fossasia/pslab/others/GPSLogger.java
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings_preference_fragment.xml
Fixes #1195 
Next step of PR #1197 
**Changes**:
- Added checkbox in setting activity to on/off location in sensors
- Removed onRequestPermissionResult from luxmeter activity and included in setting activity so that any 
further sensor instrument can be easily connected with GPS logger without worrying for location 
permission.
[switch.zip](https://github.com/fossasia/pslab-android/files/2201145/switch.zip)
> feat: added switch in settings fragment to on/off location

- app/src/main/java/org/fossasia/pslab/activity/MainActivity.java
- app/src/main/res/menu/activity_main_drawer.xml
- app/src/main/res/values/strings.xml
Fixes #1231 
**Changes**: 
Added app version in the drawer menu of the app
[app_version.zip](https://github.com/fossasia/pslab-android/files/2213551/app_version.zip)
> Adding app version in the drawer menu

- app/src/main/java/org/fossasia/pslab/activity/LuxMeterActivity.java
- app/src/main/res/values/strings.xml
Fixes #1202 
**Changes**: 
Added check for permission when the save button is clicked, if permission is not given it will prompt the user to give the permission.
[storage.zip](https://github.com/fossasia/pslab-android/files/2209656/storage.zip)
> fix: added permission check for storage in lux meter

- app/src/main/res/layout/activity_multimeter.xml
Fixes #1260 
**Changes**:
Removed hard-coded height of in display-box add added constraints.
[UI_bugs.apk.zip](https://github.com/fossasia/pslab-android/files/2215028/UI_bugs.apk.zip)
> refactor: solved minor bugs in multimeter UI

- app/src/main/java/org/fossasia/pslab/others/CustomScrollView.java
- app/src/main/res/layout/fragment_lux_meter_data.xml
Fixes #1262 
**Changes**: Created custom scroll view with overriden onTouchEvent() which passes the touch event to the parent at the bottom
**Screenshot/s for the changes**: `Not a UI change`
[scroll_btm.zip](https://github.com/fossasia/pslab-android/files/2216038/scroll_btm.zip)
> fix: solved scroll issue in lux meter fragment

- app/src/main/java/org/fossasia/pslab/activity/LuxMeterActivity.java
Fixes #1270 
**Changes**: 
- Added permission check for storage as OSM needs to save map tiles to show map
[mapsfix.apk.zip](https://github.com/fossasia/pslab-android/files/2216280/mapsfix.apk.zip)
> fix: permission for maps

- upload-apk.sh
Fixes #1263 
**Changes**:
- Appetize io has been removed from usage and the reference was still there in travis build scripts. Removed it in this fix
> fix: removed redundant appetize.io calls

- app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
Fixes #1253 
**Changes**: Made a different method to set adapters for `Two Channel Mode` so that no channel is repeated
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2211672/app-debug.zip)
NOTE: Please merge #1252 before merging this PR
> fix: Solved bug in channel selection in Two Channel Mode in Logic Analyzer

- app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentData.java
- app/src/main/res/values/strings.xml
Fixes #1295 
**Changes**: 
- Added a try catch to crash point logged in Google Play crash reports
[luxfix.apk.zip](https://github.com/fossasia/pslab-android/files/2235493/luxfix.apk.zip)
> fix: lux meter crash log from Google Play

- app/src/main/res/values/strings.xml
Fixes #1306 
**Changes**:updated bottomsheet of multimeter
[bottomsheet.apk.zip](https://github.com/fossasia/pslab-android/files/2259807/bottomsheet.apk.zip)
> refactor: updated bottomsheet of multimeter

- app/src/main/java/io/pslab/activity/CompassActivity.java
Fixes #1335 
**Changes**:
Solved the problem of convention in compass
[compass.apk.zip](https://github.com/fossasia/pslab-android/files/2262850/compass.apk.zip)
> Solved issue of convention in compass

- app/src/main/java/io/pslab/activity/AccelerometerActivity.java
- app/src/main/java/io/pslab/activity/LuxMeterActivity.java
- app/src/main/java/io/pslab/adapters/AccelerometerAdapter.java
- app/src/main/java/io/pslab/fragment/LuxMeterFragmentData.java
- app/src/main/java/io/pslab/others/GPSLogger.java
- app/src/main/res/drawable/delete_icon.xml
- app/src/main/res/drawable/pause_icon.xml
- app/src/main/res/drawable/record_icon.xml
- app/src/main/res/layout/activity_accelerometer.xml
- app/src/main/res/layout/activity_accelerometer_main.xml
- app/src/main/res/menu/data_log_menu.xml
- app/src/main/res/values/strings.xml
Fixes #1329 
**Changes**: Added bottom sheet guide for Accelerometer instrument
**Screenshot/s for the changes**:  
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2263908/app-debug.zip)
NOTE: Please merge PRs #1303 and #1320 before merging this PR
> feat: Added bottom sheet guide for Accelerometer instrument

- app/src/main/java/io/pslab/activity/SensorActivity.java
- app/src/main/java/io/pslab/activity/SensorDataLoggerActivity.java
- app/src/main/java/io/pslab/communication/sensors/BMP180.java
- app/src/main/java/io/pslab/communication/sensors/HMC5883L.java
- app/src/main/java/io/pslab/communication/sensors/MPU6050.java
- app/src/main/java/io/pslab/communication/sensors/SHT21.java
- app/src/main/java/io/pslab/communication/sensors/TSL2561.java
- app/src/main/java/io/pslab/fragment/LuxMeterFragmentConfig.java
- app/src/main/java/io/pslab/fragment/LuxMeterFragmentData.java
- app/src/main/java/io/pslab/sensors/SensorADS1115.java
- app/src/main/java/io/pslab/sensors/SensorBMP180.java
- app/src/main/java/io/pslab/sensors/SensorHMC5883L.java
- app/src/main/java/io/pslab/sensors/SensorMLX90614.java
- app/src/main/java/io/pslab/sensors/SensorMPU6050.java
- app/src/main/java/io/pslab/sensors/SensorMPU925X.java
- app/src/main/java/io/pslab/sensors/SensorSHT21.java
- app/src/main/java/io/pslab/sensors/SensorTSL2561.java
Fixes #1283 
**Changes**: 
- Made changes to view UI inside sensors even if PSLab device is not connected.
[sensors.apk.zip](https://github.com/fossasia/pslab-android/files/2268783/sensors.apk.zip)
> fix: sensor views shown without PSLab device

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/pslab/activity/BarometerActivity.java
- app/src/main/java/io/pslab/fragment/InstrumentsFragment.java
- app/src/main/res/values/strings.xml
Fixes #1337 
**Changes**:
Added the alert-box for pressure sensor in barometer and changed the file name from Barometer_activity to BarometerActivity 
[barometer.apk.zip](https://github.com/fossasia/pslab-android/files/2271511/barometer.apk.zip)
> feat: created alert box for barometer and changed the file name

- app/src/main/java/io/pslab/activity/LuxMeterActivity.java
Fixes #1361 
**Changes**: 
fixed the info and position of snack bars
[snack.zip](https://github.com/fossasia/pslab-android/files/2281089/snack.zip)
> fix: snackbar now show proper info 

- app/src/main/java/io/pslab/activity/AccelerometerActivity.java
- app/src/main/java/io/pslab/activity/BarometerActivity.java
- app/src/main/java/io/pslab/activity/CompassActivity.java
- app/src/main/java/io/pslab/activity/LuxMeterActivity.java
- app/src/main/java/io/pslab/activity/MultimeterActivity.java
- app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
- app/src/main/java/io/pslab/activity/PowerSourceActivity.java
- app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java
- app/src/main/java/io/pslab/fragment/LALogicLinesFragment.java
Fixes #1329 
**Changes**: Added code to close the bottom sheet when the window behind it is clicked
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2282890/app-debug.zip)
> Solved issue of active screen while bottom sheet is up

- app/src/main/java/io/pslab/activity/MultimeterActivity.java
- app/src/main/java/io/pslab/communication/ScienceLab.java
Fixes #1376 
**Changes**: 
There was an infinity loop in capacitance measurement, changed it to a finite loop, also handled null capacitance value in MultimeterActivity
[capacitance.apk.zip](https://github.com/fossasia/pslab-android/files/2300242/capacitance.apk.zip)
> fix: solved issue of crashing in capacitance measurement

- app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java
Fixes #1396 
**Changes**:
Added code for canceling dialog box in wave generator before navigating to another instrument.
**Screenshot/s for the changes**: Not a UI change
[dialog_wave.zip](https://github.com/fossasia/pslab-android/files/2433044/dialog_wave.zip)
> Dialog box in wave generator is now closing properly

- app/src/main/res/layout/splash_screen.xml
- app/src/main/res/values/dimens.xml
Fixes #1395
**Changes**: Hard Coded Dimensions removed from the splash screen xml file.
**Screenshot/s for the changes**: NA
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2447585/app-debug.zip)
> fix: Hard Coded dimensions fixed in splash screen

- app/src/main/java/io/pslab/activity/LuxMeterActivity.java
- app/src/main/java/io/pslab/fragment/LuxMeterFragmentData.java
- app/src/main/java/io/pslab/others/GPSLogger.java
- app/src/main/res/values/strings.xml
Fixes #1400 
**Changes**: 
Added if-else in lux meter fragment to check for empty data before storing in the realm database in the form of record.
**Screenshot/s for the changes**:Not a UI change
[emptyfix.zip](https://github.com/fossasia/pslab-android/files/2433551/emptyfix.zip)
> fix: resolved empty data bug in lux meter

- app/src/main/java/io/pslab/activity/AccelerometerActivity.java
- app/src/main/java/io/pslab/activity/MultimeterActivity.java
- app/src/main/res/menu/data_log_menu.xml
- app/src/main/res/menu/multimeter_log_menu.xml
Fixes #1410
**Changes**: Changes the recording button logo on Action bar of Multimeter and Accelerometer Activity same as Lux Meter Activity.
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/2460383/app-debug.apk.zip)
> Changing different recording button logo to one in action bar of two activities.

- app/src/main/java/io/pslab/activity/LogicalAnalyzerActivity.java
- app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
- app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java
Fixes #1386
**Changes**: On devices with horizontal screen implement auto-hiding top bar
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2466400/app-debug.zip)
> added auto hide top bar

- app/src/main/java/io/pslab/activity/LuxMeterActivity.java
- app/src/main/java/io/pslab/fragment/LuxMeterSettingFragment.java
- app/src/main/res/xml/lux_meter_settings.xml
Fixes #1421
**Changes**: Enabled/Permission GPS in LuxMeter by default.
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2528759/app-debug.zip)
> fix: Solved issue of GPS disabled by default

- app/src/main/java/io/pslab/fragment/LuxMeterDataFragment.java
Fixes #1452 
**Changes**: 
- When there were no recorded data as user closes the app quickly, app crashed. It was fixed and a message is displayed
[LuxMeterFix.zip](https://github.com/fossasia/pslab-android/files/2650067/LuxMeterFix.zip)
> fix: crash in Luxmeter when no data is saved

- app/src/main/res/layout/fragment_lux_meter_data.xml
Fixes #1462 
**Changes**: 
- Extended view to use graph in white space
[Lux.apk.zip](https://github.com/fossasia/pslab-android/files/2661269/Lux.apk.zip)
> feat: use of white space under Luxmeter

- app/src/main/java/io/pslab/activity/DataLoggerActivity.java
- app/src/main/res/layout/activity_data_logger.xml
- app/src/main/res/values/strings.xml
Fixes #1447 
**Changes**: 
- Added blank view notifying there is no log if the log list is empty
[DataLogger.apk.zip](https://github.com/fossasia/pslab-android/files/2684204/DataLogger.apk.zip)
> feat: empty datalogger view

- app/src/main/res/layout/pin_description_dialog.xml
Fixes #1495 
**Changes**: Redundant LinearLayout enclosing the Button is removed.
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2694625/app-debug.zip)
> refactor: Remove redundant LinearLayout

- app/src/main/java/io/pslab/activity/PowerSourceActivity.java
Fixes #1461 
**Changes**: 
- Handle number format exception where the crash log of the issue states crashing. 
(Note: This issue is not recreational as user cannot type in any value to happen a number format exception. But I observed, the user device uses a different language and it might have shifted dot with comma `For input string: "-5,00"`? So anyways, this fix catches such exceptions and set to a default value rather than crashing.)
----
> fix: power source crash

- app/src/main/java/io/pslab/fragment/ChannelParametersFragment.java
Fixes #1511 
**Changes**: Removed the onClick calling of CH1 spinner from the initiating method
[oscilloscope_issue.apk.zip](https://github.com/fossasia/pslab-android/files/2732412/oscilloscope_issue.apk.zip)
> fix: Solved the issue of popping up spinner in oscilloscope instrument

- app/src/main/AndroidManifest.xml
Fixes #1533 
**Changes**: Added screen orientation to barometer activity and set it to portrait.   
> Barometer's orientation fixed(#1533)

- app/src/main/res/drawable/tile_icon_accelerometer.xml
- app/src/main/res/drawable/tile_icon_lux_meter.xml
Fixes #1536
**Changes**: Width and height of the drawable were increased.
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2768398/app-debug.zip)
> fix : Blurred tile icon of LuxMeter and Accelerometer

- app/src/main/java/io/pslab/activity/MultimeterActivity.java
Fixes #1550 
**Changes**: assigned the value of "defaultValue" string inside the onCreate() function
[multimeter_bug_fix.zip](https://github.com/fossasia/pslab-android/files/2880257/multimeter_bug_fix.zip)
> Fix #1550 multimeter crash bug fixed

- app/src/main/java/io/pslab/activity/LogicalAnalyzerActivity.java
- app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
- app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java
Fixes #1552 
**Changes**:
I have made a function removeStatusBar() which will be called whenever activity is created or resumed. 
**APK for testing**: [status_bar_bug_fix.zip](https://github.com/fossasia/pslab-android/files/2881516/status_bar_bug_fix.zip)
> Fix #1552 Status Bar removed when activity is resumed

- app/src/main/java/io/pslab/activity/CompassActivity.java
- app/src/main/java/io/pslab/models/CompassData.java
- app/src/main/res/layout/activity_compass_main.xml
- app/src/main/res/menu/activity_compass_help_menu.xml
Fixes #1371 Recording functionality added in compass instrument
**Changes**: added function of record data in CompassActivity and created a new class of compassData
**APK for testing**:[app-debug.zip](https://github.com/fossasia/pslab-android/files/2881122/app-debug.zip)
> feat: recording functionality in compass instrument

- app/src/main/java/io/pslab/activity/LogicalAnalyzerActivity.java
- app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
- app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java
Fixes #1558  
**Changes**: widow full screen flag set in onCreate method
[statusbar_bug.zip](https://github.com/fossasia/pslab-android/files/2884414/statusbar_bug.zip)
> Fix #1558 status bar bug fixed, status bar doesnt reappear on opening spinners

- app/src/main/java/io/pslab/activity/SettingsActivity.java
- app/src/main/java/io/pslab/models/PSLabSensor.java
Fixes #1559  
**Changes**: 
String sent to settingsActivity with intent changed
[configuration_title.zip](https://github.com/fossasia/pslab-android/files/2883749/configuration_title.zip)
> FIx #1559 Lux Meter/Barometer configuration titles fixed

- app/src/main/java/io/pslab/activity/DataLoggerActivity.java
- app/src/main/java/io/pslab/activity/MultimeterActivity.java
- app/src/main/res/menu/multimeter_log_menu.xml
Fixes #1600
**Changes**: show logged data option added to multimeter menu
> Fix #1600 show logged data option added to multimeter menu

- app/src/main/java/io/pslab/activity/LogicalAnalyzerActivity.java
- app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
- app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java
- app/src/main/res/layout/activity_logic_analyzer.xml
- app/src/main/res/layout/activity_oscilloscope.xml
- app/src/main/res/layout/activity_wave_generator.xml
- app/src/main/res/layout/activity_wave_generator_main.xml
Fixes #1599
**Changes**: button to open guide added to Oscilloscope, logic analyzer and wave generator
> Fix # button to open guide added to Oscilloscope, logic analyzer and wave generator

- app/src/main/java/io/pslab/models/PSLabSensor.java
Fixes #1569 #1568
**Changes**: OPen button snackbar takes to data logger activity
> Fix #1568 #1569 recording snackbar "open" button takes to data logger activity

- app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java
- app/src/main/res/layout/activity_wave_generator.xml
Fixes #1553 
**Changes**:
Wave Labels in wave generator are now clickable
[wave_labels.zip](https://github.com/fossasia/pslab-android/files/2881082/wave_labels.zip)
> Fix #1553 Made wave 1/2 labels clickable in Wave Generator

- app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
Fixes #1570 
**Changes**: checking the size of log data, upon zero making the "no log data" message visible
> "no log data" message visible upon deleting everything from logged data

- app/src/main/res/values/strings.xml
Fixes #1656 
**Changes**: Changed wrong message displayed on long press of menu in compass instrument
**APK for testing**: [app-debug.zip](https://github.com/fossasia/pslab-android/files/3017797/app-debug.zip)
> fix: wrong information displayed in Compass instrument

- app/src/main/java/io/pslab/activity/AccelerometerActivity.java
- app/src/main/res/menu/data_log_menu.xml
Fixes #1647 
**Changes**: Added Show guide option to accelerometer
> Fix #1647 Show guide option added to Accelerometer

- app/src/main/res/values/strings.xml
- app/src/main/res/xml/baro_meter_settings.xml
- app/src/main/res/xml/lux_meter_settings.xml
Fixes #1574 
**Changes**:Changes made in xml files lux_meter_settings and baro_meter_settings
**Screenshot/s for the changes**:Not Appicable
[app-debug (1).zip](https://github.com/fossasia/pslab-android/files/2922508/app-debug.1.zip)
> Removed Hard coded values from multiple files

- app/src/main/res/layout/activity_compass.xml
Fixes #1639 
**Changes**: Increased margin bottom of layout to slide up the guide.
[app-debug (2).zip](https://github.com/fossasia/pslab-android/files/3026444/app-debug.2.zip)
> Compass slide up guide fixed

- app/src/main/java/io/pslab/fragment/LuxMeterDataFragment.java
Fixes #1638 
**Changes**:All the readings have been to rounded off to 2 decimal place.
**APK for testing**: [app-debug.zip](https://github.com/fossasia/pslab-android/files/3055666/app-debug.zip)
> Decimals in Luxmeter made consistent

- app/src/main/java/io/pslab/activity/MultimeterActivity.java
- app/src/main/java/io/pslab/fragment/BaroMeterSettingsFragment.java
- app/src/main/java/io/pslab/fragment/LuxMeterSettingFragment.java
Fixes #1614
**Changes**: Replaced editor.commit with editor.apply
> Fix #1614 shared preference editor.commit replaced with better option editor.apply

- app/src/main/res/layout/activity_compass.xml
- app/src/main/res/layout/activity_logic_analyzer.xml
Fixes #1620
**Changes**: Using string resources for multimeter and Logic Analyzer appbar title
[Uploading app-debug.zip…]()
> App Bar titles fixed using string resources

- app/src/main/java/io/pslab/fragment/BaroMeterDataFragment.java
- app/src/main/java/io/pslab/models/PSLabSensor.java
Fixes #1633 
**Changes**: All the readings have been to rounded off to 2 decimal place.
**APK for testing**: [app-debug.zip](https://github.com/fossasia/pslab-android/files/3055944/app-debug.zip)
> Decimals in Barometer made consistent

- app/src/main/res/layout/activity_accelerometer.xml
Fixes #1610 
**Changes**: removed bottom margin
**before:**
**after**:
> Fix #1610 additional gray view removed from the bottom of accelerometer layout

- app/src/main/java/io/pslab/activity/MultimeterActivity.java
- app/src/main/res/menu/multimeter_log_menu.xml
Fixes #1657 
**Changes**: Every instrument except multimeter had show guide option, so i have added that option to multimeter menu
> Fix #1657 show guide option added

- app/src/main/java/io/pslab/fragment/BaroMeterDataFragment.java
- app/src/main/java/io/pslab/fragment/LuxMeterDataFragment.java
- app/src/main/res/layout/fragment_barometer_data.xml
- app/src/main/res/layout/fragment_lux_meter_data.xml
Fixes #1674 
**Changes**: When save graph button is clicked on the data logger activity, if the log file alrady exist in the local storage then only the .jpg image of current graph is stored in the local storage, if user has deleted the log from local storage then the log file created and .jpg file is stored. 
So even if user deletes the log from local storage it can again be generated using the app, which was not possible earlier.
This feature is currently added to Lux meter and Baro meter
[save_graph.apk.zip](https://github.com/fossasia/pslab-android/files/3142153/save_graph.apk.zip)
@cweitat  @CloudyPadmal  @abhinavraj23  kindly review.
> Fix #1674 save graph function implemeted

- app/src/main/java/io/pslab/activity/DataLoggerActivity.java
- app/src/main/res/layout/import_log_device_type_alert_layout.xml
- app/src/main/res/menu/activity_data_logger_menu.xml
- app/src/main/res/values/strings.xml
Fixes #1690 
**Changes**: 
I have added an option in data logger activity where user can import the log stored as CSV on the SD card for the instrument selected by the user. 
**Currently I have implemented this feature for Barometer and Lux meter. Once the mentors approves these changes I will add the other instruments as well**
Following are the steps to import log in the application
**step 1**
Create a CSV file on the SD card or local storage with proper headers and required fields as per selected instrument. (Following is a CSV for Luxmeter)
**step 2**
Open DataLogger Activity, go to import log menu and in the alert dialogg select appropriate device, once a device is selected user can browse through the phone storage and select a file to be imported. …
> WIP: Playback data from SD card feature added

- app/src/main/java/io/pslab/activity/DataLoggerActivity.java
Fixes #1645 
**Changes**: Now opening log activity from barometer activity will only show barometer logs.
@abhinavraj23  @cweitat  @CloudyPadmal  Kindly review
> show logged data in barometer activty shows only barometer data

- app/src/main/java/io/pslab/activity/CompassActivity.java
- app/src/main/res/values/strings.xml
Fixes #1634 
**Changes**: A toast message appears if the device dos not contain magnetic sensor
[app-debug (3).zip](https://github.com/fossasia/pslab-android/files/3005130/app-debug.3.zip)
> Added Toast message when sensor not present in Compass

- app/src/main/java/io/pslab/activity/SettingsActivity.java
- app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
- app/src/main/java/io/pslab/fragment/AccelerometerDataFragment.java
- app/src/main/java/io/pslab/fragment/AccelerometerSettingsFragment.java
- app/src/main/java/io/pslab/models/PSLabSensor.java
- app/src/main/res/layout/fragment_accelerometer_data.xml
- app/src/main/res/menu/data_log_menu.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/accelerometer_settings.xml
Fixes #1704 
**Changes**: The configurations of accelerometer made consistent with baro,lux and gyroscope
[app-debug.zip](https://github.com/fossasia/pslab-android/files/3183674/app-debug.zip)
> Accelerometer Configurations made consistent with other Instruments

- app/src/main/java/io/pslab/activity/ThermometerActivity.java
- app/src/main/java/io/pslab/fragment/ThermometerDataFragment.java
- app/src/main/java/io/pslab/models/PSLabSensor.java
- app/src/main/res/layout/activity_thermometer.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Fixes #1750 #1752 
**Changes**: Added backend code for thermometer . 
[app-debug.zip](https://github.com/fossasia/pslab-android/files/3237006/app-debug.zip)
> Thermometer working added and crash fixed

- app/src/main/java/io/pslab/activity/MultimeterActivity.java
- app/src/main/res/menu/multimeter_log_menu.xml
Fixes #1759 
**Changes**: Bug fixed, pause button replaced with stop button, csv file created on clicking stop button.
[multimeter_log.zip](https://github.com/fossasia/pslab-android/files/3241434/multimeter_log.zip)
@CloudyPadmal  kindly review
> Fix #1759 multimeter record bug fixed

- app/src/main/java/io/pslab/activity/SettingsActivity.java
- app/src/main/java/io/pslab/activity/ThermometerActivity.java
- app/src/main/java/io/pslab/fragment/ThermometerDataFragment.java
- app/src/main/java/io/pslab/fragment/ThermometerSettingsFragment.java
- app/src/main/java/io/pslab/models/PSLabSensor.java
- app/src/main/res/layout/activity_thermometer.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/thermometer_settings.xml
Fixes #1756 
**Changes**: Settings menu with the option to change units.
[app-debug.zip](https://github.com/fossasia/pslab-android/files/3243490/app-debug.zip)
> Thermometer settings added

- app/src/main/java/io/pslab/activity/DataLoggerActivity.java
- app/src/main/java/io/pslab/activity/RoboticArmActivity.java
- app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
- app/src/main/java/io/pslab/interfaces/sensorloggers/ServoRecordables.java
- app/src/main/java/io/pslab/models/PSLabSensor.java
- app/src/main/java/io/pslab/models/ServoData.java
- app/src/main/java/io/pslab/others/LocalDataLog.java
- app/src/main/res/layout/import_log_device_type_alert_layout.xml
Fixes #1772 
**Changes**:
User can now load already saved timelines for robotic arm controller
[servo_load_timeline.zip](https://github.com/fossasia/pslab-android/files/3258351/servo_load_timeline.zip)
> Fix #1772 Import log working fine for robotic arm controller

- app/src/main/java/io/pslab/activity/DataLoggerActivity.java
Fixes #1736 
**Changes**: No crash when back button is pressed of device when data is deleted
[app-debug.zip](https://github.com/fossasia/pslab-android/files/3266635/app-debug.zip)
> No crash on back press

- app/src/main/java/io/pslab/fragment/GyroscopeDataFragment.java
- app/src/main/res/values/strings.xml
Fixes #1723
**Changes**: Graphs removed and a visual message to user when no data fetched
[gyro.zip](https://github.com/fossasia/pslab-android/files/3273178/gyro.zip)
> Visual message when no data fetched in gyroscope

- app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
Fixes #1798 
**Changes**: User can now view the fourier transform output of 2 channels simultaneously
[fft.zip](https://github.com/fossasia/pslab-android/files/3294079/fft.zip)
@CloudyPadmal  @cweitat  have a look at this. Though this might give weird output since #1797 is yet to be merged
> Fix #1798 fft working fine for 2 channels simultaneously

- app/src/main/res/layout/activity_robotic_arm.xml
- app/src/main/res/values/dimens.xml
Fixes #1751 
**Changes**: The play,pause,record button moved up as mentioned in the issue.
[ui.zip](https://github.com/fossasia/pslab-android/files/3295434/ui.zip)
> UI of robotic arm improved

- app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
Fixes #874 
**Changes**: User can now see output of Ch1 or Ch2 or Ch3 simultaneously with audio output in oscilloscope 
[osc_audio.zip](https://github.com/fossasia/pslab-android/files/3301357/osc_audio.zip)
@mariobehling  @CloudyPadmal  @cweitat  have a look at this, For now two channels will simultaneously  work completely fine, for simultaneous 3 and 4 channels i will file new issues and will fix them mostly in next milestone.
> Fix #874 audio input working fine simultaneously with other channel

- app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
- app/src/main/java/io/pslab/fragment/OscilloscopePlaybackFragment.java
Fixes #1809 
**Changes**: User can now see Fourier transform of the saved log while playing it back
[playback_fft.zip](https://github.com/fossasia/pslab-android/files/3310233/playback_fft.zip)
@mariobehling  @CloudyPadmal  @cweitat  have a look :)
> Fix #1809 fourier transform can be seen while playing back saved log

- app/src/main/java/io/pslab/activity/RoboticArmActivity.java
- app/src/main/res/layout/activity_robotic_arm.xml
- app/src/main/res/layout/bottom_sheet_robotic_arm.xml
- app/src/main/res/values/strings.xml
Fixes #1803 
**Changes**: Added bottomsheet guide for robotic arm.
[guide.zip](https://github.com/fossasia/pslab-android/files/3306450/guide.zip)
> Guide for robotic arm

- app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
Fixes #1816 Fixes #1806
**Changes**: Single Capture class created to handle all channels
[capture_task_refactor.zip](https://github.com/fossasia/pslab-android/files/3316811/capture_task_refactor.zip)
@CloudyPadmal  @mariobehling  have a look at this. The code looks a lot cleaner now. Will do similar for fft and Audiobuffer tasks in subsequent PRs.
> Fix #1815 Single Capture class created to handle all channels

- app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
- app/src/main/java/io/pslab/fragment/ChannelParametersFragment.java
Fixes #1821 
**Changes**: Everything is now handled through single Capture Class
[refactor.zip](https://github.com/fossasia/pslab-android/files/3317865/refactor.zip)
@CloudyPadmal  @mariobehling  @cweitat  have a look. I have removed all different classes for AudioBuffer and Fourier Transforms and have created single class. Currently Fourier Transform for Built In audio input is not working, i will add that in the PR to fix #1817
> Fix #1821 converted audiobuffer, fft and channel capture classes to single capture class

- app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
Fixes #1817 
**Changes**: Fourier Transform added for built in mic
[fft_mic.zip](https://github.com/fossasia/pslab-android/files/3326458/fft_mic.zip)
@CloudyPadmal @mariobehling @ho-dor @cweitat have a look
> Fix #1817 fourier transform for built in mic input working fine

- app/src/main/java/io/pslab/fragment/GyroscopeDataFragment.java
- app/src/main/java/io/pslab/fragment/GyroscopeSettingsFragment.java
- app/src/main/res/values/strings.xml
Fixes #1815 
**Changes**:bug fixed in gyroscope
[gyro.zip](https://github.com/fossasia/pslab-android/files/3326684/gyro.zip)
> Fix 1815 bug fixes in gyroscope

- app/src/main/java/io/pslab/activity/DataLoggerActivity.java
Fixes #1858 
**Changes**: Inifinite loop created on back press removed.
[back_press.zip](https://github.com/fossasia/pslab-android/files/3385072/back_press.zip)
> Back press bug removed

- app/src/main/res/xml/gyro_scope_settings.xml
Fixes #1872 
**Changes**: Crash fixed by correcting key_id of preferences
[gyro.zip](https://github.com/fossasia/pslab-android/files/3388783/gyro.zip)
> Gyroscope settings crash fixed

- app/src/main/java/io/pslab/models/PSLabSensor.java
Fixes #1879
**Changes**: Space added between instrument name and "Configurations"
[config_menu.zip](https://github.com/fossasia/pslab-android/files/3438904/config_menu.zip)
> config menu separated

- app/src/main/java/io/pslab/activity/DataLoggerActivity.java
- app/src/main/java/io/pslab/activity/LogicalAnalyzerActivity.java
- app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
- app/src/main/java/io/pslab/fragment/LALogicLinesFragment.java
- app/src/main/java/io/pslab/interfaces/sensorloggers/LogicAnalyzerRecordables.java
- app/src/main/java/io/pslab/models/LogicAnalyzerData.java
- app/src/main/java/io/pslab/models/PSLabSensor.java
- app/src/main/java/io/pslab/others/LocalDataLog.java
- app/src/main/res/layout-land/logic_analyzer_logic_lines.xml
Fixes #1909 
**Changes**: Logging for Logic Analyzer 
[la_logging.zip](https://github.com/fossasia/pslab-android/files/3465042/la_logging.zip)
@CloudyPadmal  since unlike oscilloscope waves in LA are not continuously moving, I think there is no need to add continuous logging here .. it will add unnecessary complexity and redundant data.
> logic analyzer logging/ playback added

- app/build.gradle
- app/src/main/java/io/pslab/activity/MainActivity.java
- app/src/main/java/io/pslab/fragment/ESPFragment.java
- app/src/main/res/drawable/ic_bluetooth.xml
- app/src/main/res/drawable/ic_wifi.xml
- app/src/main/res/layout/bluetooth_wifi_dialog_layout.xml
- app/src/main/res/layout/fragment_esp.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- build.gradle
Fixes #1891 
**Changes**: User can connect to pslab using wifi
[esp.zip](https://github.com/fossasia/pslab-android/files/3472336/esp.zip)
@CloudyPadmal  the interface seems nice, Once the ESP server is implemented we can add further communication protocols.
> interface for ESP wifi module added

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/pslab/activity/GasSensorActivity.java
- app/src/main/java/io/pslab/fragment/GasSensorDataFragment.java
- app/src/main/java/io/pslab/fragment/InstrumentsFragment.java
- app/src/main/res/layout/fragment_gas_sensor.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Fixes #1912 
**Changes**:Support for MQ135 added
Steps : 
1. Connect V of MQ135 to VDD 
2. Connect GND of MQ135 to GND
3. Connect AO of MQ135 to CH1
https://drive.google.com/file/d/1-KxOaqE_Y5EYquMkebYpBOEc0d7GAdLS/view?usp=sharing
[mq135.zip](https://github.com/fossasia/pslab-android/files/3473731/mq135.zip)
@CloudyPadmal  @mariobehling @cweitat have a look. For now i haven't added the logging, because that would have made this PR too huge. I have also asked @ho-dor if he can help me with svg logo for the gas sensor. The basic functionality is working fine as can be seen in the video
> MQ135 Gas sensor added

- app/src/main/java/io/pslab/activity/DataLoggerActivity.java
- app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
- app/src/main/java/io/pslab/fragment/BaroMeterDataFragment.java
- app/src/main/java/io/pslab/models/BaroData.java
- app/src/main/res/layout/fragment_barometer_data.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
Fixes #1598 
**Changes**: feature to see altitude from pressure added in Barometer
[altitude.zip](https://github.com/fossasia/pslab-android/files/3498450/altitude.zip)
> feat: feature to see altitude from pressure added in Barometer

- app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
- app/src/main/java/io/pslab/activity/RoboticArmActivity.java
- app/src/main/java/io/pslab/fragment/OscilloscopePlaybackFragment.java
- app/src/main/res/layout/activity_oscilloscope.xml
- app/src/main/res/layout/activity_robotic_arm.xml
- app/src/main/res/layout/fragment_channel_parameters.xml
- app/src/main/res/layout/fragment_oscilloscope_playback.xml
- app/src/main/res/menu/activity_landscape_menu.xml
- app/src/main/res/menu/robotic_arm_menu.xml
- app/src/main/res/values/dimens.xml
Fixes #1929 #1930
**Changes**: Actionbar added to Oscilloscope and Robotic Arm
**Oscilloscope main layout**
**Oscilloscope Playback**
**Robotic Arm**
[actionbar.zip](https://github.com/fossasia/pslab-android/files/3510711/actionbar.zip)
@CloudyPadmal  @mariobehling  I will add action bar to Logic Analyzer in separate PR... Since the implementation of LA is quite different (inflating a fragment in activity) i think I will have to come up with some hack or change the implementation. For now action bar works fine in oscilloscope and Robotic Arm. Thanks
> fix: Actionbar added to Oscilloscope and Robotic Arm

- app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java
Fixes #1928
**Changes**: Wave generator active even without pressing view button
[wave.tar.gz](https://github.com/fossasia/pslab-android/files/3513445/wave.tar.gz)
> feat: Wave generator active even without pressing view button

- app/src/main/java/io/pslab/communication/HttpAsyncTask.java
- app/src/main/java/io/pslab/communication/HttpHandler.java
- app/src/main/java/io/pslab/communication/PacketHandler.java
- app/src/main/java/io/pslab/fragment/ESPFragment.java
- app/src/main/java/io/pslab/interfaces/HttpCallback.java
- app/src/main/java/io/pslab/others/ScienceLabCommon.java
Fixes #1926 
**Changes**: added http handler class 
N/A
N/A
> feat: add Httphandler class

- app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java
- app/src/main/res/drawable/btn_back_rounded.xml
- app/src/main/res/drawable/btn_back_rounded_light.xml
- app/src/main/res/drawable/ic_arrow_left_24dp.xml
- app/src/main/res/drawable/ic_arrow_right_24dp.xml
- app/src/main/res/layout/wave_generator_analog_mode_layout.xml
- app/src/main/res/layout/wave_generator_digital_mode_layout.xml
- app/src/main/res/layout/wave_generator_main_controls.xml
- app/src/main/res/layout/wave_generator_seekbar.xml
- app/src/main/res/layout/wave_generator_wave_controls.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
Fixes #1956 
**Changes**:
1. Added separate buttons for digital/analog mode
2. Remove wave titles as mentioned in the issue
3. Added left/right arrows instead of up/down arrows for seekbar
4. Added switching effect to freq/phase/duty buttons
5. Added separate buttons for sin and triangular wave
6. Removed decimals from values of freq/phase/duty
7. removed toast when changing to digital mode
8. Made status bar visible
[wave.zip](https://github.com/fossasia/pslab-android/files/3535029/wave.zip)
> fix: Wave generator UI changes

- app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java
- app/src/main/res/values/strings.xml
Fixes #1938
**Changes**: wave generator preview working fine
**Analog Mode**
**Digital Mode**
[wave_gen_preview.zip](https://github.com/fossasia/pslab-android/files/3551415/wave_gen_preview.zip)
@CloudyPadmal @mariobehling  I have added the preview feature to the wave generator UI. It is really looking good. Please review.  I have made a getSamplePoints() function which I will use again to produce sound for different waves for the issue #1937
> feat: Add wave generator preview

- app/src/main/java/io/pslab/activity/RoboticArmActivity.java
- app/src/main/res/values/strings.xml
Fixes #1966 
**Changes**: degree and second symbols added to robotic arm timeline
[robotic.zip](https://github.com/fossasia/pslab-android/files/3555144/robotic.zip)
> fix: degree and second symbols added to robotic arm timeline

- app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java
- app/src/main/res/values/strings.xml
Fixes #1967 
**Changes**: [deg was written as text changed to its symbol (\u00b0) ]
[app-fdroid-debug.apk.zip](https://github.com/fossasia/pslab-android/files/3563800/app-fdroid-debug.apk.zip)
> fix: deg text to symbol.

- app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java
- app/src/main/res/layout/wave_generator_main_controls.xml
- app/src/main/res/values/strings.xml
Fixes #1937 #1165 
**Changes**: Added feature to produce sound using phone speaker
https://drive.google.com/file/d/1MRU9cBSepwstXNkJvfHau9L7rGFDxriv/view?usp=sharing
[wave_gen_sound.zip](https://github.com/fossasia/pslab-android/files/3563479/wave_gen_sound.zip)
@CloudyPadmal  @mariobehling this feature is complete for now. As @mariobehling mentioned in last meet we can build it up from here to allow user to play/view multiple waves simultaneously. Please review.
> feat: Use phone speaker to produce sound

- app/src/main/java/io/pslab/fragment/GasSensorDataFragment.java
Fixes #1979 
**Changes**: Toast message made consistent with all other instruments.
[toast.zip](https://github.com/fossasia/pslab-android/files/3678516/toast.zip)
> Toast message in gas sensor made consistent with all instruments

- app/src/main/java/io/pslab/CheckBoxGetter.java
- app/src/main/java/io/pslab/activity/CreateConfigActivity.java
- app/src/main/java/io/pslab/adapters/CheckBoxAdapter.java
- app/src/main/res/layout/activity_create_config.xml
- app/src/main/res/layout/item_checkbox.xml
- app/src/main/res/values/dimens.xml
Fixes #1973
**Changes**: The Config Activity UI was unordered, so changes were made in the config layout by adding a number of views.
<image src = "https://user-images.githubusercontent.com/38812752/65950873-8fab4080-e45c-11e9-879e-fbd7b06c0d89.jpeg" width=250>
<image src ="https://user-images.githubusercontent.com/38812752/65950876-90dc6d80-e45c-11e9-8c99-0f199cd938b9.jpeg" width=250>
[app-fdroid-debug.zip](https://github.com/fossasia/pslab-android/files/3684930/app-fdroid-debug.zip)
> Improved UI Of Config Activity

- app/src/main/res/layout/activity_create_config.xml
Fix: #2005 Letters of the Spinner are corrupted
**Changes**:  Letters of the Spinner won't disappear even if the screen size of mobile is small or the font size is made to maximum.
> Fix: #2005 Letters of the Spinner are corrupted

- app/src/main/java/io/pslab/InputMinMaxFilter.java
- app/src/main/java/io/pslab/activity/RoboticArmActivity.java
Fixes #2071 
Added Input Limit
**Changes**: Added new MinMaxFilter Class
**Screenshots for the changes**: 
> feat: Added input limit

- app/src/main/java/io/pslab/activity/PowerSourceActivity.java
- app/src/main/java/io/pslab/models/PSLabSensor.java
…fter recording, in some sensors, opens the datasets of all the sensors rather than that of the currently opened sensor.
Fixes #2027 
**Changes**:
Made change to `PSLabSensor` and `PowerSourceActivity` to fix issue #2027 
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/13999905/70848992-0d4ced00-1e9f-11ea-90d3-2107cd2f9d50.gif" /></td>
<td><img src="https://user-images.githubusercontent.com/13999905/70848993-0d4ced00-1e9f-11ea-96f3-c9ea778478e6.gif" /></td>
<td><img src="https://user-images.githubusercontent.com/13999905/70848994-0de58380-1e9f-11ea-9c00-00027b1faf8f.gif" /></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/13999905/70849071-ad0a7b00-1e9f-11ea-9751-4a187befc29e.gif" /></td>
<td><img …
> fix: Snackbar sensor view

- app/src/main/res/layout/activity_create_config.xml
Fix First steps for issues #2020: Alignment of "Time Interval" dropdown
**Changes**: Made the Alignment of Time Interval and instrument dropdown properly
**Screenshot/s for the changes**
> fix #2020: Alignment of "Time Interval" dropdown

- app/src/main/java/io/pslab/activity/MainActivity.java
- app/src/main/res/menu/activity_main_drawer.xml
- app/src/main/res/values/strings.xml
**fix for** https://github.com/fossasia/pslab-android/issues/2035
**Changes**: I added button in navbar with link to google play
[app-fdroid-debug.zip](https://github.com/fossasia/pslab-android/files/3988491/app-fdroid-debug.zip)
> add rate button

- app/src/main/res/values-si/string.xml
Fixes #2033 
**Changes**: 
Add Sinhala translation to string.xml.
[app-fdroid-debug.apk.zip](https://github.com/fossasia/pslab-android/files/4091381/app-fdroid-debug.apk.zip)
> Add Sinhala (Sri Lanka) Locale Support

- app/src/main/res/layout/application_list_item.xml
Fixes #2086: Add Ripple effect for click on Card on Dashborad
**Changes**: Previously there was no effect when cards on the Dashboard were clicked. Now ripple effect occurs when card is clicked
> feat #2086: Add Ripple effect on Card in Dashboard

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/pslab/activity/DataLoggerActivity.java
- app/src/main/java/io/pslab/activity/SettingsActivity.java
- app/src/main/java/io/pslab/activity/SoundMeterActivity.java
- app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
- app/src/main/java/io/pslab/fragment/InstrumentsFragment.java
- app/src/main/java/io/pslab/fragment/SoundMeterDataFragment.java
- app/src/main/java/io/pslab/fragment/SoundmeterSettingsFragment.java
- app/src/main/java/io/pslab/interfaces/sensorloggers/SoundMeterRecordables.java
- app/src/main/java/io/pslab/models/PSLabSensor.java
- app/src/main/java/io/pslab/models/SoundData.java
- app/src/main/java/io/pslab/others/LocalDataLog.java
- app/src/main/res/layout/fragment_sound_meter_data.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/xml/sound_meter_settings.xml
…sound meter
First steps for issues #2024 
**Changes**:
Implemented the basic functionality of the sound meter. I am having some issues with smooth transition in the graph of the sound and also with the proper calibration of the sound meter. 
**Checklist**:
[firststeps#issue2024.zip](https://github.com/fossasia/pslab-android/files/4010797/firststeps.issue2024.zip)
>  First steps for issue #2024 - implemented the basic functionality of sound meter

- app/src/main/java/io/pslab/fragment/SoundMeterDataFragment.java
**Fixes**: Merging https://github.com/fossasia/pslab-android/commit/ab3a44e5fcb1faf612a8b59163f315412af39ead and https://github.com/fossasia/pslab-android/commit/e4d63225a76b652c610c9c0d275f1b35bee97cb3 cause the development branch to be in a state where a newly merged class uses a method of the CSV logger which does not exist anymore. Hence the build fails: https://travis-ci.org/fossasia/pslab-android/builds/646098874 
**Changes**: The new Activity uses the new method of the CSV logger now.
**Checklist**:
**APK for testing**: [app-fdroid-debug.zip](https://github.com/fossasia/pslab-android/files/4156250/app-fdroid-debug.zip)
> Fix failing build due to inconsistent development branch

- app/src/main/java/io/pslab/activity/CreateConfigActivity.java
Fixes #2008
**Changes**: Use join method of Apache StringUtils instead of the join method of the Android String class. The join method was added to the String class of Android in API level 26, but the minimum API level of the app is 23.
**Checklist**:
**APK for testing**: [app-fdroid-debug.zip](https://github.com/fossasia/pslab-android/files/4155409/app-fdroid-debug.zip)
> Fixes #2008 Fixes crash which occurred in Create Config File

- app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
Fixes #2032
**Changes**: Use join method of Apache StringUtils instead of the join method of the Android String class. The join method was added to the String class of Android in API level 26, but the minimum API level of the app is 23.
**Checklist**:
**APK for testing**: [app-fdroid-debug.zip](https://github.com/fossasia/pslab-android/files/4155262/app-fdroid-debug.zip)
> Fixes #2032 Fixes crash which occurred in the oscilloscope

- app/src/main/res/layout/logger_data_item.xml
Fixes #2088 Effect on click event on logged data item 
**Changes**:
Added Ripple effect on click for logged data item.
Also added ripple effect on click for map and delete icon on logged data item.
> fix: #2088 Effect on click event for logged data item

- app/src/main/java/io/pslab/activity/SoundMeterActivity.java
- app/src/main/java/io/pslab/fragment/SoundMeterDataFragment.java
- app/src/main/java/io/pslab/models/PSLabSensor.java
- app/src/main/java/io/pslab/models/SoundData.java
- app/src/main/res/values/strings.xml
Fixes #2024 Completed the implementation of Soundmeter
**Changes**: Implemented the feature to record the sound level data, play/pause recorded data and added the plot of real time sound level data on the chart. 
**Checklist**:
[fix#2024.zip](https://github.com/fossasia/pslab-android/files/4220557/fix.2024.zip)
> Fixes issue #2024 - Implemented Soundmeter

- app/src/main/java/io/pslab/fragment/AccelerometerDataFragment.java
- app/src/main/java/io/pslab/fragment/BaroMeterDataFragment.java
- app/src/main/java/io/pslab/fragment/CompassDataFragment.java
- app/src/main/java/io/pslab/fragment/DustSensorDataFragment.java
- app/src/main/java/io/pslab/fragment/GasSensorDataFragment.java
- app/src/main/java/io/pslab/fragment/GyroscopeDataFragment.java
- app/src/main/java/io/pslab/fragment/LuxMeterDataFragment.java
- app/src/main/java/io/pslab/fragment/SoundMeterDataFragment.java
- app/src/main/java/io/pslab/fragment/ThermometerDataFragment.java
- app/src/main/java/io/pslab/interfaces/OperationCallback.java
- app/src/main/java/io/pslab/models/PSLabSensor.java
Fixes #2108
**Changes**: PSLabSensorActivity will interact with OperationCallback for operation not any specific fragments by doing this we can eliminate coupling & reduce boilerplate code.
> Fixes: PSLabSensor Activity decoupled from fragments

- README.md
**Changes**: Updated Documentation of README.md
> Updated Documentation of README.md

- app/src/main/java/io/pslab/fragment/GasSensorDataFragment.java
Fixes #1984
**Changes**: 
Entry would be created for case when device is not created to Gas sensor.
**Video for the change**: https://github.com/VIKAS9899/LogRepo/raw/master/Upload/2020_05_17_14_42_40.mp4
**APK for testing**: https://github.com/VIKAS9899/LogRepo/raw/master/Upload/pslab_1984.apk
> Fix: Logged data not shown for Gas Sensor.

- app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
Fixes #2092 
**Changes**: 
The sensor Type in Switch has to be changed from Acclerometer_Configuration to Accelerometer
[Video Link](https://drive.google.com/file/d/1Ysuy25OlaGkDzgZTe8V9arreokCIuvMt/view?usp=sharing)
[Map_Icon.zip](https://github.com/fossasia/pslab-android/files/5313193/Map_Icon.zip)
> Fixed Map Icon click in Accelerometer Logs

- app/src/main/res/layout/activity_create_config.xml
- app/src/main/res/layout/item_checkbox.xml
- app/src/main/res/values/dimens.xml
* Add weight to devide linear layout horizontal and vertical 
* Add font size of textView 
* Fix margin checkBox Card
> fix generate config file layout and modify item checkbox margin.

- app/src/main/AndroidManifest.xml
- app/src/main/java/io/pslab/activity/MultimeterActivity.java
- app/src/main/java/io/pslab/activity/PowerSourceActivity.java
- app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java
- app/src/main/res/layout-land/splash_screen.xml
- app/src/main/res/layout-sw600dp/activity_multimeter.xml
- app/src/main/res/layout-sw600dp/activity_power_source.xml
- app/src/main/res/layout-sw600dp/activity_wave_generator.xml
- app/src/main/res/values/dimens.xml
Fixes #2119 #2118 
**Changes**: Added Tablet layout for multimeter , unlocked landscape mode for some activities and fixed landscape mode of Splash Screen
Had to add some values in `dimens.xml` as Tablet layout need more space than normal one.
**Checklist**:
**APK for Testing**:
[tablet_layout-and-landscape_splash_screen.zip](https://github.com/fossasia/pslab-android/files/5348434/tablet_layout-and-landscape_splash_screen.zip)
[Made_changes asked.zip](https://github.com/fossasia/pslab-android/files/5348435/Made_changes.asked.zip)
> Fixes #2119 #2118 

- app/src/main/java/io/pslab/fragment/ThermometerDataFragment.java
- app/src/main/res/values/colors.xml
Fixes #[#2136 ]
**Changes**: [Added a else statement in line 491 in ThermometerDataFragment.java and set the color to "#ff48cce9"]
**Screenshot/s for the changes**: [Add screenshot/s of the layout where you made changes or a `*.gif` containing a demonstration
]
I have also referred the original repository of anastr/SpeedView(https://github.com/anastr/SpeedView) of PointerSpeedometer.
- [ x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [x ] I have reformatted code in every file included in this PR …
> added a else statement to revert the color

- app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java
- app/src/main/java/io/pslab/communication/CommandsProto.java
- app/src/main/java/io/pslab/communication/ScienceLab.java
- app/src/main/java/io/pslab/communication/analogChannel/AnalogConstants.java
- app/src/main/java/io/pslab/communication/digitalChannel/DigitalChannel.java
- app/src/main/java/io/pslab/fragment/ChannelParametersFragment.java
- app/src/main/java/io/pslab/fragment/ControlFragmentAdvanced.java
- app/src/main/java/io/pslab/fragment/ControlFragmentRead.java
- app/src/main/java/io/pslab/fragment/LALogicLinesFragment.java
- app/src/main/res/values-ar/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pol/string.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values-si/string.xml
- app/src/main/res/values/strings.xml
Changed all instances of
ID1/2/3/4 -> LA1/2/3/4
SEN -> RES
AN8 -> VOL
CNTR -> FRQ
W1/2 -> SI1/2
> Update pin names

- app/src/main/res/layout-xhdpi/activity_multimeter.xml
- app/src/main/res/values-xhdpi/dimens.xml
- app/src/main/res/values/dimens.xml
**In 5.5-inch mobile multimeter look like this**
**After fix #2139 it looks like this**
[app-fdroid-debug.zip](https://github.com/fossasia/pslab-android/files/5396230/app-fdroid-debug.zip)
> fix multimeter layout issue,#2139

- app/src/main/java/io/pslab/fragment/HomeFragment.java
Fixes #[NullPointerException in HomeFragment because of wvProgressBar]
**Changes**: [HomeFragment.java
Log:
```
2021-01-04 17:00:02.758 12294-12294/io.pslab E/AndroidRuntime: FATAL EXCEPTION: main
Process: io.pslab, PID: 12294
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ProgressBar.setVisibility(int)' on a null object reference
at io.pslab.fragment.HomeFragment$1$1.onPageFinished(HomeFragment.java:123)
at fp.b(chromium-Monochrome.aab-stable-424019823:2)
at Vs0.handleMessage(chromium-Monochrome.aab-stable-424019823:66)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:201)
at android.app.ActivityThread.main(ActivityThread.java:6823)
at java.lang.reflect.Method.invoke(Native Method)
at …
```
> Fixed NullPointerException in HomeFragment by initializing wvProgressBar

- app/src/main/res/values/strings.xml
In the "different sections" section of the guide of multimeter for "voltage" there was grammatical error in the description. The strings.xml file has been modified to correct the error for better readability for the user.
**Changes**: 
The description for "Voltage" in "Different sections" section of Multimeter's guide is changed from "Mesures the voltage of any elements connect connected between any of the channel and GND pins and other pins such as AN8" to "Mesures the voltage of any element connected between any of the channel and GND pins and other pins such as AN8"
There is an extra "connect" written which is causing the grammatical error.
> Updating guide of multimeter

- app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
Upon deletion of a logged data, the toast message should show "Log Deleted" but for some devices like Oscilloscope, it is showing "Nothing to delete" upon deletion of a log.
Fixes #2168 
**Changes**: The condition statement written to decide whether the snackbar should show "Log Deleted" or "Nothing to Delete" is not required and directly "Log Deleted" message can be shown as when there is nothing in the log then there is no option for the user to delete a log as the items menu sets "Delete All" menu option visibility to false.
Before Changes:
After changes:
[delete-log-toast.zip](https://github.com/fossasia/pslab-android/files/5825582/delete-log-toast.zip)
> Changing Delete Log SnackBar

- app/src/main/res/values/strings.xml
The edit corrects the spelling of "Transforms" in the data analysis section of the guide of Oscilloscope. Initially, it was written as "Transfroms" which is now changed to "Transforms".
Fixes #2164 
**Changes**: 
Changed spelling of "Tranfroms" to "Transforms" in app/src/main/res/values/strings.xml line 532
> Correcting spelling in guide of Oscilloscope

- app/src/main/java/io/pslab/fragment/BluetoothScanFragment.java
@CloudyPadmal @mariobehling 
The same Bluetooth device is shown multiple time in the listview problem fixed #2204
> fix: same blutooth device shown multiple times

- app/src/main/res/values/strings.xml
In the guide of Wave Generator in the third line, it is written "allow us to changes" which should be "allows us to change".
**Changes**: 
In line 799 of strings.xml "allow us to changes" is changed to "allows us to change".
> docs: update guide of Wave generator in strings.xml

- app/src/main/res/layout/list_group.xml
Fixes #2200 
**Changes**: 
Added padding right to list_group.xml (displays question in faq fragment)
https://user-images.githubusercontent.com/52701183/111592618-06720000-87ef-11eb-94ca-d88b92177659.mp4
[minor_ui_improvement_faq.zip](https://github.com/fossasia/pslab-android/files/6164038/minor_ui_improvement_faq.zip)
> Minor improvement in faq fragment

- app/src/main/java/io/pslab/activity/DataLoggerActivity.java
The code has been modified to check whether any log is present while deleting and if no logs are present then the "Delete All Data" menu option shows a snackbar "Nothing To Delete".
Fixes #2184 
**Changes**: 
In the onOptionsItemSelected function under the category of R.id.delete_all an if condition is added to check whether the size of LocalDataLog is greater than 0 or not. If it is 0 then the "Delete All Data" displays a snackbar "Nothing to delete", otherwise functions normally as before.
Before: 
https://user-images.githubusercontent.com/65716045/105618271-6198ff00-5e0b-11eb-9801-90825859383b.mp4
After:
[app-fdroid-debug.zip](https://github.com/fossasia/pslab-android/files/5861389/app-fdroid-debug.zip)
> fix: updating "Delete All Data" operation

- app/src/main/java/io/pslab/activity/MainActivity.java
Fixes #2198 
**Changes**: 
Added a break statement for the case R.id.nav_rate in Main Activity, setUpNavigationView
https://user-images.githubusercontent.com/52701183/111511466-c706cd80-8774-11eb-87bb-8636b2276c57.mp4
> fix: rate app navigate back to FAQ

- app/src/main/res/layout/activity_create_config.xml
- app/src/main/res/layout/item_checkbox.xml
- app/src/main/res/values/dimens.xml
Fixes #2208 
Fixes #2181 
**Changes**:
1. Added Card Views for Instrument and Time Interval Sections on Generate Config Screen
2. Regularized the layout
[generate-config-layout.zip](https://github.com/fossasia/pslab-android/files/6246337/apk.zip)
> Fixes #2208 Card Layout Implemented for Generate Config Layout

- app/src/main/java/io/pslab/fragment/HomeFragment.java
- app/src/main/java/io/pslab/models/PSLabSensor.java
Fixes: [empty imageview is sensors bottomsheet guide]
**Changes**: [updated setupGuideLayout in abstract class PSLabSensor to hide image if not available in a sensor's bottomsheet guide]
`Before-------------------------------------------------------------------------------------------------------------After`
<p float="left">
</p>
> updated setupGuideLayout in abstract class PSLabSensor to hide image if not available in a sensor's bottomsheet guide

- app/src/main/java/io/pslab/fragment/BluetoothScanFragment.java
Fixes #2186
**Changes**: Provide fallback if a discovered Bluetooth device has no name.
**Checklist**:
[fix_bluetooth_crash.zip](https://github.com/fossasia/pslab-android/files/7198365/fix_bluetooth_crash.zip)
> Fix: 2186 Fix crash when searching for bluetooth devices

- app/src/main/java/io/pslab/fragment/HomeFragment.java
Fixes #2211
**Changes**: Added several null-checks to prevent NullPointerExceptions when referned views have already been removed in a later stage of the Fragment lifecycle.
[fix_rare_crash.zip](https://github.com/fossasia/pslab-android/files/7213159/fix_rare_crash.zip)
> Fixes #2211 fix rare crash

- .github/PULL_REQUEST_TEMPLATE
- .github/workflows/pull-request.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Fixes #2227 
**Changes**: 
- Upgraded `upload-artifacts` version to v2
- Updated apk paths with the correct ones
- Updated PR template removing APK requirement as APKs are auto-uploaded by GitHub actions
> N/A
> N/A
> chore: updated github actions and pull request template

- app/src/main/res/layout/activity_create_config.xml
- app/src/main/res/layout/activity_data_logger.xml
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/app_bar_main.xml
- app/src/main/res/layout/applications_fragment.xml
- app/src/main/res/layout/fragment_control_main.xml
- build.gradle
First steps for issues #2242 
**Changes**: 
- Upgraded realm
- Updated main layout files
N/A
**Checklist**:
> fix: upgrading xml files

- app/src/main/java/io/pslab/fragment/AboutUsFragment.java
**Fixes** #2267 
**Changes**: 
- mode of the device - from only light mode to choose according to device
https://user-images.githubusercontent.com/75962762/141722622-1c709ce5-0ee7-4db0-b51f-04af8fd77ad7.mp4
**Checklist**:
> Issue #2267: About us section just after launching app does not close navigation drawer and take longer time than usual 

- app/build.gradle
- app/src/main/AndroidManifest.xml
- build.gradle
- gradle.properties
**Fixes** #2283
**Changes**: 
- <!Removed jCenter() and added mavenCentral(), also updated the versions of libraries used>
**Checklist**:
> Upgraded gradle and substituted previously used features

- .github/workflows/pull-request.yml
The AdoptOpenJDK has been discontinued since July 2021 (https://adoptopenjdk.net). Switching the distribution to Azul Zulu. When using Zulu you get all the latest updated (TCK Tested) builds for all versions of OpenJDK. A matrix, or array was created in case you would like to add additional builds of the openjdk to test on.
**Fixes** N/A 
The fix is in the CI/CD GitHub workflow to use Zulu as the distribution of the JDK instead of AdoptOpenJDK, as it is discontinued.
Please see more details at Foojay.io:
https://foojay.io/today/github-actions-with-java-part-2/
**Changes**: 
- GitHub Actions setup-java's distribution as `zulu` instead of `adopt`
- Created a simple matrix, just in case you want to use JDK 17 or 18ea release
N/A
**Checklist**:
> Using TCK Tested JDK builds of OpenJDK

- .github/workflows/pull-request.yml
- .github/workflows/push-event.yml
**Fixes** #2311 
**Changes**: 
- Two workflows. One for pull requests where it will just builds the project, another for push events where it will generate apk files and upload to apk branch
> N/A
**Checklist**:
> chore: updated ga scripts to upload apks

- README.md
- app/src/main/java/io/pslab/fragment/SoundMeterDataFragment.java
**Changes**: 
- Fixed errors in readme and soundmeterdatafragment
> N/A
**Checklist**:
> fix: codacy errors when merging development branch

- app/src/main/AndroidManifest.xml
**Fixes** #2320 
**Changes**: 
- Added permission check to manifest
> N/A
**Checklist**:
> fix: sensor crash due to permission error

- app/src/main/java/io/pslab/activity/MapsActivity.java
Fixes #2304 
Map couldn't place the marker overlay due to differences in the JSON array passed for different sensors.
**Checklist**:
> fixed the map issue in compass

- app/src/main/java/io/pslab/fragment/ESPFragment.java
Fixes #2176 
After these changes, the keyboard collapses as soon as the "Connect" button is pressed to let the user see the snackbar.
**Checklist**:
> Fixed the snackbar issue

- app/src/main/java/io/pslab/fragment/BluetoothScanFragment.java
- Filter known Bluetooth devices (my TV always showed up in the list twice)
Before
After
**Checklist**:
> prevent duplicates in Bluetooth scan list

- app/src/main/java/io/pslab/fragment/LALogicLinesFragment.java
- app/src/main/res/values/strings.xml
Fixes #2360
- add check if loaded data is empty and display a warning
- add a null-check which prevents a NullPointerException if of PSLab is connected
**Checklist**:
> fix: crash if empty log is analysed

- .github/workflows/pull-request.yml
- .github/workflows/push-event.yml
- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/res/xml/data_extraction_rules.xml
- build.gradle.kts
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle.kts
Fixes #2386 
- Updated SDK versions
- Updated library versions and necessary version changes in configs
> N/A
**Checklist**:
> fix: updated app to run and compile
