fossasia/pslab-android

app/src/main/java/com/viveksb007/pslab/communication/PacketHandler.java
app/src/main/java/com/viveksb007/pslab/communication/ScienceLab.java
app/src/main/java/com/viveksb007/pslab/communication/SensorList.java
app/src/main/java/com/viveksb007/pslab/communication/analogChannel/AnalogInputSource.java
app/src/main/java/com/viveksb007/pslab/communication/peripherals/I2C.java

- Added sensorList
- updated analogChannel, packetHandler
- Implemented I2C ( 1 function remaining, it has some dependency would add later )

Fix #5 Added SensorList, updated packetHandler and implemented I2C

---

app/src/main/java/com/viveksb007/pslab/others/SensorList.java

SensorList.py ported to SensorList.java

SensorList.java

---

app/src/main/java/com/viveksb007/pslab/communication/peripherals/SPI.java

ported SPI class from peripherals.py

Fix #11 ported SPI class from peripherals.py

---

.travis.yml

travis is building successfully.

Fix #19 updated .travis.yml

---

app/src/main/java/com/viveksb007/pslab/communication/PacketHandler.java
app/src/main/java/com/viveksb007/pslab/communication/SensorList.java
app/src/main/java/com/viveksb007/pslab/communication/peripherals/NRF24L01.java

ported NRF24L01 from peripherals.py

Fixes #13 ported NRF24L01

---

app/src/main/java/com/viveksb007/pslab/communication/peripherals/DACChannel.java
app/src/main/java/com/viveksb007/pslab/communication/peripherals/MCP4728.java
app/src/main/java/com/viveksb007/pslab/communication/peripherals/NRF24L01.java
app/src/main/java/com/viveksb007/pslab/communication/peripherals/RadioLink.java

Fix #12 ported RadioLink class from Peripherals.py

Fix #12 ported RadioLink class from and reformatted code

---

.travis.yml
README.md
upload-apk.sh

Fixes #31 should work
and updated readme.md showing setup to use PSLab with Android App

Autogenerate apk in apk branch

---

upload-apk.sh

@mariobehling I sent a mail with GITHUB_API_KEY. please add that as Environment variables in travis build settings.
Referred this for change : https://github.com/fossasia/open-event-android/blob/development/upload-apk.sh#L15
Hopefully this would solve the issue.

updated upload-apk.sh

---

app/src/main/java/com/viveksb007/pslab/adapters/ApplicationsAdapter.java
app/src/main/java/com/viveksb007/pslab/fragment/ApplicationsFragment.java
app/src/main/res/layout/applications_fragment.xml
app/src/main/res/layout/applications_list_item.xml
upload-apk.sh

- optimised listView ( doesn't affect much in this case as there are only 8 list items )
- reformatted and cleaned code

reformatted and cleaned code

---

README.md

Fix #43 
Added md file in docs folder about building and running app.

added instructions about building and running app  

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/pslab/communication/peripherals/DACChannel.java

Added Intent-filter to solve #48 
Fixed the flawed logic in DACChannel.java as mentioned in #15

Updated AndroidMaifest.xml and DACChannel.java

---

README.md

Fixes #46 
Added build instructions for standalone apk and debug over Wi-Fi

Fixes #46 build instructions for standalone apk

---

app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
app/src/main/java/org/fossasia/pslab/communication/analogChannel/AnalogAquisitionChannel.java
app/src/main/java/org/fossasia/pslab/communication/analogChannel/AnalogConstants.java
app/src/main/java/org/fossasia/pslab/communication/analogChannel/AnalogInputSource.java
app/src/main/java/org/fossasia/pslab/communication/digitalChannel/DigitalChannel.java
app/src/main/java/org/fossasia/pslab/communication/peripherals/I2C.java
app/src/main/java/org/fossasia/pslab/communication/peripherals/MCP4728.java
app/src/main/java/org/fossasia/pslab/communication/peripherals/NRF24L01.java

ported some sciencelab functions ( rest I am still working on ) Partially FIX #27 
Added missing function of I2C.java

Ported some sciencelab functions

---

app/src/main/java/org/fossasia/pslab/communication/peripherals/MCP4728.java
app/src/main/java/org/fossasia/pslab/communication/sensors/BMP180.java
app/src/main/java/org/fossasia/pslab/communication/sensors/MLX90614.java
app/src/main/java/org/fossasia/pslab/communication/sensors/SHT21.java
app/src/main/java/org/fossasia/pslab/communication/sensors/TSL2561.java

- Updated  MCP4728.java to fix #51 
- Ported some Sensor files
-Added TSL2561.java #53 
-Added MLX90614.java #57 
-Added SHT21.java #54 
-Added BMP180.java #56

Updated MCP4728.java, Ported some Sensor files 

---

README.md
app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/pslab/activity/MainActivity.java
app/src/main/java/org/fossasia/pslab/communication/CommunicationHandler.java
app/src/main/java/org/fossasia/pslab/communication/PacketHandler.java
app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
app/src/main/java/org/fossasia/pslab/fragment/HomeFragment.java
app/src/main/res/xml/device_filter.xml

Fixes #48 
and updated version string in HomeFragment after communicating with device.

Communication Error Fixed

---

app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java

Partly Fix #27 
Ported read & write flash functions.
Almost done with WAVEGEN and capacitance calculation code.

ported read & write Flash functions and more

---

app/build.gradle
app/src/main/java/org/fossasia/pslab/communication/sensors/AD7718.java

Ported AD7718 sensor from the python version!

Fixes #81 : Porting AD7718

---

app/src/main/java/org/fossasia/pslab/communication/sensors/AD9833.java
app/src/main/java/org/fossasia/pslab/communication/sensors/HMC5883L.java

- Created AD9833.java fixes #78 
- Created HMC5883L.java fixes #77

Ported some sensor files

---

app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
app/src/main/java/org/fossasia/pslab/communication/peripherals/I2C.java

Fixes #101 added sub-function for capture

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/pslab/activity/AdvancedControlActivity.java
app/src/main/java/org/fossasia/pslab/activity/ControlActivity.java
app/src/main/java/org/fossasia/pslab/activity/LogicalAnalyzerActivity.java
app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/java/org/fossasia/pslab/fragment/ApplicationsFragment.java
app/src/main/java/org/fossasia/pslab/items/ApplicationItem.java
app/src/main/res/values/strings.xml

Added classes for below Applications 
- Oscilloscope
- Control
- Advanced Control
- Logical Analyzer
Would add more when these would be implemented to some extent.

Fixes #110 Added boilerplate code for some activities

---

app/src/main/java/org/fossasia/pslab/communication/sensors/MPU925x.java

Added MPU925x.java

---

app/build.gradle
app/src/main/java/org/fossasia/pslab/activity/MainActivity.java

Used `Butter Knife` library to generate boilerplate code to make it easy to bind views.
**Changes made**
- Added required dependencies in the Gradle
- Implementation in `MainActivity`

Refactor #116 : Added Butterknife Dependencies

---

app/src/main/java/org/fossasia/pslab/activity/AboutUs.java
app/src/main/java/org/fossasia/pslab/activity/AdvancedControlActivity.java
app/src/main/java/org/fossasia/pslab/activity/ControlActivity.java
app/src/main/java/org/fossasia/pslab/activity/HelpAndFeedback.java
app/src/main/java/org/fossasia/pslab/activity/LogicalAnalyzerActivity.java
app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/java/org/fossasia/pslab/activity/ReportUs.java
app/src/main/java/org/fossasia/pslab/activity/SplashActivity.java
app/src/main/java/org/fossasia/pslab/fragment/ApplicationsFragment.java
app/src/main/java/org/fossasia/pslab/fragment/DesignExperiments.java
app/src/main/java/org/fossasia/pslab/fragment/HomeFragment.java
app/src/main/java/org/fossasia/pslab/fragment/SavedExperiments.java

In the earlier PR, merge conflicts were created since I had synced my local repo. So, this PR doesn't have conflicts.

Fixes #116 implements butterknife

---

app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
app/src/main/java/org/fossasia/pslab/communication/peripherals/MCP4728.java

fixed #125 resolved method and added corresponding reference

---

app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
app/src/main/java/org/fossasia/pslab/communication/analogChannel/AnalogInputSource.java
app/src/main/java/org/fossasia/pslab/communication/peripherals/DACChannel.java

Fixes #121 Successfully read complete calibration data in chunks.
Fixes #129 Unpacked Correctly
Partly Fixes #104 ( creating a Polynomial Function from read values is remaining )
All the above issues were from same method, so updated them in single PR.

Updated calibration method 

---

app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java

Fixes #104 Calibration method completed.
Calibration method is ported completely.

Fixes #104  calibration method completed

---

app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java

Fixes  #134 
No changes in source code, just re-ordering of methods section-wise for easy reference.

Fixes #134 Re-ordered Methods Section Wise

---

app/src/main/java/org/fossasia/pslab/communication/AnalyticsClass.java
app/src/main/java/org/fossasia/pslab/filters/BandstopFilter.java
app/src/main/java/org/fossasia/pslab/filters/Lfilter.java

fixes #115 
- added Damped Sine Fit
- added arbitfit
- added Butter Notch Filter
- added Bandstop filter
- added lfilter

Added remaining methods in AnalyticsClass.java

---

app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java

The flush method is commented on line 1122 as it has not been implemented

Fixes #138 Completes methods of analog section in ScienceLab

---

app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
app/src/main/java/org/fossasia/pslab/communication/digitalChannel/DigitalChannel.java

Fixes #136 Ported LA functions from [sciencelab.py](https://github.com/fossasia/pslab-python/blob/development/PSL/sciencelab.py)
This PR is a bit long as none of Logic Analyzer functions were ported before. So it might be a bit difficult to review.
Problem with breaking issue into smaller issue was, most methods are interlinked, so its difficult to find independent methods to open issue for.

Completed LA functions in ScienceLab.java

---

app/src/main/java/org/fossasia/pslab/activity/LogicalAnalyzerActivity.java
app/src/main/java/org/fossasia/pslab/fragment/LAChannelModeFragment.java
app/src/main/res/drawable/custom_border.xml
app/src/main/res/layout/activity_logic_analyzer.xml
app/src/main/res/layout/logic_analyzer_select_channel.xml
app/src/main/res/layout/single_channel_mode_la.xml
app/src/main/res/values/strings.xml

Coding UI for Logic Analyzer by taking reference from [LAmockup](https://app.moqups.com/viveksbhadauria007@gmail.com/Xz2hJPtEc5/view) here.
Partly takes care of #142 
Spinners in block changes dynamically by selecting channel modes from top spinner.

UI for Logic Analyzer

---

app/src/main/java/org/fossasia/pslab/communication/CommunicationHandler.java

unnecessary IOException fixed

---

app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
app/src/main/java/org/fossasia/pslab/communication/analogChannel/AnalogInputSource.java

Fixes #137 
And modified AnalogInputSources.java methods to handle arrays as input.

Completed capacitance calculating methods

---

.github/ISSUE_TEMPLATE
.github/PULL_REQUEST_TEMPLATE

Fixes #139 
Added template for Issue and PR and now we have started working with UI. So a proper structure to report issue and submit PR would be great.
Copied susi_android template for now.

added template for ISSUE and PR

---

app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/java/org/fossasia/pslab/fragment/ChannelParametersFragment.java
app/src/main/java/org/fossasia/pslab/fragment/DataAnalysisFragment.java
app/src/main/java/org/fossasia/pslab/fragment/TimebaseTiggerFragment.java
app/src/main/java/org/fossasia/pslab/fragment/XYPlotFragment.java
app/src/main/res/layout-sw600dp/activity_oscilloscope.xml
app/src/main/res/layout/activity_oscilloscope.xml
app/src/main/res/layout/fragment_timebase_tigger.xml

fixes #157
In this PR
-  Scaling of the graph according to different events occurring across different fragments is done, for example selecting range +/-4V of CH1 changes the left Y axis maximum and minimum value accordingly.
- Attached Listeners
- Made few changes in the UI
Video link - https://goo.gl/photos/qyYmmJhtZrzCM7NRA

Made modifications in Oscilloscope UI

---

.travis.yml

Fixes issue #164 
Changes: Modified travis.yml file for cache.

modified tavis.yml for enable cache

---

app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/res/layout-sw600dp/activity_oscilloscope.xml
app/src/main/res/layout/activity_oscilloscope.xml

Fixes issue #168 
Changes: 
- Added onClickListners to TextViews
video link: https://goo.gl/photos/vVgkXp5QnoQi8tZK9

Added onClickListners to TextViews

---

app/src/main/java/org/fossasia/pslab/fragment/ControlFragmentMain.java
app/src/main/java/org/fossasia/pslab/fragment/ControlFragmentRead.java
app/src/main/res/layout/control_main_list_item.xml
app/src/main/res/layout/fragment_control_advanced.xml
app/src/main/res/layout/fragment_control_read.xml

Fixes Issue #146
Changes: 
* Changed the UI for resistance & capacitance labels.
* Added methods for Control Read section. (haven't been tested, so commented till then)
* Temporarily replaced Butterknife due to a null object exception error. Need to identify the actual cause of the problem that led to this.(will find it out)

Fixes #146 creates read section of Control UI

---

app/src/main/res/layout/control_main_list_item.xml
app/src/main/res/values/dimens.xml

Fixes issue #176 
Changes:
- Added padding to the list item
- Set type as decimals in text boxes
- Exported dimensions to `dimens.xml` so that it is easy to set dimensions for different screen sizes at one place
- Added padding to text boxes

Fix #176 : Main Control Panel UI Fixes

---

app/src/main/java/org/fossasia/pslab/fragment/TimebaseTiggerFragment.java
app/src/main/java/org/fossasia/pslab/others/FloatSeekBar.java
app/src/main/res/layout/fragment_timebase_tigger.xml

Fixes issue #203 
Changes: 
- Common slider for both sliders

Fix #203 : Common Slider in Oscilloscope

---

app/src/main/java/org/fossasia/pslab/activity/MainActivity.java
app/src/main/java/org/fossasia/pslab/communication/CommunicationHandler.java
app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java

Fixes issue #179 
Changes: Successfully obtained explicit permission to access USB device. Tested by Other devs.

fixed obtaining explicit permission to access USB device

---

app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
app/src/main/java/org/fossasia/pslab/fragment/HomeFragment.java
app/src/main/res/values/strings.xml

Fixes issue #205 
Changes: Initialisation moved to another thread. Now UI doesn't freeze during initialisation.
[apk link](https://drive.google.com/open?id=0B30IF3fyX4Q3b25kTmxFTnBGTG8) for testing.

Initialisation moved to another thread to unblock UI thread

---

app/src/main/java/org/fossasia/pslab/fragment/LAChannelModeFragment.java

Fixes issue #213
Changes: 
- Views were hidden inside a listener. Initials views were set visibilities inside the oncreate method
> Screen updates are hard to capture

Fixes #213 : Screen updates are not visible to user in Logic Analyzer

---

app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java

Fixes issue #220 
Changes: Corrected loop iteration ranges and fixed some warnings.

fixed loop iteration and list creation from primitives

---

app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/java/org/fossasia/pslab/communication/CommunicationHandler.java
app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
app/src/main/res/layout-sw600dp/activity_oscilloscope.xml
app/src/main/res/layout/activity_oscilloscope.xml

Fixes #200 and #212 
Changes: 
- Implemented captureOne method
- Prevented Oscilloscope Activity to sleep while running.
Things still left to be done
- Remove read errors
- Determine no. of samples and time-gaps 
- speed up the process

Initial steps for implementing CaptureOne method in Oscilloscope UI

---

README.md

Fixes issue #226 
Removed Advanced Control from features and merged in Control. And changed some status to working.

Update README.md with current project status

---

app/src/main/java/org/fossasia/pslab/adapters/ControlMainAdapter.java
app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
app/src/main/java/org/fossasia/pslab/communication/peripherals/MCP4728.java
app/src/main/res/layout/control_main_list_item.xml

Fixes issue #234 
Changes: allowed negative number input in edit text and added callbacks to set voltage and current.

negative numbers fixed and added callbacks

---

app/src/main/res/layout-hdpi/control_main_list_item.xml
app/src/main/res/values-hdpi/dimens.xml

Fixes issue #224 
Changes: 
- Added `dimens.xml` to support hdpi screens
- Added `control_main_list_item.xml` to support hdpi screens

Fixes #224 : Control Main UI supports hdpi screens

---

app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/java/org/fossasia/pslab/receivers/USBDetachReceiver.java

Fixes #233 
Changes: 
- Handled abrupt disconnection in Oscilloscope Activity. 
- Handled the possible exceptions.
video link - https://goo.gl/photos/76mWQqTdtaw79XaZ7

Handled abrupt disconnection in Oscilloscope Activity

---

app/src/main/java/org/fossasia/pslab/adapters/ControlMainAdapter.java

Fixes issue #228 
Changes: 
- Added `DecimalFormat` to set required decimal places into input boxes

Fixes #228 : Resolutions set to required amounts in control UI

---

app/src/main/java/org/fossasia/pslab/activity/SensorActivity.java
app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
app/src/main/java/org/fossasia/pslab/communication/sensors/BH1750.java
app/src/main/java/org/fossasia/pslab/communication/sensors/MPU6050.java
app/src/main/java/org/fossasia/pslab/communication/sensors/Sx1276.java
app/src/main/res/layout/activity_sensor.xml

Fixes issue #201
Changes: 
* Added scienceLab methods and functions to buttons, spinners etc.
* As of now, no I2C sensors are available with me for testing. As soon as I receive my order of sensors, the code will be tested and further changes will be made.
* Some minor change in a few sensor files.

Fixes #201 Adds functionality to Sensor QuickView

---

app/src/main/java/org/fossasia/pslab/adapters/ControlMainAdapter.java

Fixes issue #231 
Changes: 
- Added try catch statements to handle the empty text boxes when user deletes values in them.

Fixes #231 : Crash handling in Control Main UI

---

app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java

Partly Fixes issue #240 
Changes:
- Implemented captureTwo method in UI
- Implemented catureFour method in UI
- Fixed some capture methods
(There are read errors)
video link - https://goo.gl/photos/hWonmBciNnmhZZ2P9

Implemented captureTwo and captureFour methods in UI

---

app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java

Fixes issue #248 
Changes: 
- Application tries to read from an array when there is no values in it when a device is not connected. Caught the exception in this fix

Fixes #248 : App crash when multiple channels are selected

---

app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/java/org/fossasia/pslab/communication/CommandsProto.java
app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
app/src/main/java/org/fossasia/pslab/communication/analogChannel/AnalogAquisitionChannel.java
app/src/main/java/org/fossasia/pslab/communication/analogChannel/AnalogInputSource.java

Fixes issue #255 #256 
Partially Fixes #249 
Changes: 
- fixed calibration data unpacking 
- byte order in making int from bytes
- fixed unsigned problem of byte ( In JAVA unsigned byte isn't supported, casted byte as ```int```, then ```ANDed``` with ```0xff```  )
- Fixed ```Polynomial Function``` Creation, unlike numpy Apache Common Math calculates value at a data point with reverse order of coefficient w.r.t ```numpy1D``` function.  
There are still readback error but now we can read most of sample data.
[Screencast](https://goo.gl/photos/ANicGk9EpygdKopD9) 
[APK Link](https://drive.google.com/open?id=0B30IF3fyX4Q3bXB4SVJnQ0dLems)

Improved readback speed and fixed various bugs

---

app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
app/src/main/java/org/fossasia/pslab/communication/analogChannel/AnalogInputSource.java
app/src/main/java/org/fossasia/pslab/fragment/ControlFragmentAdvanced.java
app/src/main/java/org/fossasia/pslab/fragment/ControlFragmentRead.java
app/src/main/java/org/fossasia/pslab/others/Edittextwidget.java
app/src/main/res/layout/fragment_control_advanced.xml

Fixes issue #239 
Changes: 
* Added scienceLab methods to Read & Advanced section of Control. The part of the code which causes errors has been commented as of now and I am looking into it.
* Changes datatype of frequency to `double` in scienceLab.

Fixes #239 adds scienceLab methods to Advanced & Main section of control UI

---

app/src/main/java/org/fossasia/pslab/communication/PacketHandler.java

Fixes issue #265 
Changes: Modified getInt and getLong methods of packetHandler

fixed getInt and getLong methods in packetHandler

---

app/src/main/java/org/fossasia/pslab/adapters/ApplicationAdapter.java
app/src/main/java/org/fossasia/pslab/fragment/ApplicationsFragment.java

Fixes issue #269 
Changes: removed extra Data Sensor Logger tile.

removed extra data-sensor logger tile

---

app/src/main/java/org/fossasia/pslab/activity/LogicalAnalyzerActivity.java
app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
app/src/main/res/layout/activity_logic_analyzer.xml
app/src/main/res/values/strings.xml

Fixes issue #276 
Changes:
- Removed Description label
- Mapped legend with Logic Line channel.
- Added padding in Fragments inserted in Logic Analyzer Activity.

minor UI improvements

---

app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/java/org/fossasia/pslab/fragment/XYPlotFragment.java

Fixes issue #280 
Changes: 
- Added a listener to the spinner so that the activity UI gets updated
APK for testing
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1127424/app-debug.apk.zip)
Screen Recording
[recording.mp4.zip](https://github.com/fossasia/pslab-android/files/1127425/recording.mp4.zip)

Fixes #280 : Oscillator XY Plot graph updates with channel select

---

app/src/main/res/drawable/tv_border.xml
app/src/main/res/layout-hdpi/control_main_list_item.xml
app/src/main/res/layout-hdpi/fragment_control_read.xml
app/src/main/res/layout-xhdpi/control_main_list_item.xml
app/src/main/res/layout-xhdpi/fragment_control_read.xml
app/src/main/res/layout/control_main_list_item.xml
app/src/main/res/layout/fragment_control_read.xml

Fixes issue #283 
Changes: Added border around textViews and some other changes in View property.
<table>
<tr>
<td>
<td>
</td>
</tr>
</table>

border added around textViews

---

app/src/main/java/org/fossasia/pslab/adapters/ControlMainAdapter.java
app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
app/src/main/java/org/fossasia/pslab/communication/peripherals/MCP4728.java
app/src/main/java/org/fossasia/pslab/fragment/ControlFragmentAdvanced.java

Fixes issue #286 #287 
Changes: 
- Fixed App crash  on setting Voltage/Current
- Added some left-out function calls in Control Main.
Checked voltage and square wave from Oscilloscope. Didn't have multi-meter to check exact voltages.

fixed crash on setting voltage/current and added left-out callbacks

---

README.md

Fixes issue #300 
Changes: 
- Replaced strike-through formatting with check-boxes with ticks

Fixes #300 : Update README.md with checkboxes

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/pslab/others/AudioJack.java

partially fixes issue #294 
Changes: 
- AudioJack class would initialise AudioRecord and AudioTrack objects and provide function to read and write buffer.
Need to test whether buffer read & write would work as it is or need to shift them to another thread. 
Screenshots for the change: NA

started implementing using audioJack as probe and wavegenerator

---

app/src/main/AndroidManifest.xml

Fixes issue #305 
Changes: 
- Retains on same fragment on screen rotation.

fixed #305 : Control Activity retains state on screen rotation

---

app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/res/layout-sw600dp/fragment_channel_parameters.xml
app/src/main/res/layout/fragment_channel_parameters.xml

Fixes #308 
Changes: 
- Enabled CH1 by default in Oscilloscope UI
Apk: 
[Uploading app-debug.apk.zip…]()
> None

Enabled CH1 by default in Oscilloscope UI

---

app/src/main/java/org/fossasia/pslab/communication/sensors/AD7718.java
app/src/main/java/org/fossasia/pslab/communication/sensors/AD9833.java
app/src/main/java/org/fossasia/pslab/communication/sensors/ADS1115.java
app/src/main/java/org/fossasia/pslab/communication/sensors/BH1750.java
app/src/main/java/org/fossasia/pslab/communication/sensors/BMP180.java
app/src/main/java/org/fossasia/pslab/communication/sensors/ComplementaryFilter.java
app/src/main/java/org/fossasia/pslab/communication/sensors/KalmanFilter.java
app/src/main/java/org/fossasia/pslab/communication/sensors/MF522.java
app/src/main/java/org/fossasia/pslab/communication/sensors/MLX90614.java
app/src/main/java/org/fossasia/pslab/communication/sensors/MPU6050.java
app/src/main/java/org/fossasia/pslab/communication/sensors/MPU925x.java
app/src/main/java/org/fossasia/pslab/communication/sensors/SHT21.java
app/src/main/java/org/fossasia/pslab/communication/sensors/SSD1306.java
app/src/main/java/org/fossasia/pslab/communication/sensors/TSL2561.java

Fixes issue #299 
Changes: 
* Removed params from sensor files which is not necessary for Android and in some cases replaced fields with corresponding ArrayLists.
* Some changes might be due to reformatting of code.
None

Removed params and edited sensor files

---

app/src/main/java/org/fossasia/pslab/experimentsetup/ZenerSetupFragment.java
app/src/main/res/layout/zener_setup.xml

Fixes issue #321 
Changes:
- created a thread that increases voltage from Initial Voltage to Final Voltage by increasing stepSize voltage.
- For each voltage x,y data points are generated.
P.S- Value of voltage read by getVoltage is wrong due to error in reading some bytes. And plot isn't real-time. Curve is plotted once all data points are acquired. Added the screenshot for captured data points too.
Would open another issue for wrong value read from ```get_voltage()``` method.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/12713808/28279311-ba3e1678-6b3d-11e7-82c1-ff6c6ef3857c.png"></td>
<td><img src="https://user-images.githubusercontent.com/12713808/28279312-ba8dfff8-6b3d-11e7-9369-bcdd13fa2488.png"></td>
</tr>
</table>

functionality added to perform zener I-V experiment

---

app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java
app/src/main/java/org/fossasia/pslab/fragment/SavedExperiments.java
app/src/main/res/values/strings.xml

Fixes issue #332 
Changes:
- Mapped available experiments in doc with expandableListView of Saved Experiments. Other experiments docs are being created in pslab-desktop-app. Once finalised there would make necessary changes here. Till then would add Experiment Setup and functionality support for experiments which are already mapped.
Apk for testing 
[pslab.apk.tar.gz](https://github.com/fossasia/pslab-android/files/1155148/pslab.apk.tar.gz)

mapped more experiments

---

README.md

Fixes issue #337 
Changes: 
- uploaded apk on appetize.io and added link to app preview on README.md
Link for preview : [preview link](https://appetize.io/app/4eqye6ea422e5np0gp2jfpemgm)

added app preview support from appetize.io and updated README.md

---

.travis.yml
app/build.gradle
app/src/androidTest/java/org/fossasia/pslab/ExampleInstrumentedTest.java
app/src/androidTest/java/org/fossasia/pslab/MainActivityTest.java

Partially Fixes issue #333 
Changes:
- Added Test to open all fragments of MainActivity.
Checked by ```./gradlew connectedAndroidTest``` works fine.
NA

added UI test to check all fragments of MainActivity

---

app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/java/org/fossasia/pslab/fragment/ChannelParametersFragment.java
app/src/main/java/org/fossasia/pslab/others/NothingSelectedSpinnerAdapter.java
app/src/main/res/layout-sw600dp/fragment_channel_parameters.xml
app/src/main/res/layout/custom_spinner_mic.xml
app/src/main/res/layout/custom_spinner_mic_tablet.xml
app/src/main/res/layout/fragment_channel_parameters.xml
app/src/main/res/layout/nothing_selected_spinner_row.xml

Fixes #325 
Changes: 
-Added option for inbuilt mic in Oscilloscope

Modified Oscilloscope UI to include selection of plotting data from in-built Mic

---

app/src/main/java/org/fossasia/pslab/fragment/SensorFragmentHMC5883L.java
app/src/main/res/layout/sensor_hmc5883l.xml

Fixes #318 
Changes: 
- Added real-time graph 
Note: 
1) for now raw data points are plotted with the time gap of 500 milliseconds.
2) @asitava1998 is looking into the conversion of raw data to Gauss.

Implemented graph in HMC5883L

---

app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/java/org/fossasia/pslab/others/AudioJack.java

Fixes issue #322 
Changes:
- Added code to monitor in-built mic selection
- Added thread to fetch and log audio buffer

Fixes #322 routine to capture audioBuffer added and logged buffer successfully

---

build.gradle

Fixes issue #351 
Changes: 
- In stacktrace log there was some error due to gradle, updating gradle fixed the problem. 
Checked it in my fork's build.

Fixed #351 Fixed travis build

---

app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
app/src/main/res/layout-land/logic_analyzer_logic_lines.xml
app/src/main/res/layout/activity_logic_analyzer.xml
app/src/main/res/layout/logic_analyzer_logic_lines.xml
app/src/main/res/values/strings.xml

Fixes issue #346 
Changes: 
- Adopted implementation from Oscilloscope done by Akarshan! (Special thanks :) )
- LED will change from green to red when device is unplugged
- LED will remain red when device is not plugged
[Screencast](https://drive.google.com/open?id=0B5su2_aUn8g7Q1lPNEs1bmpUMXc)
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1161126/app-debug.apk.zip)

Fixes #346: LED indicator for Logic Analyzer

---

app/src/main/java/org/fossasia/pslab/fragment/SensorFragmentMPU6050.java
app/src/main/res/layout/sensor_mpu6050.xml
app/src/main/res/values/strings.xml

Fixes #345 
Changes: 
Made Accelerometer and Gyroscope graphs functional

Added Accelerometer and Gyroscope graphs

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/pslab/activity/SensorDataLoggerActivity.java
app/src/main/java/org/fossasia/pslab/fragment/ApplicationsFragment.java
app/src/main/res/drawable/ic_fullscreen_black_24dp.xml
app/src/main/res/layout/activity_data_sensor_logger.xml
app/src/main/res/values/strings.xml

Fixes issue #364 
Changes:
- boiler plate code for activity added
- asks user for WRITE_STORAGE permission to log data

Basic sensorDataLogger activity created 

---

app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java
app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorCEOutputSetup.java
app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorCESetup.java
app/src/main/java/org/fossasia/pslab/fragment/SavedExperiments.java
app/src/main/res/layout/transistor_ce_output_configure_dialog.xml

Fixes issue #347 
Changes:
- Added BJT CE output characteristic experiment setup layout
Apk for testing 
[pslab.apk.tar.gz](https://github.com/fossasia/pslab-android/files/1169064/pslab.apk.tar.gz)

fixes #347 added BJT related experiments setup layout

---

app/src/main/java/org/fossasia/pslab/adapters/ControlMainAdapter.java

Fixes issue #368 
Changes: 
- Set limits to seekbars
- Adjusted step sizes
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1171828/app-debug.apk.zip)

Fixes #368 : Control Main Seekbars stays within limits

---

app/src/main/java/org/fossasia/pslab/activity/SensorActivity.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentADS1115.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentBH1750.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentBMP180.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentHMC5883L.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentMLX90614.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentMPU6050.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentMain.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentSHT21.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentTSL2561.java
app/src/main/res/layout/sensor_bh1750.xml
app/src/main/res/layout/sensor_mpu6050.xml
app/src/main/res/layout/sensor_tsl2561.xml
app/src/main/res/values/strings.xml

Fixes issue #358 
Changes: 
* Changes object names to improve code readability
* Creates a separate directory for sensor files.
None

Aligns sensor files with current coding style

---

app/src/main/res/layout/sensor_ads1115.xml
app/src/main/res/layout/sensor_bh1750.xml
app/src/main/res/layout/sensor_bmp180.xml
app/src/main/res/layout/sensor_hmc5883l.xml
app/src/main/res/layout/sensor_mlx90614.xml
app/src/main/res/layout/sensor_mpu6050.xml
app/src/main/res/layout/sensor_sht21.xml
app/src/main/res/layout/sensor_tsl2561.xml
app/src/main/res/values/dimens.xml

Fixes issue #371 
Changes: 
* Makes the UI across all layout files uniform.
* Some minor changes like text sizes, layout margins etc.
Screenshots for the change: `Some screenshots for reference`
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/19410364/28620142-4f2f3036-7229-11e7-9e8b-adea6ef77fcd.png"></td>
<td><img src="https://user-images.githubusercontent.com/19410364/28620144-514c94f8-7229-11e7-88f7-60d96af530c7.png"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/19410364/28620149-540b1264-7229-11e7-84c3-9a64933dcbe7.png"></td>
<td><img src="https://user-images.githubusercontent.com/19410364/28620151-568caa2a-7229-11e7-9e53-69e6efe0324a.png"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/19410364/28620154-590fe87a …

Makes changes in sensor layout files to bring uniformity

---

app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentSHT21.java
app/src/main/res/layout/sensor_sht21.xml

Fixes #373 
Changes: 
- Implemented graphs in SensorFragmentSHT21. One graph is for Humidity while another for temperature.
** If there is any problem while testing the graphs with SHT21 sensor in future, will create an issue and fix it.

Implemented graphs in SensorFragmentSHT21

---

app/src/androidTest/java/org/fossasia/pslab/MainActivityTest.java

Fixes issue #397 
Changes: 
- Added UI test case to include saved experiment holder

Fixes #397 : UI test case for Saved Experiments

---

app/src/main/java/org/fossasia/pslab/experimentsetup/OhmsLawSetupExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorCBSetup.java
app/src/main/java/org/fossasia/pslab/experimentsetup/ZenerSetupFragment.java

Fixes issue #400 
Changes:
- App crash fixed on performing experiment when pslab device isn't connected.

Fixes #400 app crash fixed on perform experiment if device isn't connected

---

app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentADS1115.java
app/src/main/res/layout/sensor_ads1115.xml

Fixes #396 
Changes:
Implemented graph in SensorFragmentADS115

Implemented graph in SensorFragmentADS1115

---

app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
app/src/main/java/org/fossasia/pslab/others/MathUtils.java

Fixes issue #380 
Changes:
- Added implementation of linspace() from numpy to MathUtils Java.

Fixes #380 added linspace() to MathUtils

---

app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorCBSetup.java
app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorCEOutputSetup.java

Fixes issue #378
Changes: 
- Added code for functionality of BJT experiments
- Updated refreshing of graph in realtime.

Fixes #378 added BJT experiment functionality realtime

---

app/src/main/java/org/fossasia/pslab/experimentsetup/NFETOutputCharacteristicsExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorCBSetup.java
app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorCEOutputSetup.java
app/src/main/java/org/fossasia/pslab/experimentsetup/ZenerSetupFragment.java

Fixes issue #420 
Changes: 
- Added a check to final voltage values when they are set to function parameters

Fixes #420 : Checks final voltage and initial voltage

---

app/src/main/assets/DOC_HTML/apps/D_NFET_GS_ID.html

Fixes issue #430 
Changes: 
- Created a similar html file as D_NFET.html
| Old | New |
| ---- | ------ |
| ![previousscreen](https://user-images.githubusercontent.com/14261304/28996973-228e6cec-7a3d-11e7-90c2-0789de84f20f.png) | ![htmlfile](https://user-images.githubusercontent.com/14261304/28996975-2c601c0c-7a3d-11e7-8da3-db63729d3cf6.png) |

Fixes #430 : D_NFET_GS_ID file modified

---

app/src/main/assets/DOC_HTML/apps/D_transistorCE_input.html

Fixes issue #439 
Changes:
- Added content in a similar html format
| Before | After |
| ---- | ----|
| ![before](https://user-images.githubusercontent.com/14261304/29003331-67501718-7ae7-11e7-87c1-977736528591.png) | ![after](https://user-images.githubusercontent.com/14261304/29003335-6b602906-7ae7-11e7-9fa6-6c58307beac8.png) |

Fixes #439 : Resource file for BJT CE Input Characteristics Experiment

---

app/src/main/java/org/fossasia/pslab/experimentsetup/NFETOutputCharacteristicsExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/OhmsLawSetupExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorCBSetup.java
app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorCEOutputSetup.java
app/src/main/java/org/fossasia/pslab/experimentsetup/ZenerSetupFragment.java
app/src/main/res/layout/diode_setup.xml
app/src/main/res/layout/ohms_law_setup.xml
app/src/main/res/values/attr.xml
app/src/main/res/values/strings.xml

Fixes issue #438 
Changes:
- Disabled Description label in experiment setup charts
- Added X-axis label in charts
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/12713808/29003373-542571b0-7ad3-11e7-8307-23e6572ab137.png"></td>
<td><img src="https://user-images.githubusercontent.com/12713808/29003374-54297936-7ad3-11e7-8a28-1ae2e242c9d4.png"></td>
</tr>
</table>

Fixes #438 added label to chart and disabled description

---

docs/privacy_policy.html

Fixes issue #458
Changes: 
- Added privacy policy to upload apk on play store
[Template Used](https://gist.github.com/alphamu/c42f6c3fce530ca5e804e672fed70d78)

Fixes #458 added privacy policy

---

app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java
app/src/main/java/org/fossasia/pslab/experimentsetup/RectifierExperiment.java
app/src/main/java/org/fossasia/pslab/fragment/ApplicationsFragment.java
app/src/main/java/org/fossasia/pslab/fragment/HalfwaveRectifierFragment.java
app/src/main/java/org/fossasia/pslab/fragment/SavedExperiments.java
app/src/main/res/layout/fragment_halfwave_rectifier.xml
app/src/main/res/layout/rectifier_setup.xml
app/src/main/res/values/strings.xml

Fixes #446 
Changes: 
Implemented Halfwave Rectifier Experiment
Apk:
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1209660/app-debug.apk.zip)
*In the screenshot I have mapped output signal to CH1 for the demo purpose. Please check the apk for both input and output signals.

Implemented Halfwave Rectifier Experiment

---

app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentMain.java

Fixes issue #473 
Changes:
- Sensor scanning routine moved to another thread to prevent lag in UI.
Tested successfully with PSLab Device.
[app-debug.apk.tar.gz](https://github.com/fossasia/pslab-android/files/1215641/app-debug.apk.tar.gz)

Fixed #473 sensor scanning moved to other thread. No Lag in UI

---

app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java
app/src/main/java/org/fossasia/pslab/experimentsetup/RectifierExperiment.java
app/src/main/java/org/fossasia/pslab/fragment/FullWaveRectifierFragment.java
app/src/main/java/org/fossasia/pslab/fragment/SavedExperiments.java
app/src/main/res/layout/fragment_full_wave_rectifier.xml
app/src/main/res/layout/fragment_halfwave_rectifier.xml
app/src/main/res/values/strings.xml

Fixes #469 
Changes:
Implemented FullWave Rectifier Experiment
Apk:
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1216064/app-debug.apk.zip)

Implements FullWave Rectifier Experiment

---

app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java
app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorAmplifierExperiment.java
app/src/main/java/org/fossasia/pslab/fragment/SavedExperiments.java
app/src/main/res/layout/transistor_amplifier_characteristics_dialog.xml
app/src/main/res/layout/transistor_amplifier_view.xml
app/src/main/res/values/strings.xml

Fixes issue #459 
Changes: 
- Implemented similar experiment to the desktop application
- Used functions in oscilloscope activity to capture trace
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1210702/app-debug.apk.zip)
There is a huge distortion happening and can you guys review this PR to see if I have made any errors in implementing the functionalities? Thanks a lot in advance. I have used W1 and W2 to generate waveforms at 200 Hz and 400 Hz respectively. W1 connected to CH2 and W2 connected to CH1.

Fixes #459 : Transistor Amplifier Experiment

---

app/src/main/res/layout/sensor_mpu6050.xml

Fixes issue #477 
Changes:
- Values in TextView in Sensor MPU6050 is limited to 1 line.
- Removed redundant code and improved layout.

Fixed #477 MPU6050 sensor layout improved

---

app/src/main/java/org/fossasia/pslab/experimentsetup/NFETOutputCharacteristicsExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/NFETTransferCharacteristicsExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/OhmsLawSetupExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorCBSetup.java
app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorCEInputCharacteristicsExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorCEOutputSetup.java
app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorTransferExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/ZenerSetupFragment.java
app/src/main/res/layout/diode_setup.xml
app/src/main/res/layout/ohms_law_setup.xml

Fixes issue #491 
Changes: 
- Changed graph background to black and labels white
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1219876/app-debug.apk.zip)

Fixes #491 : Uniform background for saved experiments graphs

---

app/src/main/java/org/fossasia/pslab/activity/ShowLoggedData.java
app/src/main/java/org/fossasia/pslab/adapters/MPUDataAdapter.java
app/src/main/res/layout/activity_show_logged_data.xml
app/src/main/res/layout/sensor_mpu6050_data_card.xml

Fixes issue #494 
Changes: 
- Added RecyclerView to show logged sensor data.
- Querying Ream Database to fetch sensor data. 
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/12713808/29250286-d3b30976-805d-11e7-82b2-56695a344d7f.png"></td>
<td><img src="https://user-images.githubusercontent.com/12713808/29250285-d3afa358-805d-11e7-8173-f00aa72b56a2.png"></td>
</tr>
</table>

Fixed #494 functionality to view logged data added

---

app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java

Fixes issue #498 
Changes: 
- Used string resources for hardcoded strings

Fixes #498 : Hardcoded strings in saved experiments

---

README.md

Fixes issue #501
https://github.com/viveksb007/pslab-android/blob/readme/README.md

Fixes #501 updated readme with branch policy

---

app/src/main/java/org/fossasia/pslab/adapters/ControlMainAdapter.java
app/src/main/java/org/fossasia/pslab/others/MathUtils.java

Fixes issue #511 
Changes:
- Prevented unwanted trigger in EditText value by SeekBar.
- Modified map() function to support double data types.
apk for testing : 
[app-debug.apk.tar.gz](https://github.com/fossasia/pslab-android/files/1221796/app-debug.apk.tar.gz)

Fixes #511 Fixed buggy behaviour of control main fragment

---

app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentADS1115.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentBH1750.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentBMP180.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentHMC5883L.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentMLX90614.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentMPU6050.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentMPU925X.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentMain.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentSHT21.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentTSL2561.java
app/src/main/res/values/strings.xml

Fixes #513 #315 
Changes: 
- Aligned sensor fragment files with coding style,optimised code and removed redundant code.
Apk for testing :  [app-debug.apk.tar.gz](https://github.com/fossasia/pslab-android/files/1222973/app-debug.apk.tar.gz)

aligned sensor fragment files with coding style and removed redundant code

---

app/src/main/java/org/fossasia/pslab/activity/SensorDataLoggerActivity.java
app/src/main/java/org/fossasia/pslab/activity/ShowLoggedData.java
app/src/main/java/org/fossasia/pslab/models/DataMPU6050.java
app/src/main/java/org/fossasia/pslab/models/SensorLogged.java
app/src/main/res/layout/activity_show_logged_data.xml
app/src/main/res/layout/logged_sensor_data.xml

Fixes issue #503 
Changes: 
- Added 2 layers before showing logged sensor data.
- Added Realm Model for Logged Sensor List.
Apk for testing : 
[app-debug.apk.tar.gz](https://github.com/fossasia/pslab-android/files/1226032/app-debug.apk.tar.gz)
Screencast Link : https://goo.gl/photos/rtfS8eF3MDhmX4bt7

Fixed #503 organised Logged Sensor Data View

---

app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java
app/src/main/java/org/fossasia/pslab/experimentsetup/ACGeneratorExperiment.java
app/src/main/java/org/fossasia/pslab/fragment/SavedExperiments.java
app/src/main/res/layout/ac_generator_experiment_layout.xml
app/src/main/res/values/strings.xml

Fixes issue #523 
Changes: 
- Implemented AC generator experiment
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1228566/app-debug.apk.zip)

Fixes #523 : AC Generator Experiment

---

app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java
app/src/main/java/org/fossasia/pslab/experimentsetup/LightDependentResistorExperiment.java
app/src/main/java/org/fossasia/pslab/fragment/SavedExperiments.java
app/src/main/res/layout/ldr_experiment_dialog.xml

Fixes issue #530 
Changes: 
- Implemented Light Dependent Resistor Experiment
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1230988/app-debug.apk.zip)

Fixes #530 : Light Dependent Resistor

---

app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java
app/src/main/java/org/fossasia/pslab/experimentsetup/AstableMultivibratorExperiment.java
app/src/main/java/org/fossasia/pslab/fragment/AstableMultivibratorFragment.java
app/src/main/java/org/fossasia/pslab/fragment/SavedExperiments.java
app/src/main/res/layout/fragment_astable_multivibrator.xml
app/src/main/res/values/strings.xml

Fixes #500
Changes:
- Implemented Astable Multivibrator
apk:
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1229212/app-debug.apk.zip)

Implemented Astable Multivibrator

---

app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java
app/src/main/java/org/fossasia/pslab/experimentsetup/RampGeneratorExperiment.java
app/src/main/java/org/fossasia/pslab/fragment/SavedExperiments.java
app/src/main/res/layout/ramp_gen_setup.xml

Fixes issue #483 
Changes: 
* Creates the Ramp Generator Experiment
Note: The user doesn't need to set the frequency of SQR1. so the frequency of SQR1 is set to a constant value of 1000 Hz .
> The images above are not of actual experiment.
[app.zip](https://github.com/fossasia/pslab-android/files/1226822/app.zip)

Ramp Generator Experiment

---

app/src/main/java/org/fossasia/pslab/activity/ShowLoggedData.java
app/src/main/res/layout/sensor_list_long_click_dailog.xml
app/src/main/res/values/strings.xml

Fixes issue #534 
Changes: 
- Sensor Data exported successfully as `.txt` file
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/12713808/29466451-8db1ab48-845a-11e7-9dff-bfcffa2d20a1.png"></td>
<td><img src="https://user-images.githubusercontent.com/12713808/29466454-8dc2c7ac-845a-11e7-81e3-eccc52fb92ac.png"></td>
</tr>
</table>
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/12713808/29466452-8db617a0-845a-11e7-88ac-b40baa619f15.png"></td>
<td><img src="https://user-images.githubusercontent.com/12713808/29466453-8db6b3e0-845a-11e7-9594-74b3ec828a48.png"></td>
</tr>
</table>

Fixes #534 exported sensor data as txt file

---

app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java
app/src/main/java/org/fossasia/pslab/experimentsetup/WaterResistanceExperiment.java
app/src/main/java/org/fossasia/pslab/fragment/SavedExperiments.java
app/src/main/java/org/fossasia/pslab/others/MathUtils.java
app/src/main/res/layout/water_resistance_measurement_layout.xml
app/src/main/res/values/strings.xml

Fixes issue #519 
Changes: 
- Implemented Water resistance in AC and DC measurement experiment
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1225260/app-debug.apk.zip)

Fixes #519 : Water Resistance Measurement experiment

---

app/src/main/java/org/fossasia/pslab/communication/PacketHandler.java
app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java

Fixes issue #547 
Changes: 
- Added error catch calls for respective places
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1236557/app-debug.apk.zip)

Fixes #547 : App crash when device unplugged

---

app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java
app/src/main/java/org/fossasia/pslab/experimentsetup/PrecisionRectifierExperiment.java
app/src/main/java/org/fossasia/pslab/fragment/SavedExperiments.java
app/src/main/res/layout/precision_rectifier_dialog.xml
app/src/main/res/layout/precision_rectifier_setup.xml

Fixes issue #484 
Changes: 
* Creates the Precision Rectifier Experiment present under the Op-Amp Experiments.
[app.zip](https://github.com/fossasia/pslab-android/files/1233247/app.zip)
I think my device is damaged as the device is not detected on my laptop/mobile. Someone else can update the screenshots.

Creates Precision Rectifier Experiment

---

app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java

Fixes issue #549 
Changes: 
- Added switch cases to if statements
- Since values needed to be constant, couldn't use string resources
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1236842/app-debug.apk.zip)

Fixes #549 : PerformExperiments adapter switch cases

---

app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java
app/src/main/java/org/fossasia/pslab/experimentsetup/DistanceMeasurementExperiment.java
app/src/main/java/org/fossasia/pslab/fragment/SavedExperiments.java
app/src/main/res/layout/diode_setup.xml

Fixes issue #536 
Changes: 
- Implemented distance measurement experiment
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1234659/app-debug.apk.zip)

Fixes #536: Distance Measurement experiment

---

app/src/main/java/org/fossasia/pslab/activity/ShowLoggedData.java

Fixes issue #539 
Changes: 
- Support for exporting sensor data in csv format added. 
- Data would be exported in format selected in app settings (`txt`,`csv`)

Fixed #539 exported data in csv format

---

app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java
app/src/main/java/org/fossasia/pslab/experimentsetup/AstableMultivibratorExperiment.java
app/src/main/java/org/fossasia/pslab/fragment/AstableMultivibratorFragment.java
app/src/main/java/org/fossasia/pslab/fragment/SavedExperiments.java

Fixes #526 and #527
Changes: 
- Implemented Colpitts Oscillator and Phase Shift Oscillator
**Merge it after PR #524 is merged**
* I have tested fitting sine waves and able to read correct frequencies from the waves. Most probably will be testing on actual circuit today.

Implemented Colpitts Oscillator and Phase Shift Oscillator

---

app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java

Fixes issue #558 
Changes: 
- Added method calls

Fixes #558 : Precision Rectifier and Body resistance experiments

---

app/src/main/res/layout-land/splash_screen.xml
app/src/main/res/layout/saved_experiments_fragment.xml
app/src/main/res/values/strings.xml

Fixes issue #566 
Changes: 
- Fixed UI bugs described in Issue #566 

Fixes #566 fixed UI bugs

---

app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java
app/src/main/java/org/fossasia/pslab/experimentsetup/OscillatorExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/OscillatorExperimentFragment.java
app/src/main/java/org/fossasia/pslab/fragment/SavedExperiments.java
app/src/main/res/layout/fragment_oscillator_experiment.xml

Fixes #540 
Changes: 
- Implemented Wien Bridge Oscillator
- Renamed some files

Implemented Wien Bridge Oscillator

---

app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java
app/src/main/java/org/fossasia/pslab/experimentsetup/OscillatorExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/OscillatorExperimentFragment.java
app/src/main/java/org/fossasia/pslab/fragment/SavedExperiments.java
app/src/main/res/layout/fragment_oscillator_experiment.xml
app/src/main/res/values/strings.xml

Fixes #541 
Changes:
- Implemented Monostable Multivibrator Experiment
**To be merged after #553**
apk: 
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1239982/app-debug.apk.zip)

Implemented Monostable Multivibrator Experiment

---

README.md

Fixes issue #581 
Updated readme with license and maintainer's information and added playstore link.
https://github.com/viveksb007/pslab-android/blob/patch/README.md

Fixes #581 updated readme

---

app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java
app/src/main/java/org/fossasia/pslab/experimentsetup/ServoMotorsExperiment.java
app/src/main/java/org/fossasia/pslab/fragment/SavedExperiments.java
app/src/main/res/layout/servo_motor_layout.xml
app/src/main/res/values/strings.xml

Fixes issue #579 
Changes: 
- Implemented layouts and functionality to perform servo motors related experiments
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1246465/app-debug.apk.zip)

Fixes #579 : Servo Motors

---

app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java
app/src/main/java/org/fossasia/pslab/experimentsetup/StepperMotors.java
app/src/main/java/org/fossasia/pslab/fragment/SavedExperiments.java
app/src/main/res/drawable/ic_arrow_back_black_24dp.xml
app/src/main/res/drawable/ic_arrow_forward_black_24dp.xml
app/src/main/res/layout/stepper_motor_layout.xml
app/src/main/res/values/strings.xml

Fixes issue #575 
Changes: 
- Implemented layout and functionality for stepper motor experiment
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1244015/app-debug.apk.zip)

Fixes #575 : Implement Stepper Motor

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java

Fixes issue #583 and #587 
Changes: 
- Shifted mapping of audio buffer from UI thread to background thread to prevent lag.
- Fragment retains state after screen lock and unlock 
[app-debug.apk.tar.gz](https://github.com/fossasia/pslab-android/files/1251776/app-debug.apk.tar.gz)

fixed app lag and fragment state on screen lock and unlock

---

app/src/main/assets/DOC_HTML/apps/speedofsound.html
app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java
app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
app/src/main/java/org/fossasia/pslab/experimentsetup/AstableMultivibratorExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/OscillatorExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/SpeedOfSoundFragment.java
app/src/main/java/org/fossasia/pslab/fragment/SavedExperiments.java
app/src/main/res/layout/fragment_speed_of_sound.xml
app/src/main/res/values/strings.xml

Fixes #563 
Changes: Implemented Speed of Sound Experiment

Implemented Speed of Sound Experiment

---

app/src/main/java/org/fossasia/pslab/activity/SensorActivity.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentHMC5883L.java
app/src/main/res/layout/activity_sensor.xml

Partly Fixes issue #339 
Changes: Added functionalities to HMC5883L Sensor Fragment
[video link](https://drive.google.com/file/d/0B423XEmWL9vKUG1iZHY0eUpHc1k/view)
**Please suggest the range of the time gap

Added functionality to HMC5883L Sensor Fragment

---

app/src/main/java/org/fossasia/pslab/experimentsetup/CapacitorReactanceExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/ExperimentErrorStrings.java
app/src/main/java/org/fossasia/pslab/experimentsetup/InductorReactanceExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/InvertingOpAmpExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/LRPhaseShiftExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/LightDependentResistorExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/NFETOutputCharacteristicsExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/NFETTransferCharacteristicsExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/NonInvertingOpAmpExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/PrecisionRectifierExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/RCPhaseShiftExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/SummingJunctionExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorAmplifierExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorCBSetup.java
app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorCEInputCharacteristicsExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorCEOutputSetup.java
app/src/main/java/org/fossasia/pslab/experimentsetup/TransistorTransferExperiment.java
app/src/main/java/org/fossasia/pslab/experimentsetup/ZenerSetupFragment.java

Fixes issue #569 
Changes: 
* Implements same set of strings across all experiment files
* Creates a common file for the same
None

Creates a Common Error String Resource File

---

app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentADS1115.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentBH1750.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentBMP180.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentHMC5883L.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentMLX90614.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentMPU6050.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentMPU925X.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentSHT21.java
app/src/main/java/org/fossasia/pslab/sensorfragment/SensorFragmentTSL2561.java

Fixes #339
Changes: Added functionality to remaining Sensor fragments
Screenshots for the change: None

Added functionality to remaining Sensor fragments

---

app/src/main/res/drawable/control_edittext.xml
app/src/main/res/layout-hdpi/control_main_list_item.xml
app/src/main/res/layout-xhdpi/control_main_list_item.xml
app/src/main/res/layout/control_main_list_item.xml
app/src/main/res/layout/fragment_control_main.xml
app/src/main/res/values/dimens.xml

First steps for issues #551 
Changes: 
Updated UI of Control List section
APK:
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1256744/app-debug.apk.zip)

Updated UI of Control List

---

app/src/androidTest/java/org/fossasia/pslab/MainActivityTest.java
app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/pslab/activity/ControlActivity.java
app/src/main/res/layout/activity_control.xml
app/src/main/res/layout/fragment_control_main.xml
app/src/main/res/menu/activity_control_bottom_navigationbar.xml
app/src/main/res/values/styles.xml

Fixes issue #601 
Changes:
- Adjusted layout behaviour when soft keyboard pops up.
- Refactored some code in between. 
Apk for testing 
[app-debug.apk.tar.gz](https://github.com/fossasia/pslab-android/files/1262541/app-debug.apk.tar.gz)

Fixed #601 adjusted layout when softkeyboard pops up

---

app/src/main/java/org/fossasia/pslab/experimentsetup/electronicexperiments/ZenerSetupFragment.java

Fixes issue #603 
Changes: 
- Called update graph routine at each sample point read from device to update graph in real-time

Fixed #603 updated zener I-V graph at each sample point read

---

app/build.gradle
app/src/main/assets/DOC_HTML/apps/I_CAPACITANCE.md
app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java
app/src/main/java/org/fossasia/pslab/fragment/ExperimentDocMdFragment.java
app/src/main/java/org/fossasia/pslab/fragment/SavedExperiments.java
app/src/main/res/layout/experiment_doc_md.xml

Fixes issue #605 
Changes: 
* Documentation md file modified for Capacitance Measurement
* Added the support for MarkdownView library
* A separate layout and fragment has been created for md files so that the existing files in which documentations are linked are not affected.
APK: 
[app.zip](https://github.com/fossasia/pslab-android/files/1272282/app.zip)
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/19410364/29996922-42a42104-9025-11e7-922f-e4d46c8695e3.png" height="320" width="180"></td>
<td><img src="https://user-images.githubusercontent.com/19410364/29996925-465860e4-9025-11e7-9d9b-dcec661283f0.png" height="320" width="180"></td>
<td><img src="https://user-images.githubusercontent.com/19410364/29996930-53ddae04-9025-11e7-902c-91dfb8b4 …

Reformatted md files and added support for Markdownview

---

README.md

Fixes issue #606 
Changes:
- Updated Feature section of readme with current project status.
https://github.com/viveksb007/pslab-android/blob/testing/README.md

Fixed #606 updated Feature section of readme

---

app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java

Fixes issue #617 #618 
Changes: 
- fixed thread that monitors which checkboxes are clicked by replacing `true` with a boolean and making it `false` in `onDestroy` of activity.
- added a check and released audio buffer when activity is destroyed.
APK for testing
[app-debug.apk.tar.gz](https://github.com/fossasia/pslab-android/files/1277230/app-debug.apk.tar.gz)

fixed monitor thread in oscilloscope activity and release of audio record object

---

app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/java/org/fossasia/pslab/fragment/DataAnalysisFragment.java
app/src/main/java/org/fossasia/pslab/fragment/TimebaseTriggerFragment.java
app/src/main/res/values/strings.xml

Fixes #615 
Changes: 
- Aligned no. of samples captured by the Oscilloscope with the timebase.
- Reformatted some code.
- Made few other minor changes
Note: The number of samples is in the power of 2 because sine fitting algorithm in JAVA requires data in the power of 2.
Video link - https://goo.gl/photos/mYStHWy87AhvgCXdA
Apk
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1275351/app-debug.apk.zip)

Aligned the no. of samples captured by the Oscilloscope with Timebase

---

app/build.gradle

Fixes issue #622 
Changes: 
- changed version code and version name

Fixed #622 changed version code and version name

---

app/src/main/java/org/fossasia/pslab/activity/MainActivity.java
app/src/main/res/values/strings.xml

Fixes issue #627 
Changes: added double tap to exit

fixes #627 add double tap to exit

---

app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java
app/src/main/java/org/fossasia/pslab/experimentsetup/schoollevel/MeasureVoltage.java
app/src/main/java/org/fossasia/pslab/fragment/SavedExperiments.java
app/src/main/res/layout/measure_voltage_experiment.xml

Fixes issue #631 
APK:
[pslab.zip.zip](https://github.com/fossasia/pslab-android/files/1313251/pslab.zip.zip)

Measure voltage Experiment

---

app/src/main/AndroidManifest.xml
app/src/main/res/values-v21/styles.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/styles.xml

Fixes issue #635 
Changes:status bar colour changed from dark red to dark white in splashScreen activity

Fixes #635 status bar colour is now dark white

---

app/build.gradle
app/src/main/java/org/fossasia/pslab/activity/MainActivity.java
app/src/main/java/org/fossasia/pslab/others/CustomTabService.java

Fixes issue #641 
Changes: Report issues page will now open in chrome custom tabs

Fixes #641 implement custom tab service

---

app/src/main/AndroidManifest.xml

Fixes issue #652 
Changes: landscape rotation works now

Fix #652 landscape rotation works now

---

README.md

Fixes issue #650 
Changes:
- Added links of video demo on readme.md
https://github.com/viveksb007/pslab-android/blob/patch2/README.md#video-demo

Fixed #650 Added links of video demo in README.md

---

.travis.yml

travis build fixed

---

README.md

Fixes issue #667 
Changes: 
- readme points to build status of development branch

switch to dev branch for travis build status

---

app/build.gradle
app/src/main/java/org/fossasia/pslab/PSLabApplication.java
app/src/main/java/org/fossasia/pslab/fragment/ApplicationsFragment.java
app/src/main/java/org/fossasia/pslab/fragment/ChannelParametersFragment.java
app/src/main/java/org/fossasia/pslab/fragment/ControlFragmentAdvanced.java
app/src/main/java/org/fossasia/pslab/fragment/ControlFragmentMain.java
app/src/main/java/org/fossasia/pslab/fragment/ControlFragmentRead.java
app/src/main/java/org/fossasia/pslab/fragment/DataAnalysisFragment.java
app/src/main/java/org/fossasia/pslab/fragment/DesignExperiments.java
app/src/main/java/org/fossasia/pslab/fragment/ExperimentDocFragment.java
app/src/main/java/org/fossasia/pslab/fragment/ExperimentDocMdFragment.java
app/src/main/java/org/fossasia/pslab/fragment/ExperimentSetupFragment.java
app/src/main/java/org/fossasia/pslab/fragment/HomeFragment.java
app/src/main/java/org/fossasia/pslab/fragment/LAChannelModeFragment.java
app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
app/src/main/java/org/fossasia/pslab/fragment/SavedExperiments.java

Fixes issue #664
Changes: Added LeakCanary to project to detect memory leaks.

Added LeakCanary to the project.

---

app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java

Fixes issue #654 
Apk-
[app-debug.zip](https://github.com/fossasia/pslab-android/files/1403790/app-debug.zip)

diode IV experiment fixed

---

app/src/main/res/layout/body_resistance_measurement_layout.xml
app/src/main/res/layout/capacitor_discharge_layout.xml
app/src/main/res/layout/common_experiment_setup.xml
app/src/main/res/layout/stepper_motor_layout.xml
app/src/main/res/layout/water_resistance_measurement_layout.xml
app/src/main/res/values/dimens.xml

Fixes issue #691 
Changes: Replaced the nested linear layouts to constraint layouts in 5 layout files.
body_resistance_measurement_layout.xml
capacitor_discharge_layout.xml
common_experiment_setup.xml
stepper_motor_layout.xml
water_resistance_measurement_layout.xml
APK:
[app-debug.zip](https://github.com/fossasia/pslab-android/files/1631444/app-debug.zip)

Fixes #691 Replacing nested layouts with constraint layouts

---

app/src/main/java/org/fossasia/pslab/activity/AboutUs.java
app/src/main/java/org/fossasia/pslab/activity/ControlActivity.java
app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/java/org/fossasia/pslab/activity/PerformExperimentActivity.java
app/src/main/java/org/fossasia/pslab/activity/SensorActivity.java
app/src/main/java/org/fossasia/pslab/activity/SensorDataLoggerActivity.java

Fixes issue #708 
Used ButterKnife library in the remaining actvities to maintain uniformity in the code.
Changes:
Included BindView annnotations for the initializarions of views.
Not applicable

Fixes #708 Use ButterKnife BindViews in other activities

---

app/src/main/java/org/fossasia/pslab/activity/SensorDataLoggerActivity.java

Fixes issue #710 
Changes: 
Added proper annotation to prevent crashing.
Not applicable
Apk:
[app-debug.zip](https://github.com/fossasia/pslab-android/files/1711688/app-debug.zip)

Fixes #710 App Crashing in Data Sensor Logger

---

app/src/main/res/layout/ac_generator_experiment_layout.xml
app/src/main/res/layout/body_resistance_measurement_layout.xml
app/src/main/res/layout/capacitor_discharge_layout.xml
app/src/main/res/layout/common_experiment_setup.xml
app/src/main/res/layout/fragment_oscillator_experiment.xml
app/src/main/res/layout/fragment_speed_of_sound.xml
app/src/main/res/layout/measure_voltage_experiment.xml
app/src/main/res/layout/ohms_law_setup.xml
app/src/main/res/layout/opamp_setup.xml
app/src/main/res/layout/precision_rectifier_setup.xml
app/src/main/res/layout/ramp_gen_setup.xml
app/src/main/res/layout/rectifier_setup.xml
app/src/main/res/layout/semiconductor_experiment_layout.xml
app/src/main/res/layout/servo_motor_layout.xml
app/src/main/res/layout/single_channel_mode_la.xml
app/src/main/res/layout/stepper_motor_layout.xml
app/src/main/res/layout/transistor_amplifier_view.xml
app/src/main/res/layout/water_resistance_measurement_layout.xml

Fixes issue #521 
Changes: [Same theme is used for each button in every file.]

Implement a uniform button in saved experiments #521

---

app/src/main/java/org/fossasia/pslab/communication/CommunicationHandler.java
app/src/main/java/org/fossasia/pslab/communication/PacketHandler.java
app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java

Fixes issue #726 
Changes: 
- Increased buffer sizes
- Added DTR signalling
- Fixed issue in fetching functions
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/1748811/app-debug.apk.zip)

Fixes #726: Resistance value measurement corrected

---

app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java

Fixes issue #735 
Changes: Converted the servo motor experiment from Doc format to DocMd format

Fixed issue #735

---

app/src/main/assets/DOC_HTML/apps/P_PiezoBuzzer.md

Changes: Piezo Buzzer's .md file created

Piezo Buzzer Experiment created

---

app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/java/org/fossasia/pslab/activity/SensorDataLoggerActivity.java

Fixes issue #724 #725 
Changes: 
added bind view in oscilloscope acitivity
and added snackbar code in sensordatalogger activity

Fixes issue #724 #725 bug resolved in activities

---

app/src/main/java/org/fossasia/pslab/activity/MainActivity.java
app/src/main/res/anim/fade_in.xml
app/src/main/res/anim/fade_out.xml

Fixes issue #738  
Changes: New animation files added to prevent animation overlapping while activity transition.
Screenshots for the change: None

Fixes #738 : Animation timing resolved

---

README.md

Fixed typos, and grammar

---

app/build.gradle

chore: Prepare next development cycle

---

app/src/main/assets/DOC_HTML/apps/A_AC_AND_DC.md
app/src/main/assets/DOC_HTML/apps/D_NFET.md
app/src/main/assets/DOC_HTML/apps/D_ZenerIV.md
app/src/main/assets/DOC_HTML/apps/D_diodeIV.md
app/src/main/assets/DOC_HTML/apps/L_WIEN_BRIDGE.md
app/src/main/assets/DOC_HTML/apps/Precision_Rectifier.md

Fixes issue #794 
Changes: Fixed the appearance of headings in various activities
[app-debug.zip](https://github.com/fossasia/pslab-android/files/1929526/app-debug.zip)

Fixes #794 Headings of Screenshots

---

app/src/main/assets/DOC_HTML/apps/N_Amplitude_Modulation.md
app/src/main/assets/DOC_HTML/apps/images/schematics/amp_mod.svg
app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java
app/src/main/java/org/fossasia/pslab/fragment/SavedExperiments.java

Fixes issue : #763
Changes: New experiment markdown is added and implemented with its schematic.

schematic revised

---

app/src/main/java/org/fossasia/pslab/fragment/SavedExperiments.java

Fixes issue #764 
Changes: Temporary Toast removed for Dust Sensor Experient

Updated Saved Experiments

---

app/src/main/java/org/fossasia/pslab/activity/MainActivity.java

Fixes issue #795 
Changes: added intent animations
[app-debug.zip](https://github.com/fossasia/pslab-android/files/1929638/app-debug.zip)

Fixes #795 Adding intent animations

---

app/src/main/assets/DOC_HTML/apps/images/schematics/PiezoBuzzer.svg

Fixes issue #819 
Changes: Changed the peizo buzzer image
APK for testing: [Compress the *.apk file into a rar or zip file and upload it here]
[app-debug.apk.tar.gz](https://github.com/fossasia/pslab-android/files/1976433/app-debug.apk.tar.gz)

Changed the peizo buzzer schematic

---

app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
app/src/main/java/org/fossasia/pslab/communication/analogChannel/AnalogInputSource.java
app/src/main/java/org/fossasia/pslab/communication/peripherals/I2C.java
app/src/main/java/org/fossasia/pslab/filters/BandstopFilter.java
app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java

Fixes issue #797 
Changes: Replaced for loops with for each
[app-debug.zip](https://github.com/fossasia/pslab-android/files/1929675/app-debug.zip)

Fixes #797 Replacing for loop with for each

---

app/src/main/res/layout-land/ohms_law_setup.xml

Fixes issue #828 
Changes: Updated the layout files so that it works properly in both the orientations
[app-debug.zip](https://github.com/fossasia/pslab-android/files/1977799/app-debug.zip)

Fixes #828 landscape mode works properly in case of Ohm's law

---

app/src/main/java/org/fossasia/pslab/activity/MainActivity.java
app/src/main/java/org/fossasia/pslab/activity/ShowLoggedData.java
app/src/main/java/org/fossasia/pslab/adapters/ApplicationAdapter.java
app/src/main/java/org/fossasia/pslab/adapters/MPUDataAdapter.java
app/src/main/java/org/fossasia/pslab/communication/CommunicationHandler.java
app/src/main/java/org/fossasia/pslab/communication/PacketHandler.java
app/src/main/java/org/fossasia/pslab/communication/peripherals/RadioLink.java
app/src/main/java/org/fossasia/pslab/communication/peripherals/SPI.java
app/src/main/java/org/fossasia/pslab/communication/sensors/AD7718.java
app/src/main/java/org/fossasia/pslab/communication/sensors/AD9833.java
app/src/main/java/org/fossasia/pslab/communication/sensors/ADS1115.java
app/src/main/java/org/fossasia/pslab/communication/sensors/BH1750.java
app/src/main/java/org/fossasia/pslab/communication/sensors/BMP180.java
app/src/main/java/org/fossasia/pslab/communication/sensors/HMC5883L.java
app/src/main/java/org/fossasia/pslab/communication/sensors/MF522.java
app/src/main/java/org/fossasia/pslab/communication/sensors/MLX90614.java
app/src/main/java/org/fossasia/pslab/communication/sensors/MPU6050.java
app/src/main/java/org/fossasia/pslab/communication/sensors/MPU925x.java
app/src/main/java/org/fossasia/pslab/communication/sensors/SHT21.java
app/src/main/java/org/fossasia/pslab/communication/sensors/SSD1306.java
app/src/main/java/org/fossasia/pslab/communication/sensors/TSL2561.java
app/src/main/java/org/fossasia/pslab/filters/BandstopFilter.java
app/src/main/java/org/fossasia/pslab/items/ExperimentHeaderHolder.java
app/src/main/java/org/fossasia/pslab/others/InitializationVariable.java
app/src/main/java/org/fossasia/pslab/others/NothingSelectedSpinnerAdapter.java
app/src/main/java/org/fossasia/pslab/others/ViewGroupUtils.java

Fixes #804 
Changes: Changed the access of the variables to private wherever applicable
[app-debug.zip](https://github.com/fossasia/pslab-android/files/1936064/app-debug.zip)

fix: changing the access to private

---

app/src/main/java/org/fossasia/pslab/adapters/PerformExperimentAdapter.java

Fixes #830 
Changes: Changed the format to DocMd
APK for testing: [Compress the *.apk file into a rar or zip file and upload it here]
[app-debug.apk.tar.gz](https://github.com/fossasia/pslab-android/files/1986474/app-debug.apk.tar.gz)

fix: changed the format of low pass filter experiment

---

app/build.gradle
app/src/main/java/org/fossasia/pslab/SearchModel.java
app/src/main/java/org/fossasia/pslab/fragment/SavedExperiments.java
app/src/main/res/menu/items_menu.xml
app/src/main/res/values/strings.xml

Fixes #723 
Changes: Search Bar Added within an overflow menu
[app-debug.zip](https://github.com/fossasia/pslab-android/files/1984134/app-debug.zip)

feat: added SearchBar functionality

---

app/src/main/assets/DOC_HTML/apps/C_AC_GENERATOR.html
app/src/main/assets/DOC_HTML/apps/C_AC_GENERATOR.md

Fixes #854 
Changes: Typo fixed and description improved. 
[app-debug.zip](https://github.com/fossasia/pslab-android/files/1996193/app-debug.zip)

fix: AC generator description

---

.github/PULL_REQUEST_TEMPLATE

Fixes #847 
Changes: Removed interfering words between keywords to close issues automatically

fix: PR_TEMPLATE keyword issue

---

app/build.gradle
app/src/main/java/org/fossasia/pslab/activity/MainActivity.java
app/src/main/java/org/fossasia/pslab/fragment/AboutUsFragment.java
app/src/main/res/layout/fragment_about_us.xml
app/src/main/res/values/strings.xml

Fixes issue #852 
Changes: Added AboutUs fragment.
APK for testing: [Compress the *.apk file into a rar or zip file and upload it here]
[app-debug.apk.tar.gz](https://github.com/fossasia/pslab-android/files/1996486/app-debug.apk.tar.gz)

refactor: changed AboutUs activity into fragment

---

app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/res/layout/activity_oscilloscope.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml

Fixes #880 
Changes: The four buttons channel parameters, timebase and trigger, data analysis and xy plot are separated from each other and when selected, there is a color change in the text background  
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2019230/app-debug.zip)

fix: Oscilloscope function button grouping and color changes

---

upload-apk.sh

Fixes #900 
Changes: 
- App is signed after build
- App is released after signing

feat: Upload apps through fastlane

---

.travis.yml

Fixes #903 
Changes:
- Fix script execution as shell

chore: Fix travis script bash execution

---

app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java

Fixes #895 
Changes: Added different colors for different channel in every mode along with adding colors in legend
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2024002/app-debug.zip)

Added colors for different channels in Logic Analyzer instrument

---

app/build.gradle

Fixes #921 
Changes:
- Updated app version

chore: update app version

---

app/src/main/java/org/fossasia/pslab/others/EditTextWidget.java

Fixes #917 
Changes: Fixed the issue of rounding off numbers and setting stepsize in the Advanced section of ControlActivity
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2039553/app-debug.zip)

fix: issue of rounding off the decimal numbers

---

.travis.yml

Fixes #902
Changes: 
- Removed device connected tests to improve build time.

chore: removed device tests from travis

---

app/src/main/java/org/fossasia/pslab/activity/MainActivity.java

Fixes #934 
Changes: Added the Google form for issue collection.
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/2054958/app-debug.apk.zip)

feat: added Google Form for report issue

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/pslab/activity/MultimeterActivity.java
app/src/main/java/org/fossasia/pslab/fragment/InstrumentsFragment.java
app/src/main/res/layout/activity_multimeter.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
build.gradle

Fixes #885 
Changes: Created the multimeter activity
APK for testing: [Compress the *.apk file into a rar or zip file and upload it here]:The apk will only make sense if the pr #884 is merged as there is not different multimeter section in the previous version of app so there is no button to open the activity.

feat: created multimeter activity

---

app/build.gradle

chore: updated app version

---

app/build.gradle
app/src/main/java/org/fossasia/pslab/activity/PowerSourceActivity.java
app/src/main/java/org/fossasia/pslab/items/SquareImageButton.java
app/src/main/res/drawable/control_edittext.xml
app/src/main/res/drawable/ic_arrow_drop_down_white_24dp.xml
app/src/main/res/drawable/ic_arrow_drop_up_white_24dp.xml
app/src/main/res/layout/activity_power_source.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
build.gradle

Fixes #959 
Changes: 
- Replaced older layout with new cardviews
- Implemented a knob similar to the ones available in laboratory DC generators
[powersource.apk.zip](https://github.com/fossasia/pslab-android/files/2066058/powersource.apk.zip)
_APK doesn't include the color change. Here buttons will be gray._

feat: layout for power source instrument

---

app/src/main/java/org/fossasia/pslab/activity/MultimeterActivity.java

Fixes #976 
Changes:added a loop which calculates the average resistance taking 20 values, thus gives a stable value
APK for testing: [Compress the *.apk file into a rar or zip file and upload it here]
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/2080492/app-debug.apk.zip)

refactor: reduced fluctuation of resistance in multimeter

---

.github/PULL_REQUEST_TEMPLATE

Fixes #1005 
Changes: 
- Added a personal checklist to make reviews easier by checking code for formatting issues

docs: updated PR_TEMPLATE to have a checklist

---

app/src/main/java/org/fossasia/pslab/activity/WaveGeneratorActivity.java
app/src/main/java/org/fossasia/pslab/others/WaveGeneratorCommon.java
app/src/main/res/animator-v21/selector_animator.xml
app/src/main/res/drawable/btn_back_rounded.xml
app/src/main/res/drawable/text_color_selector.xml
app/src/main/res/layout-v21/activity_wave_generator.xml
app/src/main/res/layout/activity_wave_generator.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

Fixes #958 
Partly fixes the issue #878
Changes:
-  Implemented the working of the buttons present in the waveform part in the controlling panel in the Wave Generator. 
- The buttons are working and are connected to the Left Hand Side Monitor Screen which shows the properties of the waveforms.
- The seekbar is working and up and down buttons can be used to increase decrease value
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2086761/app-debug.zip)

feat:implemented the working of buttons and seekbar in the waveform panel

---

app/src/main/res/layout-v21/activity_wave_generator.xml
app/src/main/res/layout/activity_wave_generator.xml
app/src/main/res/values-sw600dp/dimens.xml
app/src/main/res/values/dimens.xml

Fixes #982 
Changes: Added the text showing phase in the monitor and phase button in PWM panel.
APK for testing: [app-debug.zip](https://github.com/fossasia/pslab-android/files/2078002/app-debug.zip)

feat:Added the missing phase property in monitor and button for PWM.

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/pslab/activity/PowerSourceActivity.java
app/src/main/res/layout/activity_power_source.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

Fixes #953 
Changes: 
- Added controllability of power sources using Android app
TODO:
- Long click on increment decrement buttons to update values repeatedly #996 
- Dialog box to show information #997
- Make changes to instrument tile #998
- Add device connectivity menu buttons #999
- Save user set values throughout the app #1000
| Device | Multimeter |
| -------- | -------------- |
| ![device-2018-06-08-181541](https://user-images.githubusercontent.com/14261304/41158956-7479cedc-6b48-11e8-8b50-c1cf51e2d68e.png) | ![multimeterresult](https://user-images.githubusercontent.com/14261304/41159317-c436968e-6b49-11e8-90c1-4601739b4a66.JPG) |
[PowerSources.apk.zip](https://github.com/fossasia/pslab-android/files/2084397/PowerSources.apk.zip)

fix: implement functionality in power source instrument

---

app/src/main/java/org/fossasia/pslab/activity/WaveGeneratorActivity.java
app/src/main/java/org/fossasia/pslab/others/WaveGeneratorCommon.java

Fixes #1034 
**Changes**: Changed all the static final variable in both WaveGenerator and WaveGeneratorCommon to using java enum constants.
Note:- This PR requires the PR #1010  to be merged first.
**APK for testing**: [app-debug.zip](https://github.com/fossasia/pslab-android/files/2102814/app-debug.zip)

fix:changed the static final variable into enum

---

app/src/main/java/org/fossasia/pslab/activity/MultimeterActivity.java

Fixes #1035 
**Changes**:
Added shared preferences in the multimeter activity
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/2102402/app-debug.apk.zip)

feat:multimeter now saving its state

---

app/src/main/java/org/fossasia/pslab/activity/OscilloscopeActivity.java
app/src/main/java/org/fossasia/pslab/activity/WaveGeneratorActivity.java
app/src/main/java/org/fossasia/pslab/others/WaveGeneratorCommon.java
app/src/main/res/layout-v21/activity_wave_generator.xml
app/src/main/res/layout/activity_wave_generator.xml

Fixes #1012 
**Changes**:Connected the Wavegenerator module to the Science Lab module to produce sine wave and saw tooth wave.
- [x ] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
**APK for testing**: Currently the work is in progress

feat:produce sine and saw tooth waves through wave generator

---

app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
app/src/main/java/org/fossasia/pslab/communication/digitalChannel/DigitalChannel.java
app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
app/src/main/res/values/strings.xml

Fixes #1033 
**Changes**: 
Implemented Single Channel Mode Logic Analyzer for ID1 pin
[la_one_channel.zip](https://github.com/fossasia/pslab-android/files/2104065/la_one_channel.zip)
For Linux: Right click on extracted file -> Properties -> Permissions -> Give read permission to see the video
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2106315/app-debug.zip)

feat: Implemented One Channel Mode Logic Analyzer

---

app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
app/src/main/res/layout-land/logic_analyzer_logic_lines.xml
app/src/main/res/layout/logic_analyzer_logic_lines.xml

Fixes #1065 
**Changes**: Added progress bar (circle) to indicate that data is being fetched from the device
**Screenshot/s for the changes**:  
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2112754/app-debug.zip)

feat: Added progress bar for Logic Analyzer Instruments

---

app/src/main/res/values/strings.xml

Fixes #1089 
**Changes**: Made changes in the documentation of Logic Analyzer to make it complete.
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2117360/app-debug.zip)

Added proper documentation for Logic Analyzer Instrument

---

app/src/main/java/org/fossasia/pslab/others/SwipeGestureDetector.java

Fixes #1095 
**Changes**: added try-catch block to handle null pointer exception.
- [x ] My code does not contain any extra lines or extra spaces
- [x ] I have requested reviews from other members
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2118249/app-debug.zip)

fix:handled exception in swipe listener

---

app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
app/src/main/java/org/fossasia/pslab/others/SwipeGestureDetector.java
app/src/main/res/layout-land/logic_analyzer_main_layout.xml
app/src/main/res/layout-port/logic_analyzer_main_layout.xml
app/src/main/res/layout/bottom_sheet_custom.xml
app/src/main/res/values/dimens.xml

Fixes #1076
**Changes**: Changed the custom dialog guide to bottom sheet guide
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2117306/app-debug.zip)

feat: added bottom sheet guide for Logic Analyzer

---

README.md

Fixes #1104 
**Changes**: 
- Added Fdroid badge to README

docs: update README to include Fdroid app

---

app/src/main/java/org/fossasia/pslab/activity/LogicalAnalyzerActivity.java
app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java

Fixes #1102 
**Changes**: Added a boolean variable to check the status of the device
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2121408/app-debug.zip)

Handled back press in Logic Analyzer instrument to avoid crashes

---

app/src/main/java/org/fossasia/pslab/activity/PowerSourceActivity.java
app/src/main/java/org/fossasia/pslab/items/SquareImageButton.java

Fixes #996 
**Changes**: 
- Added feature to rapidly increment or decrement values by long pressing buttons
- Documented methods using JavaDocs
[powersource.zip](https://github.com/fossasia/pslab-android/files/2123743/powersource.zip)

feat: rapid increment/decrement feature in power source

---

app/src/main/java/org/fossasia/pslab/others/SwipeGestureDetector.java

Fixes #1118 
**Changes**: Handled the case of collapsing the guide while swiping down
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2125845/app-debug.zip)

fix: Handled DOWN gesture to collapse the guide

---

app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java

Fixes #1051 
**Changes**: Added the functionality of plotting data with different edges option as selected by user
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2108095/app-debug.zip)
NOTE: Please merge PR #1044 before merging this

feat: All edges options working for Single Channel Mode in Logic Analyzer

---

app/src/main/java/org/fossasia/pslab/activity/AccelerometerActivity.java
app/src/main/java/org/fossasia/pslab/adapters/AccelerometerAdapter.java
app/src/main/res/layout/accelerometer_list_item.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

First steps for issues #993 
**Changes**: 
Reading the built in accelerometer sensor and displaying the values, max and min in the three axes
[Updated apk](https://github.com/fossasia/pslab-android/files/2124207/accel_built_in.zip) 
[Initial apk](https://github.com/fossasia/pslab-android/files/2095044/builtin_accel_readings.zip)

feat: Reading built in accelerometer and displaying values

---

app/src/main/java/org/fossasia/pslab/adapters/AccelerometerAdapter.java
app/src/main/res/layout/accelerometer_list_item.xml

Third step for issue #993 
**Changes**: 
- Adding Async task to plot the charts in the list view adapter
Will update them soon
[Updated apk](https://github.com/fossasia/pslab-android/files/2130990/accel_chart_plot.zip)
[accle_chart_plot.zip](https://github.com/fossasia/pslab-android/files/2113663/accle_chart_plot.zip)

feat: Chart plot the acceleration values in three axes

---

app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java

Fixes #1141 
**Changes**: 
The voltages were getting multiplied by a factor of two which was fixed.
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/2145425/app-debug.apk.zip)

refactor: resolved voltage reading issues in AN8, SEN and CAP pins

---

app/src/main/java/org/fossasia/pslab/activity/WaveGeneratorActivity.java
app/src/main/res/drawable/btn_back_rounded.xml
app/src/main/res/drawable/text_color_selector.xml

Fixes #1100 
**Changes**:
- When used in PWM mode the SQ pins for which the value has been set will automatically be activated  
for output
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2129936/app-debug.zip)

feat : added dynamic selection of SQ pins in PWM mode.

---

app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java

Fixes #1135  #1045 
**Changes**: All the pins are being activated and currently all are fetching data for Single Channel Mode in Logic Analyzer
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2135949/app-debug.zip)

fix: Added support for all pins in Singe Channel Mode for Logic Analyzer

---

app/src/main/java/org/fossasia/pslab/activity/WaveGeneratorActivity.java

Fixes #1149 
**Changes**: implemented rapid increase in value of seekbar by long pressing up and down buttons.
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2142791/app-debug.zip)

feat: implemented rapid increase decrease of seekbar value

---

app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java

Fixes #1084 
**Changes**: 
Device now able to measure capacitance
[capacitance.apk.zip](https://github.com/fossasia/pslab-android/files/2146947/capacitance.apk.zip)

feat: solved capacitance bugs

---

app/src/main/java/org/fossasia/pslab/activity/SensorActivity.java
app/src/main/res/layout/sensor_main.xml
app/src/main/res/values/strings.xml

adding guide texts in search box
Fixes #1021 
**Changes**: Showing text rather than keeping it blank to guide the user on how to search for sensors.
[sensors_intrument.zip](https://github.com/fossasia/pslab-android/files/2131312/sensors_intrument.zip)
[sensors_instrument_updated.zip](https://github.com/fossasia/pslab-android/files/2135413/sensors_instrument_updated.zip)

fix: Improvements in Sensors instrument

---

app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java
app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java

Fixes #1124 
**Changes**: Added Two Channel Mode for Logic Analyzer including all edges support
Please use Control Activity to generate waves for testing the apk as Wave Generator is still not generating digital waves for all pins
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2140444/app-debug.zip)
NOTE: Please merge PR #1137 before merging this PR

feat: Added Two channel mode in Logic Analyzer

---

app/src/main/java/org/fossasia/pslab/activity/MultimeterActivity.java

Fixes #1164 
**Changes**:
Added units namely pico, nano, micro and milli farad to the measurement and also reduced the decimal places to two.
[units.apk.zip](https://github.com/fossasia/pslab-android/files/2152584/units.apk.zip)

feat:added units to capacitance measurement

---

app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/pslab/others/GPSLogger.java

Fixes #1049 
**Changes**: 
- Added location capturing implementation
> WIP
> WIP

feat: location for data sets

---

app/src/main/java/org/fossasia/pslab/activity/LuxMeterActivity.java
app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentData.java
app/src/main/java/org/fossasia/pslab/others/CSVLogger.java
app/src/main/res/drawable/menu_icon_save.xml
app/src/main/res/menu/data_log_menu.xml
app/src/main/res/values/strings.xml

Fixes #967 
**Changes**: 
- Added CSV logging functionality
> Not a UI change
[csv.zip](https://github.com/fossasia/pslab-android/files/2160035/csv.zip)

feat: csv logging

---

app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
app/src/main/res/layout-land/logic_analyzer_logic_lines.xml
app/src/main/res/layout/logic_analyzer_logic_lines.xml

Fixes #1166 
**Changes**: Solved the bugs coming in setting the Carousel Picker's size for different screens and also removed the hint text option from the Carousel
6 inch screen 
5.5 inch screen
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2156242/app-debug.zip)

fix: Solved the bugs in Carousel Picker

---

app/src/main/java/org/fossasia/pslab/activity/SensorActivity.java

First fix for #1177 
**Changes**: Multiple entries in the sensors fixed
> None
[fix_sense_multiple_entr.zip](https://github.com/fossasia/pslab-android/files/2164980/fix_sense_multiple_entr.zip)

fix: Sensor label duplicates

---

app/src/main/java/org/fossasia/pslab/activity/LuxMeterActivity.java
app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentData.java
app/src/main/java/org/fossasia/pslab/others/GPSLogger.java
app/src/main/res/values/strings.xml

Fixes #1171 
**Changes**: 
- Modified the GPS logger completely 
- Added dynamic check for permmision
- Added dynamic check for GPS 
- inlcuded the current location of user fetched by gps at the end of the csv file.
[loc_data_csv.zip](https://github.com/fossasia/pslab-android/files/2168233/loc_data_csv.zip)

feat: included the location in csv file

---

app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java

Fixes #1145 
**Changes**: Added `Three Channel Mode` in Logic Analyzer 
**Screenshot/s for the changes**: `WIP`
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2177984/app-debug.zip)

feat: Added Three Channel Mode functionality in Logic Analyzer instrument

---

app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java

Fixes #1153 
**Changes**: Added different methods to handle the rising and falling edges in Logic Analyzer
**Screenshot/s for the changes**: `WIP`
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2177958/app-debug.zip)

fix: Solved issue of rising and falling edges in Logic Analyzer

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/org/fossasia/pslab/activity/LuxMeterActivity.java
app/src/main/java/org/fossasia/pslab/activity/MapsActivity.java
app/src/main/res/drawable/menu_icon_map.xml
app/src/main/res/layout/activity_maps.xml
app/src/main/res/menu/data_log_menu.xml
app/src/main/res/values/strings.xml
build.gradle

Fixes #1210 
**Changes**:
- Added open street maps to Android app
[maps.zip](https://github.com/fossasia/pslab-android/files/2182800/maps.zip)
To view the map;
Go to Luxmeter and from the menu, select Show map

feat: added osm maps

---

app/src/main/java/org/fossasia/pslab/activity/SensorActivity.java

Fixes #1215 
**Changes**: Made use of AsyncTask to run a thread in the background and to set the text in the text view which wasn't possible to set from a three-level running thread
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2187616/app-debug.zip)

fix: Solved the issue of app crash while pressing Autoscan button in Sensors instrument

---

app/src/main/java/org/fossasia/pslab/activity/MultimeterActivity.java
app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java

Fixes #1223 
**Changes**:
Solved the issues in count pulse measurements
Not applicable
[count_pulse.apk.zip](https://github.com/fossasia/pslab-android/files/2193363/count_pulse.apk.zip)

refactor: solved bugs in count pulse measurements

---

app/src/main/res/values/strings.xml

Fixes #1220 
**Changes**: Removed the unnecessary pin options from Logic Analyzer instrument
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2192751/app-debug.zip)

Solved the bug in channel selection in Logic Analyzer

---

app/src/main/res/values/strings.xml

Fixes #1214 
**Changes**:
Merged feeback section into report issues and changed google form
[feedback_bugs.apk.zip](https://github.com/fossasia/pslab-android/files/2189845/feedback_bugs.apk.zip)

feat: merged feedback section into report issues and changed google form

---

app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentConfig.java
app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentData.java
app/src/main/res/layout/fragment_lux_meter_config.xml
app/src/main/res/values/strings.xml

Fixes #1092 
**Changes**: Adding TSL 2561 sensor functionality to the Lux meter
[tls-with-lux meter.zip](https://github.com/fossasia/pslab-android/files/2117745/tls-with-lux.meter.zip)

feat: TSL2561 sensor integration with lux meter

---

app/src/main/java/org/fossasia/pslab/activity/AccelerometerActivity.java
app/src/main/java/org/fossasia/pslab/adapters/AccelerometerAdapter.java

Fixes #1146 #1232
**Changes**: Added a new color to the card showing Y-axis movement and fixed the issue of data resetting by fixing the device's orientation
[accelerometer_bugs.zip](https://github.com/fossasia/pslab-android/files/2196089/accelerometer_bugs.zip)

fix: Solved the bug in Accelerometer instrument coming while changing orientation

---

app/src/main/java/org/fossasia/pslab/activity/LuxMeterActivity.java
app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentData.java
app/src/main/java/org/fossasia/pslab/others/CSVLogger.java
app/src/main/java/org/fossasia/pslab/others/CustomSnackBar.java
app/src/main/java/org/fossasia/pslab/others/GPSLogger.java
app/src/main/res/layout/activity_lux_main.xml
app/src/main/res/values-v21/styles.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

Fixes #1217 
**Changes**: 
- Added snackbar to show the path where the csv file is stored in the external storage
- Added delete option in snack bar to delete the file if not required
[snackbar.zip](https://github.com/fossasia/pslab-android/files/2188477/snackbar.zip)

feat: added snackbar and csv file delete option

---

app/src/main/java/org/fossasia/pslab/fragment/LuxMeterFragmentData.java

Fixes #1170 
**Changes**:
- Smoothed the data plot in Lux Meter
- Removed the data points from the graph which overlapped the data plot
- Changed the width of the data plot line so that it is completely visible
- Changed the high limit for Lux Meter to turn red
- Changed the onscreen visible data limit in the graph
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2198946/app-debug.zip)

fix: Smoothed the data line and changed some graph properties in Lux Meter instrument

---

app/src/main/java/org/fossasia/pslab/activity/WaveGeneratorActivity.java

Fixes #1238 
**Changes**: 
Changed the units in wave generator activity
Very minor change, screenshot will work.

refactor: solved the minor issue of unit in wave generator

---

app/src/main/java/org/fossasia/pslab/activity/PowerSourceActivity.java

Fixes #1241 
**Changes**: Used a variable to check the status if any button is long pressed i.e. are there any threads running
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2205029/app-debug.zip)

fix: Solved bug in working of buttons in Power Source instrument

---

app/build.gradle

Fixes #1256 
**Changes**: Upgraded version to `1.1.14`

chore: upgrade version

---

upload-apk.sh

Fixes #1206 
**Changes**:
- Create two different APKs for master and development branch push events

chore: build apks from development branch

---

app/build.gradle
app/src/main/java/org/fossasia/pslab/activity/MainActivity.java
app/src/main/res/drawable/icon_version.xml
app/src/main/res/menu/activity_main_drawer.xml
app/src/main/res/values/strings.xml

Fixes #1264
**Changes**: 
I have done some changes in the build.gradle so that each time the app VersionName gets updated the string which is made in the gradle will update itself and indirectly update the app Version shown in the drawer menu. 
My reference link is : https://medium.com/@manas/manage-your-android-app-s-versioncode-versionname-with-gradle-7f9c5dcf09bf
Hence now the version in the drawer menu is getting updated automatically.
[app_version_automated.zip](https://github.com/fossasia/pslab-android/files/2216086/app_version_automated.zip)

Updating app versionName automatically

---

app/src/main/java/org/fossasia/pslab/fragment/LALogicLinesFragment.java
app/src/main/java/org/fossasia/pslab/others/LogicAnalyzerAxisFormatter.java

Fixes #1248  #1251 
**Changes**: [Add here what changes were made in this issue and if possible provide links.]
[dynamicLA.zip](https://github.com/fossasia/pslab-android/files/2210189/dynamicLA.zip)
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2210184/app-debug.zip)

fix: Made Logic Analyzer instrument dynamic and documented the code

---

app/src/main/java/org/fossasia/pslab/communication/ScienceLab.java

Fixes #1266 #1277 
**Changes**: 
Corrected the bugs in voltage measurement which occurred due to merging of pr #1221.
Not applicable
[app.apk.zip](https://github.com/fossasia/pslab-android/files/2216513/app.apk.zip)

refactor: solved bugs in voltage measurement and resistance

---

app/src/main/res/layout/accelerometer_list_item.xml

Fixes #1285 
**Changes**: Changed the font style in the Accelerometer instrument to match the current theme of the app
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2225170/app-debug.zip)

fix: Changed fonts to normal in Accelerometer instrument

---

app/build.gradle

Fixes #1289 
**Changes**: 
- Upgraded app to latest version in gradle

chore: upgrade app to 1.1.15

---

upload-apk.sh

Fixes #1206 
**Changes**:
- Generate apks without deleting previous ones

chore: generate apks

---

app/src/main/java/org/fossasia/pslab/activity/MultimeterActivity.java
app/src/main/res/layout-hdpi/activity_multimeter.xml
app/src/main/res/layout-xhdpi/activity_multimeter.xml
app/src/main/res/values-hdpi/dimens.xml
app/src/main/res/values/dimens.xml

Fixes #1292 
**Changes**: 
Removed scroll view in multimeter and added views according to different screens
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/2229308/app-debug.apk.zip)

feat: removed scroll view in multimeter and added views according to different screens

---

.travis.yml

Fixes #1307 
**Changes**: 
- Added a if clause to filter branches

chore: limit travis build

---

app/src/main/res/values/strings.xml

Fixes #1310 
**Changes**: 
Fixed the issues in code
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/2241691/app-debug.apk.zip)

refactor: solved minor bugs in multimeter

---

README.md

Fixes #1317 
**Changes**: 
- Replaced `org.fossasia.pslab` with `org.pslab`

docs: update readme with new app link

---

README.md

Fixes #1338 
**Changes**: 
- Updated license to Apache 2.0
- Fixed broken link

fix: license mismatch

---

app/build.gradle

chore: upgrade to v2.0.1

---

app/build.gradle
app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
app/src/main/java/io/pslab/models/LuxData.java
app/src/main/res/layout/logger_data_item.xml
app/src/main/res/values/dimens.xml
build.gradle

Fixes #1357 
**Changes**: 
Resolved some coding issues in build.gradle file and sensor logger activity and some date issues
**Screenshot/s for the changes**: Not a UI change
**APK for testing**: NA

refractor: minor code changes

---

README.md

Fixes #1345 
**Changes**: 
- Added GSoC'18 members
- Temporarily removed Fdroid link until the new package version gets included in Fdroid.

docs: added maintainers

---

app/src/main/java/io/pslab/activity/MultimeterActivity.java
app/src/main/res/layout/activity_multimeter_main.xml
app/src/main/res/menu/multimeter_log_menu.xml

Fixes #1359 
**Changes**: 
Added data recording functionality in multimeter, now users can record the data of everything which is measured.
Will update soon 
[app.apk.zip](https://github.com/fossasia/pslab-android/files/2281286/app.apk.zip)

feat: implemented basic data recording feature in multimeter

---

app/src/main/java/io/pslab/activity/OscilloscopeActivity.java

Fixes #1367 
**Changes**: Changed the PREFS_NAME and the key for Oscilloscope instrument
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2282921/app-debug.zip)
NOTE: Please merge PR #1355 before merging this PR

fix: Solved issue in Shared Preferences of Oscilloscope instrument

---

app/build.gradle

Fixes #1372 
**Changes**: Upgrade for 2.0.2

chore: upgrade to 2.0.2

---

app/src/main/java/io/pslab/activity/MainActivity.java

Fixes #1374 
**Changes**:
Fixed the bugs coming in the FAQ  and AboutUs Section
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/2299462/app-debug.apk.zip)

refactor: solved bugs in navigation drawer

---

README.md

Fixes #1390 
**Changes**: 
- Added Fdroid link

docs: updated Readme to add Fdroid

---

app/build.gradle

Fixes #1407 
**Changes**:
- Upgraded to v2.0.4

chore: upgrade app to 2.0.4

---

app/src/main/res/menu/activity_main_drawer.xml

Fixes #1404 
**Changes**: Added checkable behavior to true for menu items under other category in the navigation drawer.
[checkable.zip](https://github.com/fossasia/pslab-android/files/2438537/checkable.zip)

feat: Add checkable behavior to menu items under other category 

---

app/build.gradle

Fixes #1423 
**Changes**: Upgrade app

chore: upgrade app to v2.0.5

---

app/build.gradle

Fixes #1440 
**Changes**: 
- Upgraded the app with new changes to instruments

chore: upgraded app to v2.0.6

---

app/src/main/java/io/pslab/activity/CompassActivity.java

Fixes  [#1274](https://github.com/fossasia/pslab-android/issues/1274)
**Changes**: In this PR I collect the values from the sensor and updated magnetic field indicators with it.
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2634244/app-debug.zip)

fix: magnetic field indicators fixed in compass instrument

---

app/src/main/java/io/pslab/activity/AccelerometerActivity.java
app/src/main/java/io/pslab/activity/LuxMeterActivity.java
app/src/main/java/io/pslab/activity/MultimeterActivity.java
app/src/main/java/io/pslab/activity/SensorGraphViewActivity.java
app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
app/src/main/java/io/pslab/fragment/LuxMeterDataFragment.java
app/src/main/java/io/pslab/models/PSLabSensor.java
app/src/main/java/io/pslab/others/CSVLogger.java
app/src/main/java/io/pslab/others/CustomSnackBar.java
app/src/main/java/io/pslab/others/GPSLogger.java
app/src/main/res/drawable/ic_stop_white_24dp.xml
app/src/main/res/menu/lux_data_log_menu.xml
app/src/main/res/values/strings.xml

Fixes #1471
**Changes**: 
- Added stop button and sync functionality between play pause and stop
- Added delete confirmation message to log delete prompt and deletes both log and file upon confirmation
- Implement export and show user where the log is with a prompt to open the location using "Open" button
| ![2](https://user-images.githubusercontent.com/14261304/49914774-97432e00-feb8-11e8-817d-1eb9e4d99b50.png) | ![3](https://user-images.githubusercontent.com/14261304/49914794-aa55fe00-feb8-11e8-9dac-a4ec7a34ece7.png) | ![4](https://user-images.githubusercontent.com/14261304/49914809-b9d54700-feb8-11e8-8dc0-8144e716c6de.png) |
| -------- | -------- | --------- |
| ![5](https://user-images.githubusercontent.com/14261304/49914853-dec9ba00-feb8-11e8-96dd-b9 …

feat: stop button and upgrades to generic sensor

---

app/src/main/java/io/pslab/activity/AccelerometerActivity.java
app/src/main/java/io/pslab/activity/CompassActivity.java
app/src/main/java/io/pslab/activity/MultimeterActivity.java
app/src/main/java/io/pslab/activity/PowerSourceActivity.java

Fixes #1477 
**Changes**: Code was reformated by including import statements.
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2679171/app-debug.zip)

 refactor: Reformat code for ActionBar declaration

---

app/build.gradle

Fixes #1483 
**Changes**:
- Upgraded app version

chore: upgraded app version to v2.0.7

---

.travis.yml
app/build.gradle
app/src/main/res/xml/lux_meter_settings.xml
app/src/main/res/xml/settings_preference_fragment.xml
build.gradle
gradle/wrapper/gradle-wrapper.properties

Fixes #1473 
**Changes**: 
- Upgraded library versions
- Fixed issue in setting preferences getting a padding by default using `app:iconSpaceReserved="false"`
[UpgradedLibs.apk.zip](https://github.com/fossasia/pslab-android/files/2682979/UpgradedLibs.apk.zip)

chore: upgrade gradle dependencies

---

app/src/main/AndroidManifest.xml
app/src/main/res/xml/baro_meter_settings.xml

Fixes #1487 
**Changes**: 
- Made Lux sensor optional in manifest, hopefully fix most of the compatibility issues
[LuxCompatibility.apk.zip](https://github.com/fossasia/pslab-android/files/2684164/LuxCompatibility.apk.zip)

feat: compatibility issues in manifest

---

app/src/main/java/io/pslab/fragment/HomeFragment.java

Fixes #1507 
**Changes**: 
- Updated URL to new link
**APK for testing**: [Link to download](https://raw.github.com/CloudyPadmal/pslab-android/apk/updateURL.apk)

refactor: updated URL

---

app/src/main/java/io/pslab/activity/MultimeterActivity.java

Fixes #1466 
**Changes**:
Restricted data recording only while PSLab is connected
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/2729320/app-debug.apk.zip)

fix:solved the issue of multimeter crash while recording

---

app/src/main/java/io/pslab/activity/MultimeterActivity.java
app/src/main/res/values/strings.xml

Fixes #1530 
**Changes**: 
Added default value of 0.00 to the multimeter
[app-debug.apk.zip](https://github.com/fossasia/pslab-android/files/2753487/app-debug.apk.zip)

fix: added default value to multimeter

---

.github/ISSUE_TEMPLATE

Fixes #1547 Update issue template
**Changes**:
Commented out hints

chore: Comment out hints in the issue template

---

app/src/main/java/io/pslab/activity/SensorActivity.java
app/src/main/res/layout/sensor_main.xml
app/src/main/res/values/dimens.xml

Fixes #1565 
**Changes**: Changes in SensorActivity , sensor_main and dimens.xml file to remove hardcoded dimensions and fix bottom sheet error.
[app-debug.zip](https://github.com/fossasia/pslab-android/files/2920524/app-debug.zip)

Sensor Bottom Sheet Error and Hard coded dimensions in sensor layout removed

---

app/src/main/res/layout/sensor_main.xml
app/src/main/res/values/dimens.xml

Fixes #1616 #1617 
**Changes**: Added missing shadow view and changed the width of the buttons in dimensions file
[sensors.zip](https://github.com/fossasia/pslab-android/files/2948337/sensors.zip)

fix: Solved issues in Sensor activity

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

**Changes**: build.gradle file
- [x ] No modifications done at the end of resource files `strings.xml`, `dimens.xml` or `colors.xml`
- [ x] My code does not contain any extra lines or extra spaces

chore: updated gradle version to 3.3.2

---

app/src/main/res/values/strings.xml

Fixes #1279 
**Changes**: Voltage range added to multimeter bottom sheet

Fix #1279 pins voltage range added to multimeter bottomsheet

---

app/src/main/res/values/strings.xml

Fixes #1640 
**Changes**:strings.xml
- [ x] I have used resources from `strings.xml`, `dimens.xml` and `colors.xml` without hard-coding them
- [x ] My code does not contain any extra lines or extra spaces

Change title  bar of About Us

---

app/src/main/java/io/pslab/activity/MainActivity.java

Fixes #1670 #1668 
**Changes**: No crash on clicking about us and faq in nav menu.
[app-debug (4).zip](https://github.com/fossasia/pslab-android/files/3027021/app-debug.4.zip)

About Us and FAQ crash fixed

---

README.md

Correct link in README

---

app/src/main/java/io/pslab/activity/MainActivity.java

Fixes #1682 
**Changes**: Indicator of current position in navigation drawer had bugs while clicking "Share App" option in the menu. Bug is solved.

Indicator of current position in Navigation Menu improved

---

app/src/main/java/io/pslab/activity/MainActivity.java

Fixes #1585 
**Changes**: 
Removed unused field in the main activity file.
[MainActivity.zip](https://github.com/fossasia/pslab-android/files/2939347/MainActivity.zip)

fix:Removing unused fields from MainActivity.java

---

app/src/main/java/io/pslab/activity/MainActivity.java

Fixes #1675 
**Changes**: Changed hard-coded value to a variable
**Screenshot/s for the changes**: Not Applicable
[app-debug_1.zip](https://github.com/fossasia/pslab-android/files/3139869/app-debug_1.zip)

Improved navigation menu code

---

app/build.gradle

chore: upgrade app to v2.0.11

---

app/src/main/java/io/pslab/activity/LogicalAnalyzerActivity.java
app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java
app/src/main/res/layout/activity_logic_analyzer.xml
app/src/main/res/layout/activity_oscilloscope.xml
app/src/main/res/layout/activity_wave_generator_main.xml
app/src/main/res/values/dimens.xml

Fixes #1687 
**Changes**: Changes made in 3 instruments which didn't have long press functionality like other instruments  This brings consistency in all instruments.
[Uploading app-debug.zip…]()

Added Long Press functionality to remaining instruments

---

app/src/main/java/io/pslab/models/PSLabSensor.java

Fixes #1622 #1653
**Changes**: I have added back button to action bar of PSLab Sensor activity. Hence all the instruments that inherits this activity will have this back button

Fix # 1622, 1653 back button added to required instruments

---

app/src/main/java/io/pslab/activity/DataLoggerActivity.java
app/src/main/res/values/strings.xml

fix: App crash when back button is pressed in Import Log

---

app/src/main/res/values/strings.xml

Fixes save_graph string bug
@CloudyPadmal please merge this

save graph string bug fixed

---

app/src/main/java/io/pslab/others/GPSLogger.java

Fixes #1662 
**Changes**: removed `locationReady` boolean from `GPSLogger` class because it was never set to true because `onLocationChanged` callback is not called always

Fix #1662 location coordinates issue solved

---

app/src/main/java/io/pslab/fragment/AccelerometerDataFragment.java

Fixes #1714 
**Changes**: CSV format made more comprehensive
[accelerometer_csv_format.zip](https://github.com/fossasia/pslab-android/files/3178697/accelerometer_csv_format.zip)
@CloudyPadmal  kindly review this as soon as possible since i need this change to be merged before i implement import log functionality for accelerometer

accelerometer csv format changed

---

app/src/main/java/io/pslab/activity/DataLoggerActivity.java
app/src/main/java/io/pslab/fragment/CompassDataFragment.java
app/src/main/res/layout/import_log_device_type_alert_layout.xml

Fixes partly #1709 #1712 
**Changes**: import log from local storage implemented for gyroscope and compass
@CloudyPadmal  kindly review this. And if you merge this please do not close the issues since saveGraph function is yet to be implemented as mentioned in issue and i will make separate PR for that

import log from local storage implemented for gyroscope and compass

---

app/build.gradle
build.gradle

Fixes partly #1727 
**Changes**: 
- Upgraded version codes
- Increased minimum SDK to support from Android 5 upwards

chore: upgrade app to v2.0.12

---

app/src/main/java/io/pslab/activity/DataLoggerActivity.java

Fixes #1706 
**Changes**: Import log functionality for accelerometer added to data logger activity
[accel_import_log.zip](https://github.com/fossasia/pslab-android/files/3186670/accel_import_log.zip)
@Smit2010  @ho-dor  @cweitat @CloudyPadmal please review

Fix #1706 import log added for accelerometer

---

app/src/main/res/layout/fragment_accelerometer_data.xml
app/src/main/res/layout/fragment_gyroscope_data.xml
app/src/main/res/layout/gyroscope_list_item.xml

Fixes #1721 
**Changes**: Added default values when when sensor absent and cardview size made consistent
[app-debug.zip](https://github.com/fossasia/pslab-android/files/3192779/app-debug.zip)

Gyroscope UI Improved When No Sensor Present

---

app/src/main/java/io/pslab/activity/RoboticArmActivity.java
app/src/main/res/layout/servo_controller_layout.xml

Fixes #1734 
**Changes**: Degree text made editable

Degree text made editable in Robotic Arm Controller Activity

---

app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
app/src/main/java/io/pslab/models/PSLabSensor.java

Fixes #1741 
**Changes**: The UI of logged data of accelerometer is correct.
[app-debug (3).zip](https://github.com/fossasia/pslab-android/files/3222331/app-debug.3.zip)

fix: Accelerometer data log UI

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/io/pslab/activity/DataLoggerActivity.java
app/src/main/java/io/pslab/activity/ThermometerActivity.java
app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
app/src/main/java/io/pslab/fragment/InstrumentsFragment.java
app/src/main/java/io/pslab/fragment/ThermometerDataFragment.java
app/src/main/java/io/pslab/interfaces/sensorloggers/ThermometerRecordables.java
app/src/main/java/io/pslab/models/PSLabSensor.java
app/src/main/java/io/pslab/models/ThermometerData.java
app/src/main/java/io/pslab/others/LocalDataLog.java
app/src/main/res/drawable/thermometer_logo.xml
app/src/main/res/layout/activity_thermometer.xml
app/src/main/res/layout/bottomsheet_thermometer.xml
app/src/main/res/layout/import_log_device_type_alert_layout.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

Fixes #1629 
**Changes**: Added UI for thermometer
[thermo.zip](https://github.com/fossasia/pslab-android/files/3225735/thermo.zip)

Added Thermometer UI

---

app/src/main/java/io/pslab/activity/RoboticArmActivity.java
app/src/main/res/layout/activity_robotic_arm.xml
app/src/main/res/layout/robotic_arm_timeline_textview.xml

Fixes #1747 
**Changes**: Time indication text added 
[robotic_arm_timeline.zip](https://github.com/fossasia/pslab-android/files/3223796/robotic_arm_timeline.zip)
@mariobehling  @CloudyPadmal  @cweitat have a look at this :)

indication of time added to time line of robotic arm controller

---

README.md

**Changes**: The name of robotic arm controller in instruments table was "Compass". Which is corrected
@CloudyPadmal please merge this

Robotic Arm controller name added to readme

---

app/src/main/java/io/pslab/activity/RoboticArmActivity.java
app/src/main/res/layout/activity_robotic_arm.xml

Fixes #1749 
**Changes**:a Red indicator added at the top of time line.

indicator added at the top of timeline

---

app/src/main/java/io/pslab/activity/RoboticArmActivity.java
app/src/main/res/layout/activity_robotic_arm.xml

Fixes #1768 
**Changes**:Indicator moves every second and play.pause and stop button work
[robotic_arm.zip](https://github.com/fossasia/pslab-android/files/3244800/robotic_arm.zip)

Play,Pause,Stop button working in Robotic arm

---

app/src/main/java/io/pslab/activity/RoboticArmActivity.java
app/src/main/java/io/pslab/others/CustomSnackBar.java
app/src/main/res/layout/activity_robotic_arm.xml

Fixes #1766 
**Changes**:
User can now save timeline as csv in robotic arm controller
[servo_save_timeline.zip](https://github.com/fossasia/pslab-android/files/3248889/servo_save_timeline.zip)

Fix #1766 save timeline added to robotic arm controller

---

app/src/main/java/io/pslab/fragment/ThermometerDataFragment.java

Fixes #1779 
**Changes**: Fixed the crash

Fix #1779 Thermometer crash fixed

---

app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java
app/src/main/res/layout-v21/activity_wave_generator.xml
app/src/main/res/layout/activity_wave_generator.xml
app/src/main/res/layout/activity_wave_generator_main.xml
app/src/main/res/values/strings.xml

Fixes #1765 
**Changes**: User can now save configs of waves in csv file
[wave_save_config.zip](https://github.com/fossasia/pslab-android/files/3268911/wave_save_config.zip)

Fix #1765 save configs added to wave generator

---

build.gradle

Fixes #1782 
**Changes**: Min Android 6 or sdk 23
**Screenshot/s for the changes**:N/A
check boxes with `[x]` if the respective task is completed]
[sdk.zip](https://github.com/fossasia/pslab-android/files/3275430/sdk.zip)

min sdk version upgraded to 23

---

app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
app/src/main/java/io/pslab/fragment/InstrumentsFragment.java
app/src/main/res/drawable/robotic_arm.xml

Fixes #1742
**Changes**: New svg logo added for robotic arm
[robotic.zip](https://github.com/fossasia/pslab-android/files/3279735/robotic.zip)

svg logo for robotic arm added

---

app/src/main/java/io/pslab/activity/RoboticArmActivity.java

Fixes #1783 
**Changes**: Robotic arm saving timeline crash fixed
[robotic_arm_save_crash.zip](https://github.com/fossasia/pslab-android/files/3273820/robotic_arm_save_crash.zip)
@CloudyPadmal  @mariobehling  @ho-dor have a look at this

Fix #1783 robotic arm save crash fixed

---

app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
app/src/main/java/io/pslab/fragment/TimebaseTriggerFragment.java

Fixes #1415 
**Changes**: Fourier Transform output generated for channel 1
[oscilloscope_fft_new.zip](https://github.com/fossasia/pslab-android/files/3282499/oscilloscope_fft_new.zip)
@CloudyPadmal  kindly have a look at this. There is small issue, even if we unselect fourier transform checkbox the original wave isn't plotted. I will handle this issue in further commits.

fft output of ch1 working fine

---

app/src/main/java/io/pslab/activity/RoboticArmActivity.java
app/src/main/res/values/strings.xml

Fixes #1794 
**Changes**: 
Validation added to robotic arm servo edit box so user can enter values only in range of 0 - 360
[robotic_arm_valid_values.zip](https://github.com/fossasia/pslab-android/files/3285225/robotic_arm_valid_values.zip)

Fix #1794 validation added to robotic arm edit box

---

app/src/main/java/io/pslab/activity/RoboticArmActivity.java

Fixes #1743 
**Changes**: function added to robotic arm controller to send selected servo degrees to PSLab board
[robotic_arm_working.zip](https://github.com/fossasia/pslab-android/files/3291498/robotic_arm_working.zip)
@CloudyPadmal  can you please check this since i don't have the robotic arm prototype or servos to test.

Fix #1743 working functionality of robotic arm controller added

---

app/src/main/java/io/pslab/activity/DataLoggerActivity.java
app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java
app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
app/src/main/java/io/pslab/interfaces/sensorloggers/WaveGeneratorRecordables.java
app/src/main/java/io/pslab/models/PSLabSensor.java
app/src/main/java/io/pslab/models/WaveGeneratorData.java
app/src/main/java/io/pslab/others/LocalDataLog.java
app/src/main/res/layout/import_log_device_type_alert_layout.xml

Fixes #1789 
**Changes**: User can playback saved wave configurations
[wave_generator_import.zip](https://github.com/fossasia/pslab-android/files/3278000/wave_generator_import.zip)
@CloudyPadmal  @ho-dor  @mariobehling have a look at this

Fix #1789 import log/ playback working fine for wave generator

---

app/src/main/java/io/pslab/activity/OscilloscopeActivity.java

Fixes #1757 
**Changes**: out put of ch1 and ch2 simultaneously doesn't give weird output
before:
after: 
[osciloscope_2.zip](https://github.com/fossasia/pslab-android/files/3293895/osciloscope_2.zip)

ch1 and ch2 simultaneous output working fine in oscilloscope

---

app/src/main/java/io/pslab/activity/RoboticArmActivity.java

Fixes #1784 
**Changes**:Cursor not blinking anymore.
**Screenshot/s for the changes**: N/A
[cursor_blink.zip](https://github.com/fossasia/pslab-android/files/3297687/cursor_blink.zip)

continuous cursor blinking fixed

---

app/src/main/java/io/pslab/activity/DataLoggerActivity.java
app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
app/src/main/java/io/pslab/fragment/OscilloscopePlaybackFragment.java
app/src/main/java/io/pslab/interfaces/sensorloggers/OscilloscopeRecordables.java
app/src/main/java/io/pslab/models/OscilloscopeData.java
app/src/main/java/io/pslab/models/PSLabSensor.java
app/src/main/java/io/pslab/others/LocalDataLog.java
app/src/main/res/layout/activity_oscilloscope.xml
app/src/main/res/layout/fragment_oscilloscope_playback.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

Fixes #1650
**Changes**: logging added to oscilloscope
[osc_logging.zip](https://github.com/fossasia/pslab-android/files/3307675/osc_logging.zip)
@CloudyPadmal @cweitat @mariobehling have a look at this. Logging and play back is working really nice for 1 channel as well as for 2 channels simultaneously. User can see logged data in data logger activity and playback it from there. I have not yet implemented fft in logged data, i.e. user should be able to view fourier transform of the logged wave, i will do that in separate PR. also i have removed Logic Analyzer from the title of issue #1650 , a separate issue will be opened for logic …

Fix #1650 logging added to oscilloscope

---

app/build.gradle

Fixes #1811 
**Changes**: version upgrade
@CloudyPadmal  please check

version upgrade

---

app/src/main/java/io/pslab/activity/OscilloscopeActivity.java

Fixes #1822 
**Changes**: All channels logging and playback working fine
[all_logging.zip](https://github.com/fossasia/pslab-android/files/3317090/all_logging.zip)
@mariobehling  @CloudyPadmal  have a look. All channels can be simultaneously logged and played back with Fourier Transform. Have packed everything in single function, seems really cool

Fix #1822 logging for all channels added

---

app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java

Fixes #1182 #1267 
**Changes**: changed the ```pulse``` argument to false in sqrPWM() function, just like python code.
[osc_pwm.zip](https://github.com/fossasia/pslab-android/files/3340584/osc_pwm.zip)
@CloudyPadmal  Thanks for the help to solve this issue. Please have look at this PR

PWM working fine

---

app/src/main/java/io/pslab/activity/DataLoggerActivity.java
app/src/main/java/io/pslab/activity/OscilloscopeActivity.java
app/src/main/res/layout/import_log_device_type_alert_layout.xml

Fixes #1842
**Changes**: import log working for oscilloscope
[osc_import.zip](https://github.com/fossasia/pslab-android/files/3343022/osc_import.zip)

import log added for oscilloscope

---

scripts/upload-apk.sh

Fixes #1847 
**Changes**: Generated apk changed

apk names changed

---

app/src/main/java/io/pslab/communication/ScienceLab.java

Fixes #1833 
**Changes**: Java Docs for Analog section added

Java Docs for methods in ScienceLab class

---

app/src/main/java/io/pslab/activity/OscilloscopeActivity.java

Fixes #613
**Changes**: curve fitting working fine in oscilloscope
**apk**
[curve_fit.zip](https://github.com/fossasia/pslab-android/files/3351839/curve_fit.zip)

Curve fit in oscilloscope

---

app/src/main/java/io/pslab/activity/OscilloscopeActivity.java

Fixes #1853 
**Changes**: User can use built in mic without connecting PSLab device
[osc.zip](https://github.com/fossasia/pslab-android/files/3364891/osc.zip)

built in mic can be used without conecting to device

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/pslab/activity/MainActivity.java
app/src/main/java/io/pslab/fragment/BluetoothScanFragment.java
app/src/main/res/layout/fragment_bluetooth_scan.xml
app/src/main/res/menu/pslab_connectivity_menu.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

Fixes #1845 
**Changes**: user can scan available bluetooth devices
[bluetooth_scan.zip](https://github.com/fossasia/pslab-android/files/3367188/bluetooth_scan.zip)
@mariobehling @CloudyPadmal @cweitat this is the first step to add bluetooth communication to PSLab. Please guide me for further steps. I am willing to work on firmware code as well to add bluetooth communication

bluetooth scan interface added

---

app/src/main/java/io/pslab/communication/ScienceLab.java

Fixes #1833 
**Changes**: Added docs for few more methods. No clash with #1834 

Java docs added to ScienceLab class

---

app/src/main/java/io/pslab/fragment/AboutUsFragment.java

Fixes #1864 
**Changes**:Correct links added
[about_links.zip](https://github.com/fossasia/pslab-android/files/3383500/about_links.zip)

about facebook/ twitter page links changed

---

app/src/main/java/io/pslab/activity/RoboticArmActivity.java
app/src/main/res/layout/activity_robotic_arm.xml

Fixes #1860 
**Changes**: robotic arm control panel now visible
[robotic_Arm.zip](https://github.com/fossasia/pslab-android/files/3386791/robotic_Arm.zip)

robotic arm control panel now visible

---

app/src/main/java/io/pslab/fragment/LuxMeterDataFragment.java

Fixes #1866 
**Changes**: Max value changed, some formatting in the code
[lux.zip](https://github.com/fossasia/pslab-android/files/3391212/lux.zip)

Lux meter indicator issue fixed

---

app/src/main/java/io/pslab/activity/PowerSourceActivity.java
app/src/main/res/layout/activity_powersource_layout.xml
app/src/main/res/values/dimens.xml

Fixes #1865 
**Changes**: power source values made editable
[power.zip](https://github.com/fossasia/pslab-android/files/3397561/power.zip)

power source values made editable

---

app/src/main/java/io/pslab/activity/DataLoggerActivity.java

Fixes #1869 
**Changes**: singe function created for all imports
[import.zip](https://github.com/fossasia/pslab-android/files/3392022/import.zip)

import log refactor

---

app/src/main/java/io/pslab/activity/MultimeterActivity.java
app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
app/src/main/java/io/pslab/interfaces/sensorloggers/MultimeterRecordables.java
app/src/main/java/io/pslab/models/MultimeterData.java
app/src/main/java/io/pslab/models/PSLabSensor.java
app/src/main/java/io/pslab/others/LocalDataLog.java
app/src/main/res/menu/multimeter_log_menu.xml

Fixes #1863 
**Changes**: adding multimeter log data to realm
[multimeter_log.zip](https://github.com/fossasia/pslab-android/files/3389738/multimeter_log.zip)

Multimeter logging / playback added

---

app/src/main/java/io/pslab/activity/DataLoggerActivity.java
app/src/main/java/io/pslab/activity/PowerSourceActivity.java
app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
app/src/main/java/io/pslab/interfaces/sensorloggers/PowerSourceRecordables.java
app/src/main/java/io/pslab/models/PSLabSensor.java
app/src/main/java/io/pslab/models/PowerSourceData.java
app/src/main/java/io/pslab/others/LocalDataLog.java
app/src/main/res/menu/power_source_menu.xml

Fixes #1861
**Changes**: User can log, playback and import already saved log in power source
[power_source.zip](https://github.com/fossasia/pslab-android/files/3386177/power_source.zip)

power source recording,playback and import working fine

---

app/src/main/java/io/pslab/activity/WaveGeneratorActivity.java

Fixes #1884 
**Changes**: Duty cycle resolution changed
[duty_resolution.zip](https://github.com/fossasia/pslab-android/files/3423773/duty_resolution.zip)

duty resolution made 1 from 10

---

.travis.yml
app/build.gradle
build.gradle
scripts/prep-key.sh
scripts/upload-apk.sh

Fixes #1881 
**Changes**: change build script 
**Screenshot/s for the changes**:N/A
**APK for testing**: WIP

Build script changed

---

scripts/upload-apk.sh

Fixes #1888 
**Changes**: .aab file support added to build script
**Screenshot/s for the changes**: N/A
**APK for testing**: N/A

aab added to build script

---

.travis.yml
scripts/upload-apk.sh

Fixes upload script updated
**Changes**: command to delete and recreate apk branch added

upload_apk script updated

---

scripts/upload-apk.sh

Fixes #1896 
**Changes**:Upload script error fixed

build script errors corrected

---

app/build.gradle

Fixes #1898 
**Changes**: version changed to 2.0.17

version changed to v2.0.17

---

scripts/upload-apk.sh

Fixes #1901 
Changes:
- Updated Script to support aabs for both branches

chore: updated build script to generate bundles

---

scripts/upload-apk.sh

upload script error fixed

---

app/src/main/AndroidManifest.xml
app/src/main/java/io/pslab/activity/CreateConfigActivity.java
app/src/main/java/io/pslab/activity/MainActivity.java
app/src/main/res/drawable/create_config_icon.xml
app/src/main/res/layout/activity_create_config.xml
app/src/main/res/menu/activity_main_drawer.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

Fixes #1882 
**Changes**: User can create config files
[cc.zip](https://github.com/fossasia/pslab-android/files/3456043/cc.zip)
@CloudyPadmal  my local branch for previous PR got messy because of an error while using BFG. Regarding storing files directly on SD card, i did looked up to many docs and stackoverflow, but apparently Android doesn't allow apps other then system apps to store files directly on /sdcard/ folder. We can store files on the app specific folder on sd card which is /sdcard/Android/data/<package>/files, bu i asume in our case that wont make much sense. A better option would be storing the file on local storage and then …

create config file working fine

---

app/src/main/java/io/pslab/fragment/LALogicLinesFragment.java

Fixes #1825
**Changes**: Logic analyzer giving proper output 
**before
**after
[la.zip](https://github.com/fossasia/pslab-android/files/3462472/la.zip)

logic analyzer bug fixed

---

.github/release-drafter.yml

Fixes #1916 
**Changes**: 
- Added script for release-drafter

chore: automatic release drafting

---

.github/release-drafter.yml

Fixes #1916 
**Changes**: 
- Made release name compatible with Fdroid script
- Combined tags
> Not available. Tested with a draft repo.
@adityastic can't add you as a reviewer.

chore: updated release-draft

---

app/src/main/java/io/pslab/activity/DataLoggerActivity.java
app/src/main/java/io/pslab/activity/GasSensorActivity.java
app/src/main/java/io/pslab/adapters/SensorLoggerListAdapter.java
app/src/main/java/io/pslab/fragment/GasSensorDataFragment.java
app/src/main/java/io/pslab/interfaces/sensorloggers/GasSensorRecordables.java
app/src/main/java/io/pslab/models/GasSensorData.java
app/src/main/java/io/pslab/models/PSLabSensor.java
app/src/main/java/io/pslab/others/LocalDataLog.java
app/src/main/res/layout/fragment_gas_sensor.xml

Fixes #1921 
**Changes**: Logging added to mq135 sensor
[mq135_logging.zip](https://github.com/fossasia/pslab-android/files/3489222/mq135_logging.zip)

feat: logging added to mq135

---

app/src/main/java/io/pslab/activity/OscilloscopeActivity.java

Fixes #1518 
**Changes**: unstable oscilloscope bug fixed
**Before:
**After:
[osc.zip](https://github.com/fossasia/pslab-android/files/3490312/osc.zip)
@CloudyPadmal @cweitat have a look. Feels good when after debugging a huge code just couple of line changes do the miracle. :joy:

fix: unstable oscilloscope bug fixed

---

app/src/main/java/io/pslab/activity/MultimeterActivity.java
app/src/main/res/menu/multimeter_log_menu.xml

Fixes #1931
**Changes**: multimeter action bar fixed
[multimeter_actionbar.zip](https://github.com/fossasia/pslab-android/files/3506067/multimeter_actionbar.zip)

fix: multimeter action bar fixed

---

app/src/main/java/io/pslab/activity/LogicalAnalyzerActivity.java
app/src/main/java/io/pslab/fragment/LALogicLinesFragment.java
app/src/main/res/layout-land/logic_analyzer_logic_lines.xml
app/src/main/res/layout/activity_logic_analyzer.xml
app/src/main/res/menu/logical_analyzer_menu.xml

Fixes #1946 
**Changes**:  Actionbar added to logical analyzer
[la_actionbar.tar.gz](https://github.com/fossasia/pslab-android/files/3512367/la_actionbar.tar.gz)

fix: action bar added to logic analyzer

---

app/src/main/java/io/pslab/activity/CreateConfigActivity.java
app/src/main/res/layout/activity_create_config.xml

Fixes #1954 
**Changes**: Added proper scrolling for horizontal view
[create_config_scroll.zip](https://github.com/fossasia/pslab-android/files/3547110/create_config_scroll.zip)

fix: scroll added to create config layout

---

app/src/main/java/io/pslab/activity/RoboticArmActivity.java
app/src/main/res/layout/servo_controller_layout.xml

Fixes #1978 
**Changes**: [Add here what changes were made in this issue and if possible provide links.]
[crash.zip](https://github.com/fossasia/pslab-android/files/3678345/crash.zip)

Crash in robotic arm resolved

---

app/src/main/java/io/pslab/fragment/PSLabPinLayoutFragment.java

Fixes #1991 
**Changes**: 
Corrected Logical analyzer pins descriptions.
**Gif for the changes**:
[apkDebug.zip](https://github.com/fossasia/pslab-android/files/3773484/apkDebug.zip)

fix : Correcting LA pins description.

---

app/src/main/res/values-ru/strings.xml

Add Russian language
[app.zip](https://github.com/fossasia/pslab-android/files/3931530/app.zip)

Add Russian language

---

app/src/main/java/io/pslab/fragment/InstrumentsFragment.java
app/src/main/java/io/pslab/models/PSLabSensor.java

Fixes fossasia#2021 Improving application localization
Changed code opening Instruments
APK for testing : 
[app.zip](https://github.com/fossasia/pslab-android/files/3949247/app.zip)

Fixes #2021 Improving application localization

---

app/src/main/res/values-ru/strings.xml

Fixes #2030
[app.zip](https://github.com/fossasia/pslab-android/files/3963987/app.zip)

Fixed bug : Settings tab in an application with a different language does not open

---

app/src/main/res/values-pol/string.xml

Fixes #2037 and #2014 
**Changes**: For the purpose of the above request I have added an extra language in the form of polish to PSLab android app as there seemed to be a lack of languages.
@hpdang @mariobehling Mentors please review.

Add Language to PSLab Android

---

app/src/main/java/io/pslab/fragment/HomeFragment.java

Fixes #2004 
**Changes**: Enabled JavaScript so that the menu button could work properly and enabled DOM Storage so that the data of current web session is stored
**Checklist**:
feature.zip(https://github.com/fossasia/pslab-android/files/4048978/feature.zip

Fixes #2004 Fixes the menu button in the webview of the website

---

app/src/main/java/io/pslab/fragment/AboutUsFragment.java
app/src/main/res/values-pol/string.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values-si/string.xml
app/src/main/res/values/strings.xml

Fixes #2095 
**Changes**: Added Developers Section in About Us.
**APK for testing**: [app-fdroid-debug.zip](https://github.com/fossasia/pslab-android/files/4132569/app-fdroid-debug.zip)

feat: added developers section in about us

---

app/src/main/res/values-pl/strings.xml

Fixes #2048 
**Changes**: Added a Polish language to strings.xml 

fixes #2048 - add a Polish language

---

app/src/main/res/values-ar/strings.xml

Fixes #2037 
**Changes**: Translated strings.xml into Arabic Language
**APK for testing**: It doesn't need

Added strings.xml in Arabic

---

README.md

**Changes**:  Updated Documentation of README.md

Updated Documentation of README.md

---

app/src/main/res/values/strings.xml

**Changes**: Updated strings.xml

Updated strings.xml

---

app/src/main/java/io/pslab/fragment/FAQFragment.java

@CloudyPadmal 
Sir please check out my PR and merge it.

fix: FAQFragment crash #2126

---

app/src/main/java/io/pslab/fragment/ESPFragment.java
app/src/main/res/layout/fragment_esp.xml

Fixes #2175 
**Changes**: 
1) Done button on keyboard.
2) Press on done button to connect the USB.
https://user-images.githubusercontent.com/70392921/105326123-6a16ed00-5bf3-11eb-84a5-40d6a0b5e9aa.mp4

fix: done button on keyboard will connect to ESP

---

app/src/main/res/layout/fragment_bluetooth_scan.xml

@CloudyPadmal 
In Bluetooth, scan fragment change the rectangle border and divider color

fix: change border color with red

---

.github/dependabot.yml

add configs to dependabot yml

---

.github/dependabot.yml

**Fixes** #2222 
**Changes**: 
- Fixed the configuration file
N/A
**Checklist**:

chore: updated dependabot configuration

---

README.md

**Fixes** #2235 
**Changes**: 
- Configured codacy project under FOSSASIA account and added badge to Readme
N/A
**Checklist**:

docs: updated codacy badge

---

app/src/main/AndroidManifest.xml
build.gradle

**Fixes** #2240 
**Changes**: 
- Updated OSM version
- Modified manifest
N/A
**Checklist**:

fix: geopack version upgrade

---

app/build.gradle
app/src/main/res/layout/activity_robotic_arm.xml

**Fixes** #2280 
**Changes**: 
changed from android to androidx packages
- 
https://user-images.githubusercontent.com/75962762/140631318-32d84040-9bc0-41b6-9ad8-443d4924b931.mp4
**Checklist**:

Fix the crash on opening of ROBOTIC ARM

---

.github/workflows/pull-request.yml

Reverts fossasia/pslab-android#2293

Revert "Using TCK Tested JDK builds of OpenJDK"

---

app/build.gradle

**Fixes** #2315 
**Changes**: 
- Upgraded minor version of app
> N/A
**Checklist**:

chore: upgraded minor version

---

app/src/main/java/io/pslab/fragment/HomeFragment.java

Fixes #2217 
- 
**Checklist**:

Fixed the bug in connect device activity

---

app/src/main/java/io/pslab/adapters/ApplicationAdapter.java
app/src/main/java/io/pslab/fragment/InstrumentsFragment.java

Fixes #2340
- Add different way to update layout of fragment for recent versions of Android
- Some minor code cleanup
- Refactoring of the way Intents are created. This was necessary to reduce complexity and to pass Codacy Static Code Analysis.
https://user-images.githubusercontent.com/11596220/162831392-b3a60b40-9eb0-4d6e-a5ce-fca447bc7791.mp4
**Checklist**:

fix: layout change on orientation change

---

app/src/main/java/io/pslab/communication/ScienceLab.java

Fixes #2100
- fixed formula for calculation of triangle wave
- reformatted code
- optimized imports
I did not change the UI, but this is what the wave looks like in the oscilloscope now.
**Checklist**:

Fix calculation of triangle wave
